"use strict";var _a,_b,_c,_f,_e,_d,_g;function _h(){var r,t,e,n,a,o,l,f,i=[131072,512,2,131584,131330,514,131328,65794,513,66048,256,1,257,258,65536,65537,65538,65792,131329,66049,66050,131073,131074,131585];if(null==_b){for(_c=Array(32),o=_b=Array(32),t=32;0<=--t;)_c[t]=Array(192),o[t]=Array(192);for(r=192;0<=--r;){for(a=r+64,t=24;0<=--t;)e=i[t],o[t][r]="rgb("+((e=e*(a>>1)+(e>>1&65793)*(1&a))>>16)+","+(e>>8&255)+","+(255&e)+")";for(t=9;0<--t;)o[t+23][r]="rgb("+(e=a*t>>3)+","+e+","+e+")";for(
t=32;0<=--t;)_c[t][r]="rgba"+o[t][r].slice(3,-1)+",.125)"}}if(null==_a)for(r=1,t=0,_a=new Uint32Array(627);r<8192;r++){for(a=r;0==(1&a);a>>=1);for(;a%5==0;a/=5);for(n=1;(n*=10)<=1e6&&n%a!=1;);(1==a||n<=1e6)&&(_a[t++]=r)}if(null==_d)for(_d=Array(r=20);0<=--r;)_d[r]=r+5+"px Courier New";for(l=document.getElementsByTagName("div"),_g=[],r=-1;++r<l.length;)"convex"==l[r].getAttribute("name")&&(f=l[r].getElementsByTagName("canvas")).length&&_i(l[r],f[0])}function _i(Qr,jr){function Hr(r,t,e,n,a){var o
,l=n+a;if((o=t-n)<0)for(;--l>=n;)e[l]=r[l+o];else for(;n<l;n++)e[n]=r[n+o]}function _(r,t,e,n,a){var o,l=n+a;if((o=t-n)<0)for(;--l>=n;)e[l]=r[l+o];else for(;n<l;n++)e[n]=r[n+o]}function Jr(r,t){return r.length!=t&&Hr(r,0,r=new Int32Array(t),0,t),r}function Kr(r,t,e){var n;return Mn[n=wt++]=r,dn[n]=t,wn[n]=e,n}function xr(r,t,e,n,a,o){var l,f,i,h,s,g;if((i=e-1)>=(f=0))do{if(0<=(g=n-r[s=(h=f+i>>1)<<1])?g<=a:(g=n-r[s+1])>=-a)return o?(g<0?r[s]=n:n>r[s+1]&&(r[s+1]=n),t[h]++,e):h}while(0<g?(f=1+h
)<=i:(i=h-1)>=f);return o?(s=f<<1,0!=(l=e-f)&&(_(r,s,r,s+2,l<<1),Hr(t,f,t,f+1,l)),r[s]=r[s+(t[f]=1)]=n,e+1):0}function Rr(r,t,e){var n,a,o,l=57.29577951308232;if(t*r<=0)return 0;if(e&&(t*=l,r*=l),Math.abs(t)<=1e4)for(o=-1;++o<_a.length;)if((n=~~(r*(a=_a[o])))==1+~~(t*a))return n/a;return.5*(t+r)}function Lr(r,t,e,n){for(var a,o=-1;++o<t;)r[o]=Rr(r[a=o<<1]+e,r[1+a]-e,n);return _(r,0,r=new Float64Array(t),0,t),r}function lr(r,t,e){var n,a,o,l,f,i,h,s,g,u,y,c,A,b,M=c=e[8]=1,d=u=y=A=e[6]=e[7]=0;0!=(
g=yn[r])&&(s=1+(e[8]=un[r]/g)*(b=e[8]<0?-1:1),M=(1-(u=-(e[6]=sn[r]/g))*u/s)*b,c=1-(A=-(e[7]=gn[r]/g)*b)*A/s,y=(d=-u*A/s)*b),i=M*(o=sn[t])+d*(l=gn[t])+u*(f=un[t]),h=y*o+c*l+A*f,n=1,(a=0)!=(g=Math.hypot(i,h))&&(n=i/g,a=h/g),e[0]=n*M+a*y,e[1]=n*d+a*c,e[2]=n*u+a*A,e[3]=n*y-a*M,e[4]=n*c-a*d,e[5]=n*A-a*u}function fr(r,t,e,n,a,o){var l,f,i;n[t]=e[0]*(l=sn[r])+e[1]*(f=gn[r])+e[2]*(i=un[r]),a[t]=e[3]*l+e[4]*f+e[5]*i,o[t]=e[6]*l+e[7]*f+e[8]*i}function ir(r,t,e,n,a,o,l,f,i){var h,s,g,u,y,c,A;if((g=(h=In[r]
).length)==(s=In[t]).length&&Math.abs(Math.abs(rn[r][3])-Math.abs(rn[t][3]))<=f){for(;0<=--g;)fr(h[g],g,i,a,o,l);if(u=f*f,tt(ln[g=s[n]]-a[e],fn[g]-o[e],hn[g]-l[e])<u){for(y=s.length;tt(ln[A=s[(n+--y)%s.length]]-a[c=(e+y)%h.length],fn[A]-o[c],hn[A]-l[c])<u;)if(y<=1)return 1073741824|(n+s.length-e)%s.length;for(y=s.length;tt(ln[A=s[++n%s.length]]-a[c=(e+--y)%h.length],fn[A]-o[c],hn[A]-l[c])<u;)if(y<=1)return 3221225472|(n+e)%s.length}}return 536870912}function hr(r,t,e,n,a,o,l,f,i,h){for(var s,g,u
,y,c,A=Math.abs(rn[r][3]),b=h*h,M=In[r],d=o[0],w=l[0],v=f[0];0<=t;t--)if(!i[t]&&(g=(s=In[t]).length)==M.length&&Math.abs(Math.abs(rn[t][3])-A)<=h)for(;0<=--g;)if(tt(e[u=s[g]]-d,n[u]-w,a[u]-v)<b){for(y=s.length;tt(e[u=s[(g+--y)%s.length]]-o[y],n[u]-l[y],a[u]-f[y])<b;)if(y<=1)return t;for(c=g+(y=s.length);tt(e[u=s[(c- --y)%s.length]]-o[y],n[u]-l[y],a[u]-f[y])<b;)if(y<=1)return t}return-1}function Ur(r,t){for(var e,n=(e=In[r]).length;0<=--n;)if(e[n]==t)return n;return 0}function G(r,t){var e,n;(n=(
e=O)[r])>e[t]&&(e[r++]=e[t],e[t++]=n,n=e[r],e[r]=e[t],e[t]=n)}function Vr(r,t,e,n){var a,o,l,f,i,h,s,g,u,y,c,A,b,M,d,w,v,m,p,I,k,F,C,E,T,N,q,S,x,R,L,U=2.3283064365386963e-10,V=6.283185307179586,P=sn,B=gn,X=un,D=Array(1);for(D[0]=Array(m=31);0<=--m;)D[0][m]=new Float64Array(4);for(M=mt,m=2147483647,d=ve=we=0;0<=--M;)(p=Bn[n[M]])<m&&tt((o=B[w=Sn[0][M]])*(h=X[v=Sn[1][M]])-(l=X[w])*(i=B[v]),l*(f=P[v])-(a=P[w])*h,a*i-o*f)>=e*e&&(d=M,m=p);for(I=new Float64Array(9),lr(Sn[0][d],Sn[1][d],I),m=F=dt,
k=yn;0<=--m;)fr(m,m,I,ln,fn,hn);for(_(I,0,C=new Float64Array(9),0,9),N=new Float64Array((T=new Float64Array((E=new Float64Array(pt)).length)).length),q=!1,p=n[d];;){for(M=d+1,m=0;0<=--M;)n[M]==p&&(m+=function(r,t,e,n,a,o,l,f,i,h,s,g){var u,y,c,A,b,M,d,w,v,m,p,I,k,F,C,E,T,N,q,S,x,R,L,U,V,P,B,X,D,_,G,O,Y,z,W,Q,j,H=5.421010862427522e-20,J=3.141592653589793,K=6.283185307179586,Z=yn[er=(C=Sn[0])[r]],$=yn[(E=Sn[1])[r]],rr=Ur((T=Sn[2])[r],er),tr=Ur((N=Sn[3])[r],er),er=E[t],nr=C[t],ar=T[t],or=vt;r:for(
F=2,k=0;0<=--F;){if(0==F){if(t==r&&!e)return k+1;er=nr,nr=E[t]}if(!(Math.abs(yn[er]-Z)>i||Math.abs(yn[nr]-$)>i)){if(lr(er,nr,h),Xe)for(S=R=or-1;0<=S;S--){for(x=(q=In[S]).length;0<=--x;)fr(q[x],x,h,o,l,f);if(hr(S,R,ln,fn,hn,o,l,f,xn,i)<0)continue r}else{if(S=Ur(ar,er),536870912==(L=ir(ar,U=T[r],S,rr,o,l,f,i,h))&&536870912==(L=ir(ar,U=N[r],S,tr,o,l,f,i,h)))continue;for(S=or;0<--S;)for(x=3,q=n[S];0<=--x;)q[x]=0;for(x=or;0<=--x;)a[x]=0;for(a[(q=n[0])[0]=ar]=1,a[q[1]=U]|=2,q[2]=L,x=1;x<=or;S++)if(
x<=S){if(or<=x)break;for(U=or;0<=--U&&1==(1&a[U]););for(R=(q=In[U]).length;0<=--R;)fr(q[R],R,h,o,l,f);if((V=hr(U,or-1,ln,fn,hn,o,l,f,xn,i))<0||2==(2&a[V]))continue r;for(P=(q=In[V]).length,u=o[0],y=l[0],c=f[0];0<=--P&&et(ln[L=q[P]]-u,fn[L]-y,hn[L]-c)>=i;);if(536870912==(L=ir(U,V,0,P,o,l,f,i,h)))continue r;a[(q=n[x++])[0]=U]|=1,a[q[1]=V]|=2,q[2]=L}else for(R=(q=Cn[U=(B=n[S])[0]]).length,X=(P=B[2])>>30,P=(D=Cn[V=B[1]]).length+(536870911&P);0<=--R;)if(O=2&a[G=T[L=D[(P-=X)%D.length]]+N[L]-V],0==(
1&a[_=T[L=q[R]]+N[L]-U])){if(2==O)continue r;if(536870912==(L=ir(_,G,O=Ur(_,In[U][R]),Ur(G,In[V][(P-(X-1>>1))%In[V].length]),o,l,f,i,h)))continue r;a[(B=n[x++])[0]=_]|=1,a[B[1]=G]|=2,B[2]=L}else if(0==O)continue r}if(k++,!e){for(x=-1,Y=new Float64Array(9);++x<3;)for(S=3;0<=--S;)for(R=9;0<=(R-=3);)Y[3*S+x]+=s[R+S]*h[R+x];if((w=(d=(z=Y[0])+(W=Y[4]))+(Q=Y[8]))<0&&(w=0==(x=z<W?W<Q?2:1:z<Q?2:0)?z-(W+Q):1==x?W-(Q+z):Q-d),w=.25/(d=.5*Math.sqrt(w+1)),u=(Y[3]+(1-(2&x))*Y[1])*w,y=(Y[2]+(1-(x<<1&2))*Y[6]
)*w,c=(Y[7]+((2&(x^x<<1))-1)*Y[5])*w,m=x<2?0==x?d:u:2==x?y:c,p=x<2?0==x?u:d:2==x?c:y,I=x<2?0==x?y:c:2==x?d:u,0==(w=1-(v=x<2?0==x?c:y:2==x?u:d)*v))continue;for(x=0,u=m/(w=Math.sqrt(w)),y=p/w,c=I/w;x<we&&tt(y*(M=(j=g[0][x])[2])-c*(b=j[1]),c*(A=j[0])-u*M,u*b-y*A)>=H;x++);we<=x&&(x==g[0].length&&(g[0][x]=new Float64Array(4)),(j=g[0][x])[0]=u,j[1]=y,j[2]=c,j[3]=K,we++),(w=2*Math.acos(v))>J&&(w=K-w),w<j[3]&&(j[3]=w)}}}return k}(d,M,q,r,t,E,T,N,e,I,C,D));if(q)break;for(q=!0,Ie=m,m=F;0<=--m;
)fn[m]=-fn[m]}if(pe=m,O=new Int32Array(6),1<(me=Ie)){for(m=we,me=0;0<=--m;)for((w=~~(V/D[0][m][3]+.5))>me&&(me=w),p=0;p<6;p+=2)if(0==(S=O)[p]||S[p]==w){S[p]=w,S[p+1]++;break}G(4,2),G(2,0),G(4,2)}for(M=p=F,Se=!0;(y=k[--M])<e;)if(M<=0)return;for(b=Array(m=15);0<=--m;)b[m]=new Float64Array(3);for(a=P[m=M],o=B[M],l=X[M],A=U*y;0<=--m;)if((c=k[m])>=e&&et(s=o*(h=X[m])-l*(i=B[m]),g=l*(f=P[m])-a*h,u=a*i-o*f)>=A*c){for(p=m,A*=c;;){if(--p<0){(x=b[0])[0]=s/(A=y*c),x[1]=g/A,x[2]=u/A,ve=1;break}if(Math.abs(
P[p]*s+B[p]*g+X[p]*u)>=A)break}break}for(R=new Uint8Array(vt),w=M;;){for(v=F,a=P[w],o=B[w],l=X[w],A=k[w];0<=--v;)v!=w&&Math.abs(k[v]-A)<=e&&(b=function(r,t,e,n,a,o,l,f,i){var h,s,g,u,y,c,A,b,M,d,w,v,m,p=5.421010862427522e-20,I=3019169939857233e154;if(0==(u=et(r,t,e))&&0==(u=et(r*=I,t*=I,e*=I)))return i;for(y=A=ve,r/=u,t/=u,e/=u;0<=--y;)if(tt(t*(g=(b=i[y])[2])-e*(s=b[1]),e*(h=b[0])-r*g,r*s-t*h)<p)return i;for(y=l.length;0<=--y;)l[y]=!1;for(M=sn,d=gn,w=un,y=l.length;0<=--y;)if(!l[y]){for(c=(
m=In[y]).length;0<=--c;)u=2*((h=M[v=m[c]])*r+(s=d[v])*t+(g=w[v])*e),n[c]=h-r*u,a[c]=s-t*u,o[c]=g-e*u;if((c=hr(y,y,M,d,w,n,a,o,l,f))<0)return i;l[c]=!0}return A==i.length&&(i[A]=new Float64Array(3)),(b=i[A])[0]=r,b[1]=t,b[2]=e,ve++,i}(P[v]-a,B[v]-o,X[v]-l,E,T,N,R,e,b));if(w==p||(w=w==M?m:p)<0)break}for(m=R.length;0<=--m;)R[m]=!1;for(m=R.length;0<=--m;)if(!R[m]){for(p=(L=In[m]).length;0<=--p;)E[p]=-P[w=L[p]],T[p]=-B[w],N[p]=-X[w];if((p=hr(m,m,P,B,X,E,T,N,R,e))<0)return void(Se=!1);R[p]=!0}}
function nr(r,t,e,n,a){var o;r[3]=a,1<=Math.abs(r[0]=t/=o=et(t,e,n))?r[1]=r[2]=0:1<=Math.abs(r[1]=e/=o)?r[0]=r[2]=0:1<=Math.abs(r[2]=n/=o)?r[0]=r[1]=0:1<=t*t+e*e?r[2]=0:1<=t*t+(o=n*n)?r[1]=0:1<=e*e+o&&(r[0]=0)}function Zr(r,t){for(var e,n,a,o,l,f,i,h,s,g,u,y,c,A,b,M,d,w,v,m,p,I,k,F,C,E,T,N,q,S,x,R,L,U,V,P,B,X,D,_,G,O,Y,z,W,Q,j,H,J,K,Z,$,rr,tr=e=n=a=o=l=f=i=h=s=g=0,er=vt;0<=--er;)for(v=2,p=ln[m=(w=In[er])[0]],I=fn[m],k=hn[m],F=ln[m=w[1]],C=fn[m],E=hn[m];v<w.length;v++)u=(x=C-I)*(V=(q=hn[m=w[v]]
)-k)-(R=E-k)*(U=(N=fn[m])-I),y=R*(L=(T=ln[m])-p)-(S=F-p)*V,c=S*U-x*L,P=(A=p+F)+T,B=(M=(b=p*p)+F*A)+T*P,X=p*b+F*M+T*B,D=B+p*(P+p),_=B+F*(P+F),G=B+T*(P+T),O=(A=I+C)+N,Y=(M=(b=I*I)+C*A)+N*O,z=I*b+C*M+N*Y,W=Y+I*(O+I),Q=Y+C*(O+C),j=Y+N*(O+N),H=(A=k+E)+q,J=(M=(b=k*k)+E*A)+q*H,K=k*b+E*M+q*J,Z=J+k*(H+k),$=J+E*(H+E),rr=J+q*(H+q),tr+=d=u*P,e+=Math.abs(d),n+=u*B,a+=y*Y,o+=c*J,l+=u*X,f+=y*z,i+=c*K,h+=u*(I*D+C*_+N*G),s+=y*(k*W+E*Q+q*j),g+=c*(p*Z+F*$+T*rr),F=T,C=N,E=q;return r[0]=n/(d=4*(Math.abs(tr
)>=16*ze?tr:0!=e?e:.25)),r[1]=a/d,r[2]=o/d,null!=t&&(u=(A=r[0]/24)*n,function(r,t,e,n,a,o,l,f,i){var h,s,g,u,y,c,A,b,M,d,w,v,m,p,I,k,F,C,E,T,N,q,S,x,R=.7071067811865476,L=I=k=F=C=E=T=N=q=0,U=0==r&&0==n&&0==o;r:for(;;){if(0==t){if(0==e){if(v=r,L=1,0==a){m=n,p=o,C=q=1;break r}if(U){p=-(m=a),N=-(C=E=q=R);break r}c=Math.hypot(n-o,2*a),p=(n*o-a*a)/(m=.5*((h=n+o)<0?h-c:h+c)),Math.abs(c=m-n)>Math.abs(h=p-n)?(C=q=a/(s=Math.hypot(a,c)),N=-(E=c/s)):(E=-(N=a/(s=Math.hypot(a,h))),C=q=h/s);break r}if(0==a){
if(v=n,I=1,U){p=-(m=e),q=-(F=T=E=R);break r}c=Math.hypot(r-o,2*e),p=(r*o-e*e)/(m=.5*((h=r+o)<0?h-c:h+c)),Math.abs(c=m-o)>Math.abs(h=p-o)?(q=-(F=c/(s=Math.hypot(e,c))),T=E=e/s):(T=E=h/(s=Math.hypot(e,h)),F=-(q=e/s));break r}if(0==r&&0==n){c=Math.sqrt(o*o+4*(h=e*e+a*a)),p=-h/(m=.5*(o<0?o-c:o+c)),F=e/(s=Math.sqrt(m*m+h)),C=a/s,E=m/s,T=e/(s=Math.sqrt(p*p+h)),N=a/s,q=p/s,v=0,L=a/(s=Math.hypot(e,a)),I=-e/s,p<m&&(L=-L,I=-I);break r}}if(0==e&&0==a){if(v=o,k=1,U){p=-(m=t),T=-(F=C=N=R);break r}
c=Math.hypot(r-n,2*t),p=(r*n-t*t)/(m=.5*((h=r+n)<0?h-c:h+c)),Math.abs(c=m-r)>Math.abs(h=p-r)?(F=N=t/(s=Math.hypot(t,c)),T=-(C=c/s)):(C=-(T=t/(s=Math.hypot(t,h))),F=N=h/s);break r}if(0==o){if(0==r&&0==e){c=Math.sqrt(n*n+4*(h=t*t+a*a)),p=-h/(m=.5*(n<0?n-c:n+c)),F=t/(s=Math.sqrt(m*m+h)),C=m/s,E=a/s,T=t/(s=Math.sqrt(p*p+h)),N=p/s,q=a/s,v=0,L=-a/(s=Math.hypot(t,a)),k=t/s,p<m&&(L=-L,k=-k);break r}if(0==n&&0==a){c=Math.sqrt(r*r+4*(h=t*t+e*e)),p=-h/(m=.5*(r<0?r-c:r+c)),F=m/(s=Math.sqrt(m*m+h)),C=t/s,
E=e/s,T=p/(s=Math.sqrt(p*p+h)),N=t/s,q=e/s,v=0,I=e/(s=Math.hypot(t,e)),k=-t/s,p<m&&(I=-I,k=-k);break r}}for(v=r,(x=0!=e)?(q=-(C=t/(d=Math.hypot(t,e))),m=n+(s=(N=E=e/d)*(h=2*C*a+N*(o-n))),p=o-s,w=a-C*h):(m=n,p=o,d=t,w=a,C=q=1),L=1,S=8;0<=--S&&(A=Math.abs(v)+Math.abs(m),Math.abs(d)+A!=A);){if(A=Math.abs(m)+Math.abs(p),u=Math.hypot(h=(m-v)/(2*d),1),c=d/(h<0?h-u:h+u),Math.abs(w)+A!=A)if(Math.abs(w)>=Math.abs(h=p-v+c)?(b=h/w,b*=y=1/(u=Math.hypot(b,1))):(y=w/h,y*=b=1/(u=Math.hypot(y,1))),p+=g=y*(u=(
m-p)*y+2*b*w),T=y*F+b*(c=T),F=b*F-y*c,N=y*C+b*(c=N),C=b*C-y*c,q=y*E+b*(c=q),E=b*E-y*c,M=b*d,Math.abs(c=y*d)>=Math.abs(h=b*u-w)){if(0==c){w=0,m-=g;continue}w=c*(u=Math.hypot(b=h/c,1)),b*=y=1/u}else w=h*(u=Math.hypot(y=c/h,1)),y*=b=1/u;else h=m-v+c,g=w=0,Math.abs(c=M=d)>=Math.abs(h)?(b=h/c,b*=y=1/(u=Math.hypot(b,1))):(y=c/h,y*=b=1/(u=Math.hypot(y,1)));m=(h=m-g)+(g=y*(u=(v-h)*y+2*b*M)),F=y*L+b*(c=F),L=b*L-y*c,C=y*I+b*(c=C),I=b*I-y*c,E=y*k+b*(c=E),k=b*k-y*c,v-=g,d=b*u-M}for(S=8;0<=--S&&(A=Math.abs(m
)+Math.abs(p),Math.abs(w)+A!=A);)u=Math.hypot(h=(g=p-m)/(2*w),1),Math.abs(w)>=Math.abs(h=g+w/(h<0?h-u:h+u))?(b=h/w,b*=y=1/(u=Math.hypot(b,1))):(y=w/h,y*=b=1/(u=Math.hypot(y,1))),p+=g=y*(u=(m-p)*y+2*b*w),T=y*F+b*(c=T),F=b*F-y*c,N=y*C+b*(c=N),C=b*C-y*c,q=y*E+b*(c=q),E=b*E-y*c,m-=g,w=b*u-w;x&&(T=-T,N=-N,q=-q);break r}nr(l,L,I,k,v),nr(f,F,C,E,m),nr(i,T,N,q,p)}((f+i)/60-((y=(b=r[1]/24)*a)+(c=(M=r[2]/24)*o)),A*a-h/120,M*n-g/120,(l+i)/60-(u+c),b*o-s/120,(l+f)/60-(u+y),t[0],t[1],t[2])),Rr((A=tr/6)+(
b=De*De*ze*3),A-b,!1)}function v(r,t){var e;return r-(e=r-t)==t&&e+t==r}function m(r,t,e){var n,a;return r?isFinite(r)?(t[0]=r=Math.abs(r),n=e[0],e[1],4294967295<++n&&(n=0,0),a=t[0],isFinite(a)?a-r:199584030953472e278):1/0:Number.MIN_VALUE}function $r(r,t){for(var e,n,a,o,l,f,i,h,s,g,u,y,c,A,b,M,d=t,w=e=r[0];0<--d;)(i=r[d])<w&&(w=i),e<i&&(e=i);if((l=w)*(f=e)<=0)return 0;g=new Uint32Array((s=new Float64Array(1)).buffer);r:for(a=.5*(w+e),o=0;(n=.5*(w+e))!=w&&n!=e;)t:for(h=n;;){for(d=t;0<=--d;)if(
!v(r[d],h)){if(s[0]=h,u=c=g[0],0==(2146435072&(y=A=g[1])))for(;y=y<<1|u>>>31,u<<=1,0==(2146435072&y););if(!(u||1048575&y)){for(b=d+1,M=0;0<=--b;)if(!v(i=r[b],h)&&3==(M|=i<h?1:2))break r;1==M?e=n:w=n;continue r}if(c){for(u=1;!(c&u);u<<=1);g[0]=c&~u,g[1]=A}else{for(y=1;!(A&y);y<<=1);g[0]=c,g[1]=A&~y}h=s[0];continue t}if((o=h)==a)break r;o<a?w=n:e=n;continue r}return 0!=o&&((i=m(l,s,g))>(h=m(f,s,g))?i:h)>((w=m(l-o,s,g))>(e=m(f-o,s,g))?w:e)?o:0}function rt(r,t){for(var e,n,a=t,o=e=r[0];0<--a;)(
n=r[a])<o&&(o=n),e<n&&(e=n);return e-o}function Pr(r,t,e,n,a){var o,l,f,i;if(e<=3)return 1==t?"equilateral triangle":2==t?"isosceles triangle":"scalene triangle";if(4==e)return 1==t?1==r?"square":"rhombus":2==t?a[0]==a[2]&&a[1]==a[3]?1==r?"rectangle":"parallelogram":a[0]==a[1]&&a[2]==a[3]||a[0]==a[3]&&a[1]==a[2]?2==r?"tri-equiangular kite":"kite":2==r?"tri-equilateral trapezoid":"tri-equilateral tetragon":2==r&&(n[0]==n[1]&&n[2]==n[3]||n[0]==n[3]&&n[1]==n[2]
)?"isosceles trapezoid":"irregular tetragon";if(o=l=!1,0==(1&e))if(1==t&&2==r){for(f=0,i=2;i<e&&n[f]==n[i];f++,i++);o=e<=i}else if(1==r&&2==t){for(f=0,i=2;i<e&&a[f]==a[i];f++,i++);l=e<=i}return!(o|l)||16<e?(1==t&&1==r?"regular ":function(r,t,e){for(var n,a,o,l=0,f=(n=r)>>1,i=r+1>>1;0<=--n;){for(a=1,o=n+r;a<i&&e[(o-a)%r]==e[(n+a)%r];a++);if(i<=a){for(a=0;a<f&&t[(o-a)%r]==t[(n+a+1)%r];a++);f<=a&&l++}}for(n=r;0<=--n;){for(a=1,o=n+r;a<i&&t[(o-a)%r]==t[(n+a)%r];a++);if(i<=a){for(a=0;a<f&&e[(o-a-1
)%r]==e[(n+a)%r];a++);f<=a&&l++}}if(0<l)return((l>>=1)<=3?_e[l-1]:l+"-")+"mirror-symmetric ";for(n=r>>1;2<=n;n--)if(r%n==0){for(a=r/n,o=0;o<a;o++){for(l=1;l<n&&t[o]==t[o+a*l]&&e[o]==e[o+a*l];l++);if(l<n)break}if(o==a)break}return 1<n?"C"+n+"-symmetric ":"irregular "}(e,n,a))+(e<=16?_f[e-5]:e+"-gon"):_f[e+(o?7:6)]}function tt(r,t,e){return t*=t,(r*=r)<(e*=e)&&t<e?r+t+e:r<t?r+e+t:t+e+r}function et(r,t,e){return Math.sqrt(tt(r,t,e))}function Br(r,t){var e,n;return Math.abs((e=r[t])+(n=en[t])
)<ze?-n:e}function Xr(r,t,e,n,a,o,l,f,i,h){for(var s,g,u,y,c,A,b,M,d,w,v,m=0==n?En:Cn,p=Sn[n+1],I=Sn[n],k=dt;0<=--k;)l[k]=0;for(k=i.length;0<=--k;)i[k]=!1;for(A=r,l[u=t?p[A]:I[A]]=s=g=1,h&&(w=o[0]==(a[0]=1));;){for(f[A]=1,i[d=(y=I[A]+p[A]-u)<u?A+mt:A]=!0,k=b=(v=m[y]).length;0<=--k&&v[k]!=A;);if(0==(c=l[y]))A=v[(k+b+e)%b],l[y]=c=++s;else if(i[mt+(A<<1)-d]){for(M=1,k+=b;M<b&&i[I[A=v[(k+e*M)%b]]+p[A]<y<<1?A+mt:A];M++);if(b<=M)return void(h&&(a[g++]=1,Hr(a,0,o,0,g)))}if(h){if(w){if(c>o[g])return
;w=c==o[g]}a[g++]=c}u=y}}function Dr(r,t,e,n,a,o,l){var f,i=r;for(n[0]=2147483647;i<mt;i++)if(i==r||1==o[i])for(f=-3;(f+=2)<=1;)Xr(i,!1,f,t,e,n,a,o,l,!0),Xr(i,!0,f,t,e,n,a,o,l,!0)}function wr(){for(var r,t,e,n,a,o,l,f,i,h,s,g,u,y,c,A,b,M,d,w,v,m,p,I,k,F,C,E,T,N,q,S,x,R,L,U,V,P,B,X,D,_,G,O,Y,z,W,Q,j,H,J,K,Z,$,rr,tr,er,nr,ar,or,lr,fr,ir,hr,sr,gr,ur,yr,cr,Ar,br,Mr,dr,wr,vr,mr,pr,Ir,kr,Fr,Cr=2.3283064365386963e-10,Er=1.4629180792671596e-9,Tr=De*Cr,Nr=new Float64Array((c=new Float64Array((
y=new Int32Array((u=new Int32Array((g=new Int32Array((s=new Int32Array(h=mt)).length)).length)).length)).length<<1)).length),qr=new Int32Array((b=Array(t=A=vt)).length),Sr=0;0<=--t;)Sr+=e=In[t].length,b[t]=new Int32Array(e);for(d=new Float64Array((M=new Int32Array(Sr)).length<<1),v=new Int32Array((w=Array(A)).length),p=0,m=new Float64Array(Sr>(t=h)?Sr:h);0<=--t;)p=xr(c,g,p,m[t]=et(sn[l=Sn[0][t]]-sn[f=Sn[1][t]],gn[l]-gn[f],un[l]-un[f]),Tr,!0);for(t=h;0<=--t;)s[t]=xr(c,g,p,m[t],Tr,!1);for(vn=Lr(c,
p,Tr,!1),Bn=Jr(g,Yr=p),I=0,t=h;0<=--t;)I=xr(Nr,y,I,m[t]=(q=t,O=O=G=_=D=V=void 0,_=3.141592653589793,G=In[V=(X=Sn)[2][q]],O=Ur(V,L=X[0][q]),Y=(D=rn[V+=(B=X[3][q])-(P=G[(O+1)%G.length]==(U=X[1][q])?V:B)])[0],z=D[1],W=D[2],Q=(D=rn[P])[0],j=D[1],H=D[2],J=Math.atan2(et(S=z*H-W*j,x=W*Q-Y*H,R=Y*j-z*Q),Y*Q+z*j+W*H),O=Ur(B,L),((G=In[B])[(O+1)%G.length]==U?V:P)==B?J:_+J*(0<=S*(sn[U]-sn[L])+x*(gn[U]-gn[L])+R*(un[U]-un[L])?1:-1)),Er,!0);for(t=h;0<=--t;)u[t]=xr(Nr,y,I,m[t],Er,!1);for(mn=Lr(Nr,I,Er,!0),Xn=Jr(
y,zr=I),t=A,Sr=k=0;0<=--t;)for(e=(r=In[t]).length,f=r[0],i=r[1];0<=--e;)k=xr(d,M,k,m[Sr++]=(K=t,Z=l=r[e],rr=i,Ar=cr=yr=ur=gr=sr=hr=ir=fr=nr=er=tr=void 0,ir=3.141592653589793,hr=(tr=(ar=sn)[$=f])-ar[Z],sr=(er=(or=gn)[$])-or[Z],gr=(nr=(lr=un)[$])-lr[Z],ur=ar[rr]-tr,yr=or[rr]-er,cr=lr[rr]-nr,Ar=Math.atan2(et(tr=sr*cr-gr*yr,er=gr*ur-hr*cr,nr=hr*yr-sr*ur),hr*ur+sr*yr+gr*cr),ir+Ar*(0<=tr*(fr=rn[K])[0]+er*fr[1]+nr*fr[2]?-1:1)),Er,!0),i=f,f=l;for(t=A,Sr=0;0<=--t;)for(e=(r=b[t]).length;0<e;e--
)r[e%r.length]=xr(d,M,k,m[Sr++],Er,!1);for(pn=Lr(d,k,Er,!0),Dn=Jr(M,Wr=k),t=A;0<=--t;)for(F=b[t],e=(r=Cn[t]).length;0<=--e;)F[e]|=s[r[e]]<<16;for(C=0,t=A;0<=--t;){for(e=Sr=0,r=b[t];++e<r.length;)for(n=0;n<r.length;n++)if(0!=(E=r[(n+Sr)%r.length]-r[(n+e)%r.length])){0<E&&(Sr=e);break}r:for(e=0;e<C;e++)if((T=w[e]).length==r.length){for(o=r.length;0<=--o;)if(T[o]!=r[(o+Sr)%r.length])continue r;break}if(C<=e){for(T=w[e]=new Int32Array(o=r.length);0<=--o;)T[o]=r[(o+Sr)%r.length];C++}v[qr[t]=e]++}for(
Mr=C,(br=w).length=Mr,kn=br,Gn=Jr(v,C),N=new Int32Array((F=new Int32Array(pt)).length),zn=new Int32Array((Yn=new Int32Array((On=new Int32Array((Fn=Array(t=de=C)).length)).length)).length);0<=--t;){for(e=(r=w[t]).length,Sr=0;0<=--e;){for(o=0,a=65535&r[e];o<Sr&&a!=F[o];o++);Sr<=o&&(F[Sr++]=a)}for(Yn[t]=Sr,e=(r=w[t]).length,Sr=0;0<=--e;){for(o=0,a=r[e]>>>16;o<Sr&&a!=F[o];o++);Sr<=o&&(F[Sr++]=a)}zn[t]=Sr,Fn[t]=new Int32Array(v[t]),v[t]=0}for(t=A;0<=--t;)b[Fn[e=qr[t]][v[e]++]=t].length<3&&(
b[t]=new Int32Array(3));for(jn=Array(t=C);0<=--t;){for(e=Sr=(r=w[t]).length;0<=--e;)F[e]=65535&r[e],N[e]=r[e]>>>16;jn[t]=Pr(Yn[t],zn[t],Sr,F,N)}Xe||(Or=dt-h+A),function(r){var t,e,n,a,o,l,f,i,h,s,g,u,y,c,A,b,M,d,w,v,m,p,I,k,F,C,E,T,N,q,S,x,R,L,U,V,P,B,X,D=3019169939857233e154,_=sn,G=gn,O=un,Y=ze;for(nn=new Float64Array(3),u=y=c=S=0,I=Number.MAX_VALUE;;){for(q=dt,k=Number.MAX_VALUE,F=0;0<=--q;)(e=tt((A=_[q])-u,(b=G[q])-y,(M=O[q])-c))<k&&(k=e,l=A,f=b,i=M),F<e&&(F=e,h=A,s=b,g=M);if((e=Math.sqrt(F
)-Math.sqrt(k))<I){if(nn[0]=u,nn[1]=y,nn[2]=c,0==(I=e))break;S=0}else if(5<++S)break;0==(e=et(d=h-l,w=s-f,v=g-i))&&(e=et(d*=D,w*=D,v*=D)),u-=(t=u*(d/=e)+y*(w/=e)+c*(v/=e)-.5*((l+h)*d+(f+s)*w+(i+g)*v))*d,y-=t*w,c-=t*v}if(Re=I<r){for(u=Br(nn,0),y=Br(nn,1),c=Br(nn,2),q=dt,C=Number.MAX_VALUE,E=0;0<=--q;)(e=tt(_[q]-u,G[q]-y,O[q]-c))<C&&(C=e),E<e&&(E=e);Math.sqrt(E)-Math.sqrt(C)<r&&(nn[0]=u,nn[1]=y,nn[2]=c,k=C,F=E),Je=Rr(Math.sqrt(F)+Y,Math.sqrt(k)-Y,!1)}for(an=new Float64Array(3),u=y=c=S=0,
I=Number.MAX_VALUE;;){for(q=vt,k=Number.MAX_VALUE,F=0;0<=--q;)U=(e=-(u*(A=(L=rn[q])[0])+y*(b=L[1])+c*(M=L[2])+(t=L[3])))<0&&Be?-1:1,A*=U,b*=U,M*=U,t*=U,(e*=U)<k&&(k=e,l=A,f=b,i=M,m=t),F<e&&(F=e,h=A,s=b,g=M,p=t);if((e=F-k)<I){if(an[0]=u,an[1]=y,an[2]=c,0==(I=e))break;S=0}else if(5<++S)break;if(0==(e=et(d=h-l,w=s-f,v=g-i)))break;u-=(t=u*(d/=e)+y*(w/=e)+c*(v/=e)+(p-m)/e)*d,y-=t*w,c-=t*v}if(Le=I<r){for(u=Br(an,0),y=Br(an,1),c=Br(an,2),q=vt,C=Number.MAX_VALUE,E=0;0<=--q;)(e=-(u*(L=rn[q]
)[0]+y*L[1]+c*L[2]+L[3]))<C&&(C=e),E<e&&(E=e);E-C<r&&(an[0]=u,an[1]=y,an[2]=c,k=C,F=E),Ke=Rr(F+Y,k-Y,!1)}for(V=Sn[0],P=Sn[1],B=mt,on=new Float64Array(3),u=y=c=S=x=0,I=Number.MAX_VALUE;;){for(q=B,C=Number.MAX_VALUE,E=0;0<=--q;)A=_[T=V[q]]-(n=_[N=P[q]]),b=G[T]-(a=G[N]),M=O[T]-(o=O[N]),n+=(e=((u-n)*A+(y-a)*b+(c-o)*M)/tt(A,b,M))*A-u,(e=tt(n,a+=e*b-y,o+=e*M-c))<C&&(C=e),E<e&&(E=e);if((e=Math.sqrt(E)-Math.sqrt(C))<I){if(on[0]=u,on[1]=y,on[2]=c,k=C,F=E,0==(I=e))break;S=0}else if(5<++S)break;for(T=dt,
R=l=f=i=E=0;0<=--T;)for(q=(L=En[T]).length,A=u-(h=_[T]),b=y-(s=G[T]),M=c-(g=O[T]);0<=--q;)for(e=et(n=_[N=V[U=L[q]]+P[U]-T]-h,a=G[N]-s,o=O[N]-g),n*A+a*b+o*M<0&&(n=-n,a=-a,o=-o),U=q,n/=e,a/=e,o/=e;0<=--U;)e=et(d=_[N=V[X=L[U]]+P[X]-T]-h,w=G[N]-s,v=O[N]-g),d*A+w*b+v*M<0&&(d=-d,w=-w,v=-v),0!=(t=et(d=d/e-n,w=w/e-a,v=v/e-o))&&(R++,l+=(e=A*(d/=t)+b*(w/=t)+M*(v/=t))*d,f+=e*w,i+=e*v,(e=Math.abs(e))>E&&(E=e));if(r<E&&1e4<++x)break;u-=l/R,y-=f/R,c-=i/R}if(Ve=!1,Ue=I<r){for(u=Br(on,0),y=Br(on,1),c=Br(on,2),
q=B,l=f=i=0,C=Number.MAX_VALUE,E=0;0<=--q;)A=_[T=V[q]]-(n=_[N=P[q]]),b=G[T]-(a=G[N]),M=O[T]-(o=O[N]),h=(n+=(e=((u-n)*A+(y-a)*b+(c-o)*M)/tt(A,b,M))*A)-u,(e=tt(h,s=(a+=e*b)-y,g=(o+=e*M)-c))<C&&(C=e),E<e&&(E=e),l+=n,f+=a,i+=o;Math.sqrt(E)-Math.sqrt(C)<r&&(on[0]=u,on[1]=y,on[2]=c,k=C,F=E),Ze=Rr(Math.sqrt(F)+Y,Math.sqrt(k)-Y,!1),Ve=tt(l/B-on[0],f/B-on[1],i/B-on[2])<r*r}}(Tr),function(){var r,t,e,n,a,o,l,f,i,h=new Uint8Array(r=(o=new Int8Array(mt)).length<<1),s=new Int32Array(dt<vt?vt:dt);for((
xe=dt==vt&&It==pt)&&(l=new Int32Array((i=new Int32Array((f=new Int32Array(++r)).length)).length)),t=Gr=0,a=!1;!a;){if(xe){for(Dr(t,0,f,i,s,o,h),Hr(i,0,l,0,r),Dr(t,2,f,i,s,o,h),e=r;0<=--e&&l[e]==i[e];);xe=e<0}else Xr(t,!1,-1,0,f,i,s,o,h,!1);for(e=t-1,a=!0,Gr++;++e<o.length;)1==(n=o[e])?o[e]=2:a&&0==n&&(t=e,a=!1)}}(),Vr(b,qr,Tr,s),wr="U",vr="Unknown",mr=ve,pr=me,Ir=pe,kr=Ie,Fr=Se,0==(dr=we)?1==pr&&1==kr&&(1==mr?1!=Ir||Fr||(wr="Cs = C1h = C1v",vr="Reflection"):0==mr&&(1==Ir?Fr&&(wr="Ci = S2",
vr="Inversion"):0!=Ir||Fr||(wr="C1",vr="No Symmetry"))):1==dr?2<=pr&&pr==kr&&(Ir==pr?0==mr?1==(1&pr)==Fr&&(wr="S"+(pr<<1),vr=pr+"-fold Rotoreflection"):1==mr?1==(1&pr)!=Fr&&(wr="C"+pr+"h",vr=pr+"-fold Cyclic + Perpendicular Reflection"):mr!=pr||Fr||(wr="C"+pr+"v",vr=pr+"-fold Pyramidal"):0!=Ir||0!=mr||Fr||(wr="C"+pr,vr=pr+"-fold Cyclic")):dr==pr+1?2<=pr&&pr<<1==kr&&(Ir==kr?mr==dr?1==(1&pr)!=Fr&&(wr="D"+pr+"h",vr=pr+"-fold Prismatic"):mr==pr&&1==(1&pr)==Fr&&(wr="D"+pr+"v",
vr=pr+"-fold Antiprismatic"):0!=Ir||0!=mr||Fr||(wr="D"+pr,vr=pr+"-fold Dihedral")):7==dr?3==pr&&12==kr&&(12==Ir?6==mr?Fr||(wr="Td",vr="Full Tetrahedral"):3==mr&&Fr&&(wr="Th",vr="Pyritohedral"):0!=Ir||0!=mr||Fr||(wr="T",vr="Chiral Tetrahedral")):13==dr?4==pr&&24==kr&&(24==Ir?9==mr&&Fr&&(wr="Oh",vr="Full Octahedral"):0!=Ir||0!=mr||Fr||(wr="O",vr="Chiral Octahedral")):31==dr&&5==pr&&60==kr&&(60==Ir?15==mr&&Fr&&(wr="Ih",vr="Full Icosahedral"):0!=Ir||0!=mr||Fr||(wr="I",vr="Chiral Icosahedral")),Wn=wr
,Qn=vr,hn=yn=rn=null,Cn=En=Sn=null,qe=!0}function nt(r,t){var e;return r=r.substring(1-(e="-"==r.charAt(0)?-1:1)>>1),e*("C"==r.charAt(0)?t[parseInt(r.substring(1),10)]:parseFloat(r))}function at(r){r.preventDefault()}function e(r,t,e){var n,a,o,l,f,i;r?Ce=!0:Fe=!0,o=~~(t-(a=jr.getBoundingClientRect()).left+.5),l=~~(e-a.top+.5),c=0,te<o&&o<=ee&&Zt<l&&l<=$t?(c=1,(Ne^=!0)?(jr.style.cursor="all-scroll",g=o,u=l):jr.style.cursor="default",Tt=Ct,Nt=Et,yt()):Ne?(g=o,u=l):(Lt<o&&o<=Ut&&Vt<l&&l<=Pt?0<=(
c=0<(y=o-(n=_t))&&y<=Yt&&Gt<l&&l<=Ot?-1:1)&&(o<=n?Qt<n&&_t--:n+Yt<o&&n<jt&&_t++):Jt<o&&o<=Kt&&Zt<l&&l<=$t?(c=1,Ee^=!0):Jt<o&&o<=Kt&&ne<l&&l<=ae?(c=1,Te^=!0):Te&&oe<l&&l<=le&&0!=(n=Ln[(l-oe-1)*ct+o])?(c=1)==n?(ke=(ke+de-1)%de,q="lightGray"):2==n?(ke=0,x="lightGray"):3==n?(ke=(ke+1)%de,S="lightGray"):(5==n?(f=0,U="lightGray"):(f=On[ke],i=Gn[ke],4==n?(f=(f+i-1)%i,R="lightGray"):(f=(f+1)%i,L="lightGray")),On[ke]=f):(Ct=o,Et=s=l),0<c&&(Tt=Ct,Nt=Et,ut(),yt()))}function ot(r){r.button&&2!=r.button||e(
r.button,r.clientX,r.clientY)}function lt(r){var t;r.preventDefault(),e(0,(t=r.targetTouches[0]).clientX,t.clientY)}function t(r){r?Ce=!1:Fe=!1,q=S=x=R=L=U="black",yt()}function ft(r){r.button&&2!=r.button||t(r.button)}function it(r){r.preventDefault(),t(0)}function n(r,t){var e,n,a,o,l,f,i,h;Fe|Ce&&(Ne||c<=0)&&(n=~~(r-(e=jr.getBoundingClientRect()).left+.5),Ne?(a=~~(t-e.top+.5),Fe&&((St+=n-g)<-1600&&(St=-1600),xt+=a-u),Ce&&(768<(o=Rt+(a-u))?o=768:o<160&&(o=160),xt=(l=At>>1)-~~((l-xt)*(l=o>>5)/(
f=Rt>>5)),Rt=o,(E=At-~~((At-E)*l/f))>qt&&(E=qt)),g=n,u=a,xt<E&&(xt=E),qt<xt&&(xt=qt)):(Tt=Ct,Nt=Et,c<0?_t=(n-=y)<Qt?Qt:jt<n?jt:n:(a=~~(t-e.top+.5),Fe&&(Ct=n,Et=a),Ce&&.5<=(h=(i=Ge*Math.exp((a-s)*je))*De)&&(Ge=i,Oe=.75/(We<h?.5*(h+We):h)),s=a),ut()),yt())}function ht(r){n(r.clientX,r.clientY)}function st(r){var t;r.preventDefault(),n((t=r.targetTouches[0]).clientX,t.clientY)}function gt(){Fe=Ce=!1,q=S=x=R=L=U="black"}function ut(){var r,t,e,n,a,o,l,f,i,h,s,g,u,y,c,A,b,M,d,w,v,m,p,I,k,F,C,E,T,N,q,
S,x,R,L,U,V,P,B,X,D,_,G,O,Y,z,W,Q,j,H,J,K,Z,$,rr,tr,er,nr,ar,or,lr,fr,ir,hr,sr,gr,ur,yr,cr=1.5707963267948966,Ar=(Tt-bt)*(U=Oe),br=(Mt-Nt)*U,Mr=(Ct-bt)*U,dr=(Mt-Et)*U;for(1<=(P=Math.hypot(Ar,br))?(0!=(U=Math.hypot(Mr,dr))&&(Mr*=U=1-(P-1)/U,dr*=U),t=0):(P=et(Ar,br,t=Math.cos(P*cr)),t/=P),Ar/=P,br/=P,1<(P=Math.hypot(Mr,dr))&&(Mr*=U=(V=P%4)/P,dr*=U,1<V&&(Mr*=U=(V<=3?2-V:V-4)/V,dr*=U)),n=t*(Mr/=P=et(Mr,dr,r=Math.cos(P*cr)))-(r/=P)*Ar,a=Ar*(dr/=P)-Mr*br,l=(e=br*r-dr*t)*(P=.5/(o=Math.sqrt(.5*(
1+Ar*Mr+br*dr+t*r)))),f=n*P,i=a*P,(tr=tn)[0]=h=o*(y=tr[0])-l*(c=tr[1])-f*(A=tr[2])-i*(b=tr[3]),tr[1]=s=o*c+l*y+f*b-i*A,tr[2]=g=o*A-l*b+f*y+i*c,tr[3]=u=o*b+l*A-f*c+i*y,M=h*(U=2*s),v=U*s,m=U*g,p=U*u,d=h*(U=2*g),I=U*g,k=U*u,w=h*(U=2*u),C=1-(I+(F=U*u)),E=m-w,T=p+d,N=m+w,q=1-(v+F),S=k-M,x=p-d,R=k+M,L=1-(v+I),j=(_t-Ht)*Ye,er=cn,nr=An,ar=bn,or=Ge,Z=wt,pr=lr=0,Ir=fr=-1;0<=--Z;)vr(Z,C*(e=Mn[Z])+E*(n=dn[Z])+T*(a=wn[Z]),N*e+q*n+S*a,j*(ar[Z]=(x*e+R*n+L*a)*or),or,er,nr);if(0==++Me)for(Z=dt;0<=--Z;)Un[Z]=0
;for(ir=++Me,Te&&(qe||wr(),fr=Fn[ke][On[ke]]),rr=Ee|Te,hr=Vn,Z=($=!Ee&&Te)?fr+1:vt;0<=--Z;)if(K=1+(J=1+(H=3*Z)),0<(Q=(_=er[J]-(B=er[H]))*(z=nr[K]-(X=nr[H]))-(Y=er[K]-B)*(G=nr[J]-X))||rr){if(Rn[Z]=191.99*Math.abs(Q)/et(G*(W=ar[K]-(D=ar[H]))-z*(O=ar[J]-D),O*Y-W*_,Q),0<Q||$){if(hr[lr++]=Z,$)break;for(gr=(sr=In[Z]).length;0<=--gr;)Un[sr[gr]]=ir}else Pn[pr++]=Z;Z==fr&&(Ir=Q<=0?1:0)}for(ur=ln,yr=fn,Z=dt,V=j*or;0<=--Z;)!rr&&Un[Z]!=ir||(vr(Z,C*(e=sn[Z])+E*(n=gn[Z])+T*(a=un[Z]),N*e+q*n+S*a,V*(x*e+R*n+L*a
),or,ur,yr),qn[0][Z]=~~(We+ur[Z]),qn[1][Z]=~~(Qe-yr[Z]));mr=lr}function vr(r,t,e,n,a,o,l){var f=42535295865117303e21,i=-42535295865117303e21;n=n<1?a/(1-n):Number.POSITIVE_INFINITY,l[r]=0!=e?e*n:0,isFinite(o[r]=0!=t?t*n:0)&&isFinite(l[r])||(Math.abs(t)>=Math.abs(e)?l[r]=(o[r]=0<t?f:i)*(e/t):o[r]=(l[r]=0<e?f:i)*(t/e))}function d(r){na.fillText(r,St,T)}function w(r){d(r),T+=N}function p(r,t,e){for(var n=t,a=1;0<=--n;)r[n]>a&&(a=r[n]);return(4+~~Math.log10(a))*e}function I(r,t){w("Center: ("+(
r[0]+t[0])+", "+(r[1]+t[1])+", "+(r[2]+t[2])+")")}function k(r,t,e,n,a){for(var o=r.length;0<=--o;)t[o]=n[r[o]],e[o]=a[r[o]]}function F(r,t,e){var n;for(na.beginPath(),na.moveTo(r[0],t[0]),n=0;++n<e;)na.lineTo(r[n],t[n]);na.fill()}function C(r,t,e,n,a){var o,l,f,i,h,s;na.beginPath(),na.moveTo(o=r+a,t),na.quadraticCurveTo(r,t,r,i=t+a),na.lineTo(r,s=(h=t+n)-a),na.quadraticCurveTo(r,h,o,h),na.lineTo(f=(l=r+e)-a,h),na.quadraticCurveTo(l,h,l,s),na.lineTo(l,i),na.quadraticCurveTo(l,t,f,t),na.lineTo(o,
t),na.fill()}function yt(){var r,t,e,n,a,o,l,f,i,h,s,g,u,y,c,A,b,M;if(na.fillStyle=Kn,na.fillRect(0,0,ct,At),Ne){if(qe||(jr.style.cursor="wait",wr(),jr.style.cursor="all-scroll"),T=xt+(N=Rt>>5),na.fillStyle="black",na.font=_d[N-5],r=~~(na.measureText("m").width+.5),w("----- EMPIRICALLY GENERATED DATA -----"),T+=N,w("Faces: "+vt+"  Edges: "+mt+"  Vertices: "+dt),T+=N,w("Euler Characteristic:"),w("Rotation Symmetries:"),w("Mirror Rotation Symmetries:"),w("Rotation Axes:"),w("Mirror Planes:"),w(
"Invertible:"),w("Symmetry Classification:"),w("Orientable Surface:"),w("Connected Components:"),w("Topologically Self-Dual:"),w("Canonical:"),T-=11*N,St+=28*r,w(Xe?"(not a closed 2-manifold)":Or),w(Ie),w(pe),t=""+we,0<we){for(t+=" (",e=-2;(e+=2)<6&&0<(n=O[e]);)t+=(0<e?" + ":"")+O[e+1]+"["+n+"]";t+=")"}for(w(t),w(ve),w(Se?"yes":"no"),w(Qn+" ("+Wn+")"),w(Be?"no":Pe?"yes but "+Ft+(1==Ft?" face is reversed":" faces are reversed"):"yes"),w(Gr),w(xe?"yes":"no"),w(Ve?"yes (sphere radius "+Ze+")":"no")
,St-=28*r,T+=N,w("Sphere Touching All Vertices:"),St+=r<<2,Re?(I(nn,en),w("Radius: "+Je)):w("None"),St-=r<<2,w("Sphere Tangent to (and below) All Face Planes:"),St+=r<<2,Le?(I(an,en),w("Radius: "+Ke)):w("None"),St-=r<<2,w("Sphere Tangent to All Edges:"),St+=r<<2,Ue?(I(on,en),w("Radius: "+Ze)):w("None"),St-=r<<2,T+=N,w("Volume = "+He+(Pe?" (unoriented)":"")),T+=N,w("Edge Dihedral Angles:"),a=p(Xn,zr,r),e=-1;++e<zr;)d("("+Xn[e]+")"),St+=a,w("D"+(e+1)+" = "+mn[e]+" degrees"),St-=a;for(T+=N,w(
"Edge Lengths:"),a=p(Bn,Yr,r),e=-1;++e<Yr;)d("("+Bn[e]+")"),St+=a,w("E"+(e+1)+" = "+vn[e]),St-=a;for(T+=N,w("Face Vertex Angles:"),a=p(Dn,Wr,r),e=-1;++e<Wr;)d("("+Dn[e]+")"),St+=a,w("A"+(e+1)+" = "+pn[e]+" degrees"),St-=a;for(T+=N,w("Face Types:"),a=p(Gn,de,r),e=0;e<de;e++){for(o=kn[e],d("("+Gn[e]+")"),St+=a,w("F"+(e+1)+" = "+jn[e]),n=-1,t="sides: {";++n<o.length;)t+=" E"+(1+(o[n]>>>16));for(n=-1,t+=" } angles: {";++n<o.length;)t+=" A"+(1+(65535&o[n]));w(t+=" }"),St-=a}for(T+=N,w(
"Center of Mass:"),w("("+en[0]+", "+en[1]+", "+en[2]+")"),T+=N,w("Principal Moments and Axes of Inertia:"),e=0;e<3;e++)w("MOMENT: "+(l=$e[e])[3]),w("AXIS: ("+l[0]+", "+l[1]+", "+l[2]+")");(E=At+xt-T)>qt&&(E=qt),na.fillRect(te,Zt,re,re),na.font=ta}else{for(f=Tn[0],i=Tn[1],h=qn[0],s=qn[1],g=Ee?Jn:Hn,u=Ee&Te,y=Ee?2:1;0<=--y;)for(c=0!=y?pr:mr,A=0!=y?Pn:Vn,b=Ee?0!=y?ra:$n:Zn,Ir==y&&(k(o=In[e=Fn[ke][On[ke]]],f,i,h,s),na.fillStyle=Hn[e][255&Rn[e]],F(f,i,o.length)),n=0;n<c;n++)k(o=In[e=A[n]],f,i,h,s),
u||(na.fillStyle=g[e][255&Rn[e]],F(f,i,o.length)),na.strokeStyle=b,function(r,t,e){var n;for(na.beginPath(),na.moveTo(r[0],t[0]),n=0;++n<e;)na.lineTo(r[n],t[n]);na.closePath(),na.stroke()}(f,i,o.length);na.fillStyle="lightGray",C(Lt,e=Vt,Bt,Xt,n=Wt),na.strokeStyle=Kn,na.beginPath(),na.moveTo(Dt,e),na.lineTo(Dt,Pt),na.closePath(),na.stroke(),na.fillStyle="#505050",C(_t,Gt,Yt,zt,n),Ee||(na.fillStyle=_b[4][64],na.fillRect(Jt,Zt,re,re)),na.strokeStyle=na.fillStyle="black",na.strokeRect(Jt,Zt,re,re),
0<(e=kt)&&(na.font=~~(ct/20)+"px Courier New",na.fillText("WARNING: "+e+(1==e?" face is non-planar":" faces are non-planar"),0,63*At>>6)),na.strokeRect(te,Zt,re,re),Te?(na.fillRect(Jt,ne,re,re),na.font=ea,M=jn[ke],na.fillText(M,ct-Ae*M.length>>1,le-be),na.fillText(e=ke+1,se-(Ae*~~Math.log10(e)>>1),le-be),na.fillText(e=On[ke]+1,ge-(Ae*~~Math.log10(e)>>1),le-be),na.fillText("face type",se-(9*Ae>>1),oe-be),na.fillText("occurrence",ge-(9*Ae>>1),oe-be),na.strokeStyle=x,na.strokeRect(fe,oe,he,ue),
na.fillStyle=q,F(Nn[0],Nn[1],3),na.fillStyle=S,F(Nn[2],Nn[3],3),na.strokeStyle=U,na.strokeRect(ie,oe,he,ue),na.fillStyle=R,F(Nn[4],Nn[5],3),na.fillStyle=L,F(Nn[6],Nn[7],3),na.fillStyle="lightGray"):na.strokeRect(Jt,ne,re,re),na.font=ta,na.fillText("F",Jt+ye,ae-ce)}na.fillStyle=Ne?"lightGray":"black",na.fillText("M",te+ye,$t-ce)}var ct,At,bt,Mt,dt,wt,vt,mt,pt,It,Gr,Or,kt,Ft,s,Ct,Et,Tt,Nt,qt,E,St,xt,T,g,u,Rt,N,Lt,Ut,Vt,Pt,Bt,Xt,Dt,_t,Gt,Ot,Yt,zt,Wt,Qt,jt,Ht,y,Jt,Kt,Zt,$t,re,te,ee,ne,ae,oe,le,fe,ie
,he,se,ge,ue,ye,ce,Ae,be,mr,pr,Ir,Me,Yr,zr,Wr,de,we,ve,me,pe,Ie,ke,c,Fe,Ce,Ee,Te,Ne,qe,Se,xe,Re,Le,Ue,Ve,Pe,Be,Xe,De,Ge,Oe,Ye,ze,We,Qe,je,He,Je,Ke,Ze,$e,rn,tn,en,nn,an,on,ln,fn,hn,sn,gn,un,yn,cn,An,bn,Mn,dn,wn,vn,mn,pn,In,kn,Fn,Cn,En,Tn,Nn,qn,Sn,xn,Rn,Ln,O,Un,Vn,Pn,Bn,Xn,Dn,Gn,On,Yn,zn,Wn,Qn,jn,Hn,Jn,Kn,Zn,$n,ra,q,S,x,R,L,U,ta,ea,na;_g[_g.length]=(na=jr.getContext("2d"),void function(){var r,t,e,n,a,o,l,f,i,h,s,g,u,y,c,A,b,M,d,w,v,m,p,I,k,F,C,E,T,N,q,S,x,R,L,U,V,P,B,X,D,_,G,O,Y,z,W,Q,j,H,J,K,Z,$
,rr,tr,er,nr,ar,or,lr,fr,ir,hr,sr,gr,ur,yr,cr,Ar,br,Mr,dr,wr,vr,mr,pr,Ir,kr,Fr,Cr,Er,Tr,Nr,qr,Sr,xr,Rr,Lr,Ur,Vr,Pr,Br,Xr,Dr,Gr,Or=5820766091346741e-26,Yr=2.3283064365386963e-10,zr=5.960464477539063e-8,Wr=3019169939857233e154;for(Ct=Tt=bt=(Y=ct=jr.width)>>1,Et=Nt=Mt=(z=At=jr.height)>>1,Kn=(W=Qr.getElementsByClassName("Background")).length?W[0].value:"#606060",Zn=(W=Qr.getElementsByClassName("EdgeColor")).length?W[0].value:"black",$n=(W=Qr.getElementsByClassName("WireColor")
).length?W[0].value:"black",na.fillStyle=Kn,na.fillRect(0,0,Y,z),Ot=(Pt=(Vt=E=z>>6)+(Xt=T=z<256?8:z>>5))-1,Gt=E+1,Wt=T>>1,_t=(Ht=N=(3*(k=(jt=(Ut=(Lt=Y>>2)+(Bt=Y>>1))-(Yt=zt=T-2)-1)-(Qt=Lt+1))>>2)+Qt)+(k>>4),Dt=N+(Yt>>1),Ye=(je=.5/(We=Y>>1))/(p=3*(jt-N)>>3),(W=Qr.getElementsByClassName("Perspective")).length&&((_t=N+~~(parseFloat(W[0].value)*p))>jt&&(_t=jt),_t<Qt&&(_t=Qt)),Kt=(Jt=St=Y>>6)+(re=R=T<<1),$t=xt=qt=(Zt=E)+R,te=(ee=Y-Jt)-R,na.font=ta=R+"px Verdana",ye=ce=R-~~(na.measureText("M"
).width+.5)+1>>1,Rt=384,na.font=ea=~~((R<<1)/5)+"px Courier New",be=T-(Ae=N=~~(na.measureText("M").width+.5))>>1,Nn=Array(L=8);0<=--L;)Nn[L]=new Uint32Array(3);for((j=Nn[2])[0]=(j[1]=j[2]=(fe=((Q=Nn[0])[1]=Q[2]=(Q[0]=Kt+(ue=T))+T)+2)+(he=6*N)+2)+T,(H=Nn[4])[0]=(H[1]=H[2]=(ie=((J=Nn[6])[1]=J[2]=(J[0]=te-T)-T)-2-he)-2)-T,oe=(K=Nn[1])[2]=(Z=Nn[3])[1]=($=Nn[5])[2]=(X=Nn[7])[1]=(ae=le=K[1]=Z[2]=$[1]=X[2]=z-E)-T,ne=ae-R,se=fe+(L=he-N>>1),ge=ie+L,K[0]=$[0]=K[1]+K[2]>>1,Z[0]=X[0]=Z[1]+Z[2]>>1,
Ln=new Int8Array(L=T*Y);0<=(L-=Y);){for(E=L+Q[1],N=L+Q[0];--E>=N;)Ln[E]=1;for(E=L+fe+he,N=L+fe;--E>=N;)Ln[E]=2;for(E=L+j[0],N=L+j[1];--E>=N;)Ln[E]=3;for(E=L+H[1],N=L+H[0];--E>=N;)Ln[E]=4;for(E=L+ie+he,N=L+ie;--E>=N;)Ln[E]=5;for(E=L+J[0],N=L+J[1];--E>=N;)Ln[E]=6}if((rr=tn=new Float64Array(4))[0]=1,(W=Qr.getElementsByClassName("Quaternion")).length){for(t=W[0].value.match(/[^ \t\n\r\f,;]+/g),E=-1,p=0;++E<4;)p+=(rr[E]=parseFloat(t[E]))*rr[E];for(0==p&&(rr[0]=p=1,rr[1]=rr[2]=rr[3]=0),E=4,
p=Math.sqrt(p);0<=--E;)rr[E]/=p}for(t=Qr.getElementsByClassName("Counts")[0].value.match(/[^ \t\n\r\f,;]+/g),I=parseInt(t[0],10),Un=new Int32Array((fr=un=new Float64Array((lr=gn=new Float64Array((or=sn=new Float64Array((ar=hn=new Float64Array((nr=fn=new Float64Array((er=ln=new Float64Array(tr=dt=parseInt(t[1],10))).length)).length)).length)).length)).length)).length),qn=Array(E=2);0<=--E;)qn[E]=new Int32Array(Un.length);for(wn=new Float64Array((dn=new Float64Array((Mn=new Float64Array((
bn=new Float64Array((An=new Float64Array((cn=new Float64Array(3*(Jn=Array((Hn=Array((rn=Array((Rn=new Int8Array((Pn=new Int32Array((Vn=new Int32Array((hr=In=Array(ir=vt=parseInt(t[2],10))).length)).length)).length)).length)).length)).length)).length)).length)).length)).length)).length)).length),E=Rn.length;0<=--E;)rn[E]=new Float64Array(4);for($e=Array(E=3);0<=--E;)$e[E]=new Float64Array(4);if(xn=new Uint8Array(ir),sr=new Int32Array(tr),gr=new Float64Array(I),0<I)for(t=Qr.getElementsByClassName(
"Constants")[0].value.match(/[^ \t\n\r\f,;]+/g),E=-1;++E<I;)gr[E]=parseFloat(t[E]);for(yn=new Float64Array(tr),t=Qr.getElementsByClassName("Vertices")[0].value.match(/[^ \t\n\r\f,;]+/g),ur=0,V=E=-1;++V<tr;)(p=tt(or[V]=nt(t[++E],gr),lr[V]=nt(t[++E],gr),fr[V]=nt(t[++E],gr)))>ur&&(ur=p);for(ur=Math.sqrt(ur),ze=ur*Or,gr=null,yr=Cn=Array(ir),cr=En=Array(tr),M=$r(or,tr),d=$r(lr,tr),w=$r(fr,tr),V=-1;++V<tr;)er[V]=or[V]-=M,nr[V]=lr[V]-=d,ar[V]=fr[V]-=w;for(_=new Int32Array(ir),
t=Qr.getElementsByClassName("Faces")[0].value.match(/[^ \t\n\r\f,;]+/g),D=new Int32Array(F=0),br=Ar=0,E=V=-1;++E<ir;){for(N=0;"#"!=(r=t[++V]).charAt(0);)sr[Un[N++]=parseInt(r,10)]++;if(br+=N,yr[E]=new Int32Array(N),Hr(Un,0,hr[E]=new Int32Array(N),0,N),Ar<N&&(Ar=N),1<r.length){for(T=16777215&parseInt(r.substring(1),16),x=F;0<=--x&&D[x]!=T;);x<0&&(Hr(D,0,Mr=new Int32Array(D.length+32),0,D.length),(D=Mr)[x=F++]=T),_[E]=x}else Hn[E]=_b[31&N],Jn[E]=_c[31&N]}for(E=tr;0<=--E;)Un[E]=0;for(Sn=Array(E=4
);0<=--E;)Sn[E]=new Int32Array(br);for(dr=Array(E=tr),It=0;0<=--E;)for(dr[E]=new Int32Array(T=sr[E]),It<T&&(It=T),cr[E]=X=new Int32Array(T<<=1);0<=--T;)X[T]=-1;for(E=ir;0<=--E;)for(T=(X=hr[E]).length;0<=--T;)dr[N=X[T]][--sr[N]]=T<<18|E;for(E=tr,Pe=Xe=!1;0<=--E;)if(0<(X=dr[E]).length)for(vr=(wr=hr[262143&(N=X[L=0])]).length-1,N>>>=18;L<X.length-1;){for(U=wr[(N+vr)%wr.length],T=++L;T<X.length;T++)if(x=(wr=hr[262143&(N=X[T])]).length-1,(mr=wr[((N>>>=18)+1)%wr.length]==U)||wr[(N+x)%wr.length]==U){(
mr?1==vr:1<vr)&&(Pe=!0),vr=mr?x:1;break}T>=X.length?(Xe=!0,vr=(wr=hr[262143&(N=X[L])]).length-1,N>>>=18):T!=L&&(R=X[L],X[L]=X[T],X[T]=R)}for(E=ir,pr=Sn[br=0],Ir=Sn[1],kr=Sn[2],Fr=Sn[3];0<=--E;)for(T=(X=hr[E]).length,Er=X[0],Cr=yr[E];0<=--T;){for(x=Er+(Tr=X[T])-(q=Er<Tr?Er:Tr),N=0,wr=cr[Er];0<=(L=wr[N])&&(pr[L]!=q||Ir[L]!=x);N++);L<0?(pr[wr[sr[Er]++]=cr[Tr][sr[Tr]++]=L=br++]=q,Ir[L]=x,kr[L]=Fr[L]=E):(Fr[L]!=kr[L]&&(Xe=!0),kr[L]+=E-(Fr[L]=E<(N=kr[L])?N:E)),Cr[T]=L,Er=Tr}for(E=tr;0<=--E;)if(
cr[E]=wr=Jr(cr[E],sr[E]),0<(X=dr[E]).length)if(1==X.length)Xe=!0;else for(T=1,Nr=262143&X[S=0];;){for(x=Nr+(qr=262143&X[T])-(q=Nr<qr?Nr:qr),N=S;N<wr.length&&(kr[L=wr[N]]!=q||Fr[L]!=x);N++);if(N<wr.length?(wr[N]=wr[S],wr[S++]=L):Xe=!0,S>=wr.length||1==(T=(T+1)%X.length))break;Nr=qr}if(dr=null,!(Be=Xe)&&Pe){r:for(Rr=new Uint8Array((xr=new Uint8Array((Sr=new Int32Array(E=ir)).length)).length),C=0;0<=--E;)if(!xr[E])for(xr[Sr[N=0]=E]=!0,T=1;N<T;N++)for(q=(wr=yr[S=Sr[N]]).length,X=hr[S],
Lr=Rr[S];0<=--q;){for(R=(Ur=yr[x=kr[L=wr[q]]+Fr[L]-S]).length,Cr=hr[x];0<=--R&&Ur[R]!=L;);if(Vr=Lr!=(X[q]==Cr[R]),xr[x]){if(Rr[x]!=Vr){Be=!0;break r}}else xr[Sr[T++]=x]=!0,(Rr[x]=Vr)&&C++}Be||(Ft=C<(E=ir-C)?C:E)}for(ra=Be?$n:"#888888",Sn[0]=Jr(pr,br),Sn[1]=Jr(Ir,br),Sn[2]=Jr(kr,br),Sn[3]=Jr(Fr,mt=br),T=1,c=A=b=i=h=s=0,o=Number.MAX_VALUE,Pr=new Float64Array(3);!(Pe|Xe);){if(Zr(Pr,null),(p=tt(Pr[0],Pr[1],Pr[2]))<o){if(i=c,h=A,s=b,0==(o=p))break;T=1}else if(i+=c,h+=A,s+=b,4<=++T){i*=.25,h*=.25,
s*=.25;break}for(V=-1,c+=Pr[0],A+=Pr[1],b+=Pr[2];++V<tr;)er[V]=or[V]-c,nr[V]=lr[V]-A,ar[V]=fr[V]-b}for(Math.abs(i)<rt(or,tr)*Or&&(i=0),Math.abs(h)<rt(lr,tr)*Or&&(h=0),Math.abs(s)<rt(fr,tr)*Or&&(s=0),V=-1,ur=0,(en=new Float64Array(3))[0]=M+i,en[1]=d+h,en[2]=w+s;++V<tr;)(yn[V]=p=et(er[V]=or[V]-=i,nr[V]=lr[V]-=h,ar[V]=fr[V]-=s))>ur&&(ur=p);if(Ge=We*((W=Qr.getElementsByClassName("Scale")).length?.75*parseFloat(W[0].value):.75)/ur,Oe=1/We,We+=.5,Qe=.5+(z>>1),ze=(De=ur)*Or,He=Zr(Pr,$e),G=O=Pr=null,
0!=F)for(O=Array((G=Array(E=F)).length);0<=--E;)for(O[E]=Array(192),G[E]=Array(192),T=192,wr=G[E],Cr=O[E],Xr=(Br=D[E])>>8&255,Dr=255&Br,Br>>=16;0<=--T;)wr[T]="rgb("+~~((Br*(N=T+64)+127)/255)+","+~~((Xr*N+127)/255)+","+~~((Dr*N+127)/255)+")",Cr[T]="rgba"+wr[T].slice(3,-1)+",.125)";for(B=new Float64Array((P=new Float64Array(pt=Ar)).length),Tn=Array(E=2);0<=--E;)Tn[E]=new Int32Array(B.length);for(E=wt=kt=0,D=null;E<ir;E++){for(null==Hn[E]&&(Hn[E]=G[N=_[E]],Jn[E]=O[N]),T=(X=hr[E]).length,c=A=b=0,
o=or[V=X[1]],l=lr[V],f=fr[V],i=or[V=X[0]],h=lr[V],s=fr[V];c+=h*(f-(y=fr[V=X[--T]])),A+=s*(o-(g=or[V])),b+=i*(l-(u=lr[V])),!(T<=0);)o=i,l=h,f=s,i=g,h=u,s=y;for(0==(p=et(c,A,b))&&0==(p=et(c*=Wr,A*=Wr,b*=Wr))&&(p=b=1),i=Math.abs((Cr=rn[E])[0]=c/=p),h=Math.abs(Cr[1]=A/=p),s=Math.abs(Cr[2]=b/=p),Cr[3]=-(o*c+l*A+f*b),i=(1-(s=-c)*s/(p=1+b*(Gr=b<0?-1:1)))*Gr,u=1-(y=-A*Gr)*y/p,g=(h=c*y/p)*Gr,T=X.length,o=or[V=X[0]],l=lr[V],f=fr[V];0<=--T;)P[T]=er[V=X[T]]=i*(e=or[V]-o)+h*(n=lr[V]-l)+s*(a=fr[V]-f),
B[T]=nr[V]=g*e+u*n+y*a;if(Kr(e=o+i*(v=function(r,t,e,n,a,o){var l,f,i,h,s,g,u,y,c,A,b,M,d,w;r:for(l=e;;)for(d=.5*((f=r[n])+r[a]),w=.5*((i=t[n])+t[a]),s=o,h=(f-=d)*f+(i-=w)*i;;){for(;s<e;s++)if((f=r[s]-d)*f+(i=t[s]-w)*i>h){if(0!=o){a=n,e=n=s,o--;continue r}d=(d=r[n])+(b=((u=t[s]-(w=t[n]))*(y=(f=r[a]-d)*f+(i=t[a]-w)*i)-i*(c=(g=r[s]-d)*g+u*u))*(A=.5/(f*u-i*g))),w+=M=(f*c-g*y)*A,h=b*b+M*M}if(2==o)return t[0]=w,d;s=e+1,e=0==o?a:l,n=a,a=o++}}(P,B,X.length,0,1,2))+g*(m=B[0]),n=l+h*v+u*m,a=f+s*v+y*m),
Kr(e+(p=ur*zr)*i,n+p*h,a+p*s),Kr(e+p*g,n+p*u,a+p*y),2<(T=X.length-1))r:for(;0<=(N=T--);)for(o=or[V=X[N]],l=lr[V],f=fr[V];0<=--N;)if(Math.abs((c*(or[V=X[N]]-o)+A*(lr[V]-l)+b*(fr[V]-f))/yn[V])>Yr){kt++;break r}}P=B=G=O=_=null,Fe=Ce=Ee=Te=Ne=qe=!1,jr.addEventListener("contextmenu",at,!1),jr.addEventListener("mousedown",ot,!1),jr.addEventListener("touchstart",lt,!1),document.addEventListener("mouseup",ft,!1),document.addEventListener("touchend",it,!1),document.addEventListener("mousemove",ht,!1),
document.addEventListener("touchmove",st,!1),document.addEventListener("mouseleave",gt,!1),Me=ke=0,ut(),yt()}())}window.addEventListener("load",_h,!1),_f=["pentagon","hexagon","heptagon","octagon","enneagon","decagon","hendecagon","dodecagon","tridecagon","tetradecagon","pentadecagon","hexadecagon","ditrigon","triambus","ditetragon","tetrambus","dipentagon","pentambus","dihexagon","hexambus","diheptagon","heptambus","dioctagon","octambus"],_e=["","bi-","tri-"];
