"use strict";var _a,_b,_c,_q,_e,_d,_p;function _r(){var r,e,t,n,a,l,f,o,h=[131072,512,2,131584,131330,514,131328,65794,513,66048,256,1,257,258,65536,65537,65538,65792,131329,66049,66050,131073,131074,131585];if(null==_b){for(_c=Array(32),l=_b=Array(32),e=32;0<=--e;)_c[e]=Array(192),l[e]=Array(192);for(r=192;0<=--r;){for(a=r+64,e=24;0<=--e;)t=h[e],l[e][r]="rgb("+((t=t*(a>>1)+(t>>1&65793)*(1&a))>>16)+","+(t>>8&255)+","+(255&t)+")";for(e=9;0<--e;)l[e+23][r]="rgb("+(t=a*e>>3)+","+t+","+t+")";for(
e=32;0<=--e;)_c[e][r]="rgba"+l[e][r].slice(3,-1)+",.125)"}}if(null==_a)for(r=1,e=0,_a=new Uint32Array(627);r<8192;r++){for(a=r;0==(1&a);a>>=1);for(;a%5==0;a/=5);for(n=1;(n*=10)<=1e6&&n%a!=1;);(1==a||n<=1e6)&&(_a[e++]=r)}if(null==_d)for(_d=Array(r=20);0<=--r;)_d[r]=r+5+"px Courier New";for(f=document.getElementsByTagName("div"),_p=[],r=-1;++r<f.length;)"viewer"==f[r].getAttribute("name")&&(o=f[r].getElementsByTagName("canvas")).length&&_s(f[r],o[0])}function _s(Jn,Kn){function Zn(r,e,t,n,a,l,f,o,
h,i,g){for(var y,A,u,s,w,c=r.length;0<=--c;)(y=e[(w=r[c])>>7])[384+(w&=127)]=l*(A=y[w]-t)+f*(u=y[128+w]-n)+o*(s=y[256+w]-a),y[512+w]=h*A+i*u+g*s}function f(r,e,t){r-hf<e[t]&&(e[t]=r-hf),r+hf>e[++t]&&(e[t]=r+hf)}function $n(r,e,t){var n,a,l=r.length;for(t[1]=t[3]=t[5]=-(t[0]=t[2]=t[4]=Number.MAX_VALUE);0<=--l;)f((n=e[(a=r[l])>>7])[a&=127],t,0),f(n[128+a],t,2),f(n[256+a],t,4)}function a(r,e,t){for(var n,a=r[e];(n=2*e+1)<t&&(n<t-1&&r[n]<r[n+1]&&n++,!(a>=r[n]));r[e]=r[n],e=n);r[e]=a}function y(r,e){
for(var t,n=(e>>1)-1;0<=n;n--)a(r,n,e);for(n=e-1;0<n;n--)t=r[n],r[n]=r[0],r[0]=t,a(r,0,n)}function ra(r,e,t,n){var a,l,f,o,h,i,g;for(y(r,t),y(e,n),a=l=f=o=h=0;;)if((i=r[f])<(g=e[o])){if(2==(h^=1)&&(l+=i-a),a=i,++f>=t)return l}else if(1==(h^=2)&&(l+=g-a),a=g,++o>=n)return l}function ea(r,e,t,n,a,l,f,o,h,i,g,y){for(var A,u,s,w,c,b,M,I,v,d,k,m,p,F,E,T,C,N,S,q,U,L,x,R,V,X,_,P,B,D,G,O,Y,z,W,Q,j=3019169939857233e154,H=i.length;0<=--H;)i[H]=0;for(B=Array(H=r),F=l[0],E=l[1],T=l[2];0<=--H;)for(
B[H]=G=new Int32Array(S=(D=t[H>>9][511&H]).length),w=(C=n[(_=D[0])>>7])[q=127&_],c=C[q+128],b=C[q+256];0<=--S;_=X,w=M,c=I,b=v){0==(p=pa(A=w-(M=(C=n[(X=D[S])>>7])[q=127&X]),u=c-(I=C[q+128]),s=b-(v=C[q+256])))&&0==(p=pa(A*=j,u*=j,s*=j))||(A/=p=s<0?-p:p,u/=p,s/=p),(G[S]=V=ba(A,u,s,M,I,v,a,l,f,o,e))==e&&e++,m=T[V];r:for(N=X,L=_,O=h[V],p=0==(Y=(d=Math.abs(F[V]))>(k=Math.abs(E[V]))?m<d?0:256:m<k?128:256)?M:128==Y?I:v,z=0==Y?w:128==Y?c:b;0<=N;N=L,L=-1,p=z){for(W=0,U=q=i[V];(R=W+U>>1)<U;){if((x=O[R])==N
)continue r;p<n[x>>7][(127&x)+Y]?U=R:W=R+1}i[V]++==(Q=O).length&&ha(O,0,h[V]=O=new Int32Array(O.length+4),0,R),ha(Q,R,O,R+1,q-R),O[R]=N}}for(H=r,P=new Int32Array(11);0<=--H;){for(S=U=0,D=t[H>>9][511&H],G=B[H];S<D.length;){for(q=i[V=G[S]],O=h[V],X=D[S],_=D[++S%D.length],N=-1;(V=O[--q])!=X;)V==_&&(N=1);for(;(X=O[q])!=_;q+=N)P=ga(P,U++,X,8),null!=y&&y[X]++}if(null!=(D=null==g?U==D.length?null:t[H>>9][511&H]=new Int32Array(U):g[H]=new Int32Array(3*U))&&ha(P,0,D,0,U),null!=g)for(S=U<<1;--S>=U;
)D[S]=-1}return e}function ta(r,e,t,n,a,l,f,o,h){var i,g,y,A,u,s,w,c,b=5820766091346741e-26;return Math.hypot(r-t,e-n)<=hf?Math.abs((u=(i=h[(w=o[(l+2)%o.length])>>7])[384+(w&=127)]-(y=(g=h[(c=f[(a+f.length-1)%f.length])>>7])[384+(c&=127)]))*((A=g[512+c])-.5*(e+n))-(s=i[512+w]-A)*(y-.5*(r+t)))<(u*u+s*s)*b?2:1:0}function na(r,e,t,n,a,l){var f,o,h,i,g,y,A,u=5820766091346741e-26;return(A=Math.hypot(f=r-t,o=e-n))<=hf?0:Math.hypot(h=a-r,i=l-e)<=hf?1:Math.abs(f*(y=l-n)-o*(g=a-t))<(f*g+o*y)*u&&Math.abs(
h*y-i*g)<(h*g+i*y)*u?A/Math.hypot(g,y):-1}function aa(r,e,t,n,a){var l,f;return(r[n]-(l=r[t]))*(e[a]-(f=e[t]))-(r[a]-l)*(e[n]-f)}function la(r,e,t,n,a,l){for(var f,o,h=0,i=r[t],g=e[t];--n>=t;)f=r[n],o=e[n],g<=l?l<o&&(a-i)*(o-g)<(f-i)*(l-g)&&h++:o<=l&&(f-i)*(l-g)<(a-i)*(o-g)&&h--,i=f,g=o;return h}function fa(r,e,t,n,a,l,f){var o,h,i;if(l!=n&&l!=a){for(o=h=r[n]-1;0<=o&&t[o]>f;o--);if((o<0||e[o]!=l)&&(o==h||e[o+1]!=l)){for(o++,i=r[n]++;(h=i)>o;)e[h]=e[i=h-1],t[h]=t[i];e[o]=l,t[o]=f}}}function oa(r,
e,t,n,a){var l,f=n+a;if((l=e-n)<0)for(;--f>=n;)t[f]=r[f+l];else for(;n<f;n++)t[n]=r[n+l]}function ha(r,e,t,n,a){var l,f=n+a;if((l=e-n)<0)for(;--f>=n;)t[f]=r[f+l];else for(;n<f;n++)t[n]=r[n+l]}function ia(r,e,t,n,a){var l,f=n+a;if((l=e-n)<0)for(;--f>=n;)t[f]=r[f+l];else for(;n<f;n++)t[n]=r[n+l]}function ga(r,e,t,n){var a;return e>=r.length&&(ha(r,0,a=new Int32Array(r.length+n),0,r.length),r=a),r[e]=t,r}function ya(r,e){return r[r.length]=e,r}function Aa(r,e){return r.length!=e&&ha(r,0,
r=new Int32Array(e),0,e),r}function ua(r,e,t){for(var n,a,l,f,o=r.length,h=e[0],i=e[1],g=e[2],y=e[3],A=0;0<=--o;)if((l=Math.abs(a=(n=t[(f=r[o])>>7])[f&=127]*h+n[f+128]*i+n[f+256]*g+y))>hf){if(A==(f=3+l/a>>1))return 3;A=3-f}return A}function W(r,e,t){for(var n,a=n=r.length-1;0<=a&&r[a]!=e;a--);return 0<=a&&(r[(a+1)%r.length]==t||r[(a+n)%r.length]==t)?-1:-2}function sa(r,e,t,n,a,l,f){for(var o,h,i,g,y,A,u,s,w,c,b,M,I,v,d,k,m,p,F,E,T,C,N,S,q,U,L,x,R,V,X=0,_=a[0],P=a[1],B=a[2],D=l[0],G=l[1],O=l[2],
Y=l[3],z=-1;++z<t.length;)if(Math.abs(m=(y=(o=f[(U=t[z])>>7])[R=127&U])*D+(A=o[R+128])*G+(u=o[R+256])*O+Y)>hf){X=m/Math.abs(m);break}if(0==X)return 0;for(V=z+++t.length,F=N=S=x=0;;z++){if(p=(s=(o=f[(L=t[z%t.length])>>7])[R=127&L])*D+(w=o[R+128])*G+(c=o[R+256])*O+Y,T=Math.abs(p)>hf?p/Math.abs(p):0,0==F)0==T?F=1:T!=X&&(m/=m-p,r[N++]=e<0?y+m*(s-y):0==e?A+m*(w-A):u+m*(c-u),S=2147483648);else if(1==F)0==T?((x=W(n,U,L))==(2==(F=((M=A-i)*(k=c-u)-(d=w-A)*(I=u-g))*_+(I*(v=s-y)-k*(b=y-h))*P+(b*d-v*M
)*B<0?3:2)?-2:-1)&&(r[N++]=e<0?y:0==e?A:u),C=E):(T!=E&&(r[N++]=e<0?y:0==e?A:u,S=2147483648),F=0);else{if(0==T){x=U,U=L,y=s,A=w,u=c;continue}0<=x&&(x=W(n,x,U)),S|=(q=T==C?0:1)<<31,0==(x+F+q&1)&&(r[N++]=e<0?y:0==e?A:u),F=0}if(V<=z)return S|N;h=y,i=A,g=u,E=X,U=L,y=s,A=w,u=c,m=p,X=T}}function wa(r,e,t,n,a,l,f,o,h,i,g,y,A){for(var u,s,w,c,b,M,I,v,d,k,m,p,F,E,T,C,N,S,q,U,L,x,R,V,X,_,P,B,D,G,O,Y,z,W,Q,j,H,J,K,Z,$,rr,er,tr,nr,ar,lr,fr,or,hr,ir,gr,yr,Ar,ur,sr,wr,cr,br=t[or=r>>9][hr=511&r],Mr=(
wr=wf[to[cr=(Ar=a[0])[or][hr]]])[0]*(Cr=n[or][hr]),Ir=wr[1]*Cr,vr=wr[2]*Cr,dr=e[0],kr=e[1],mr=e[2],pr=e[3],Fr=f[0],Er=f[1],Tr=f[2],Cr=0;;Cr++)if(Math.abs(Y=(b=(u=A[(rr=br[Cr])>>7])[lr=127&rr])*dr+(M=u[lr+128])*kr+(I=u[lr+256])*mr+pr)>hf){J=Y/Math.abs(Y);break}for(ir=Cr+++br.length,W=!1,gr=yr=l[$=j=ar=0];;Cr++){if(z=(v=(u=A[(er=br[Cr%br.length])>>7])[lr=127&er])*dr+(d=u[lr+128])*kr+(k=u[lr+256])*mr+pr,0==(K=Math.abs(z)>hf?z/Math.abs(z):0)&&(nr=er),0==j)0==K||K==J?(gr[ar++]=er,j=1-K*K):(
gr[ar++]=nr=tr=ca(A,m=E=b+(Y/=Y-z)*(R=v-b),p=T=M+Y*(V=d-M),F=C=I+Y*(X=k-I),o,h,i,g,y),Z=J,W=!0);else if(1==j)0!=K&&K!=H?(tr=rr,m=E=b,p=T=M,F=C=I,Z=H,W=!0,j=0):(Q=((V=M-w)*(B=k-I)-(P=d-M)*(X=I-c))*Mr+(X*(_=v-b)-B*(R=b-s))*Ir+(R*P-_*V)*vr<0,0==K?(j=Q?3:2,Z=H):(Q?(tr=rr,m=E=b,p=T=M,F=C=I,Z=H,W=!0):gr[ar++]=er,j=0));else{if(0==K){rr=er,b=v,M=d,I=k;continue}3==j||K!=Z?(tr=rr,m=s,p=w,F=c,E=b,T=M,C=I,W=!0):(gr[ar++]=rr,gr[ar++]=er),j=0}if(W&&(0==$?(U=m,L=p,x=F):(_=m-N,P=p-S,B=F-q,Tr[$]=0<(G*B-P*O)*Mr+(
O*_-B*D)*Ir+(D*P-_*G)*vr?1:0,Er[$]=Z),Fr[$]=ar,(gr=l[++$])[0]=tr,gr[1]=er,D=v-(N=E),G=d-(S=T),O=k-(q=C),W=!(ar=2)),ir<=Cr)break;s=b,w=M,c=I,H=J,rr=er,b=v,M=d,I=k,Y=z,J=K}if(_=U-N,P=L-S,B=x-q,Tr[$]=0<(G*B-P*O)*Mr+(O*_-B*D)*Ir+(D*P-_*G)*vr?1:0,Er[$]=K,Fr[$]=ar+(lr=Fr[0]),ha(yr,0,gr,ar,lr),4<=$)for(Cr=0;++Cr<=$;)if(1==Tr[Cr])for(s=(u=A[(tr=(gr=l[Cr])[0])>>7])[tr&=127],w=u[tr+128],c=u[tr+256],b=(u=A[(tr=gr[(fr=Fr[Cr])-1])>>7])[tr&=127],M=u[tr+128],I=u[tr+256];;){for(ar=0,R=b-s,V=M-w,X=I-c,
Y=-Number.MAX_VALUE,lr=-1;++ar<=$;)ar!=Cr&&0==Tr[ar]&&Er[ar]==Er[Cr]&&(z=R*(_=(u=A[(tr=(yr=l[ar])[0])>>7])[tr&=127]-b)+V*(P=u[tr+128]-M)+X*(B=u[tr+256]-I))<=0&&Y<=z&&(Y=z,0<=R*(D=(m=(u=A[(tr=yr[Fr[ar]-1])>>7])[tr&=127])-s)+V*(G=(p=u[tr+128])-w)+X*(O=(F=u[tr+256])-c)&&(lr=ar,U=m,L=p,x=F));if(lr<0)break;ha(l[lr],0,gr,fr,ar=Fr[lr]),Tr[lr]=2,Fr[Cr]=fr+=ar,b=U,M=L,I=x}for(ur=a[1],sr=a[2],Cr=fr=0;++Cr<=$;)1==Tr[Cr]&&(ar=Fr[Cr],null==t[tr=(lr=0==fr++?r:za++)>>9]&&(sr[tr]=new Int16Array((
ur[tr]=new Int16Array((Ar[tr]=new Int16Array((n[tr]=new Int8Array((t[tr]=Array(512)).length)).length)).length)).length)),rr=511&lr,lr==r&&ar==br.length||(t[tr][rr]=br=new Int32Array(ar)),ha(l[Cr],0,br,0,ar),n[tr][rr]=n[or][hr],Ar[tr][rr]=cr,ur[tr][rr]=ur[or][hr],sr[tr][rr]=sr[or][hr]);return nr}function ca(r,e,t,n,a,l,f,o,h){for(var i,g,y,A,u,s=4095&~~(((g=e-l)-hf)*f),w=4095&~~((g+hf)*f);;s=s+1&4095){for(y=o[s];0<=y;y=h[u][A])if(ma((i=r[u=y>>7])[A=127&y]-e,i[128+A]-t,i[256+A]-n)<a)return y;if(
s==w)break}return null==(i=r[s=(y=Da++)>>7])&&(i=r[s]=new Float64Array(640),h[s]=new Int32Array(128)),i[w=127&y]=e,i[w+128]=t,i[w+256]=n,h[s][w]=o[s=4095&~~(g*f)],o[s]=y}function ba(r,e,t,n,a,l,f,o,h,i,g){for(var y,A,u,s,w,c,b=4095.99,M=5.960464477539063e-8,I=.2857142857142857,v=5.421010862427522e-20,d=(4095&~~(((s=Math.abs(3*(t-.5*e)-r)*I)-M)*b))-1,k=4095&~~((s+M)*b),m=o[0],p=o[1],F=o[2],E=o[3],T=o[4];++d<=k;)for(c=h[d];0<=c;c=i[c])if(ma((A=p[c])*t-(u=F[c])*e,u*r-(y=m[c])*t,y*e-A*r
)<=v&&Math.hypot(E[c]-(n-(w=l+(n*y+a*A)/(u+1))*y),T[c]-(a-w*A))<=f)return c;return m[g]=r,p[g]=e,F[g]=t,E[g]=n-(w=l+(n*r+a*e)/(t+1))*r,T[g]=a-w*e,i[g]=h[d=4095&~~(s*b)],h[d]=g}function Ma(r,e,t){var n;return Cf[n=Ga++]=r,Nf[n]=e,Sf[n]=t,n}function Xr(r,e,t,n,a,l){var f,o,h,i,g,y;if((h=t-1)>=(o=0))do{if(0<=(y=n-r[g=(i=o+h>>1)<<1])?y<=a:(y=n-r[g+1])>=-a)return l?(y<0?r[g]=n:n>r[g+1]&&(r[g+1]=n),e[i]++,t):i}while(0<y?(o=1+i)<=h:(h=i-1)>=o);return l?(g=o<<1,0!=(f=t-o)&&(ia(r,g,r,g+2,f<<1),ha(e,o,e,
o+1,f)),r[g]=r[g+(e[o]=1)]=n,t+1):0}function Ia(r,e,t){var n,a,l,f=57.29577951308232;if(e*r<=0)return 0;if(t&&(e*=f,r*=f),Math.abs(e)<=1e4)for(l=-1;++l<_a.length;)if((n=~~(r*(a=_a[l])))==1+~~(e*a))return n/a;return.5*(e+r)}function Pr(r,e,t,n){for(var a,l=-1;++l<e;)r[l]=Ia(r[a=l<<1]+t,r[1+a]-t,n);return ia(r,0,r=new Float64Array(e),0,e),r}function fr(r,e,t){var n,a,l,f,o,h,i,g,y,A,u,s,w,c,b=s=t[8]=1,M=A=u=w=t[6]=t[7]=0;0!=(y=pf[r])&&(g=1+(t[8]=mf[r]/y)*(c=t[8]<0?-1:1),b=(1-(A=-(t[6]=df[r]/y)
)*A/g)*c,s=1-(w=-(t[7]=kf[r]/y)*c)*w/g,u=(M=-A*w/g)*c),h=b*(l=df[e])+M*(f=kf[e])+A*(o=mf[e]),i=u*l+s*f+w*o,n=1,(a=0)!=(y=Math.hypot(h,i))&&(n=h/y,a=i/y),t[0]=n*b+a*u,t[1]=n*M+a*s,t[2]=n*A+a*w,t[3]=n*u-a*b,t[4]=n*s-a*M,t[5]=n*w-a*A}function or(r,e,t,n,a,l){var f,o,h;n[e]=t[0]*(f=df[r])+t[1]*(o=kf[r])+t[2]*(h=mf[r]),a[e]=t[3]*f+t[4]*o+t[5]*h,l[e]=t[6]*f+t[7]*o+t[8]*h}function hr(r,e,t,n,a,l,f,o,h){var i,g,y,A,u,s,w;if((y=(i=Lf[r]).length)==(g=Lf[e]).length&&Math.abs(Math.abs(wf[to[r]][3]
)-Math.abs(wf[to[e]][3]))<=o){for(;0<=--y;)or(i[y],y,h,a,l,f);if(A=o*o,ma(Mf[y=g[n]]-a[t],If[y]-l[t],vf[y]-f[t])<A){for(u=g.length;ma(Mf[w=g[(n+--u)%g.length]]-a[s=(t+u)%i.length],If[w]-l[s],vf[w]-f[s])<A;)if(u<=1)return 1073741824|(n+g.length-t)%g.length;for(u=g.length;ma(Mf[w=g[++n%g.length]]-a[s=(t+--u)%i.length],If[w]-l[s],vf[w]-f[s])<A;)if(u<=1)return 3221225472|(n+t)%g.length}}return 536870912}function ir(r,e,t,n,a,l,f,o,h,i){for(var g,y,A,u,s,w=Math.abs(wf[to[r]][3]),c=i*i,b=Lf[r],M=l[0],
I=f[0],v=o[0];0<=e;e--)if(!h[e]&&(y=(g=Lf[e]).length)==b.length&&Math.abs(Math.abs(wf[to[e]][3])-w)<=i)for(;0<=--y;)if(ma(t[A=g[y]]-M,n[A]-I,a[A]-v)<c){for(u=g.length;ma(t[A=g[(y+--u)%g.length]]-l[u],n[A]-f[u],a[A]-o[u])<c;)if(u<=1)return e;for(s=y+(u=g.length);ma(t[A=g[(s- --u)%g.length]]-l[u],n[A]-f[u],a[A]-o[u])<c;)if(u<=1)return e}return-1}function Br(r,e){for(var t,n=(t=Lf[r]).length;0<=--n;)if(t[n]==e)return n;return 0}function D(r,e){var t,n;(n=(t=G)[r])>t[e]&&(t[r++]=t[e],t[e++]=n,n=t[r]
,t[r]=t[e],t[e]=n)}function Dr(r,e,t,n){var a,l,f,o,h,i,g,y,A,u,s,w,c,b,M,I,v,d,k,m,p,F,E,T,C,N,S,q,U,L,x,R=2.3283064365386963e-10,V=6.283185307179586,X=df,_=kf,P=mf,B=Array(1);for(B[0]=Array(d=31);0<=--d;)B[0][d]=new Float64Array(4);for(b=Wa,d=2147483647,M=te=ee=0;0<=--b;)(k=me[n[b]])<d&&ma((l=_[I=Qf[0][b]])*(i=P[v=Qf[1][b]])-(f=P[I])*(h=_[v]),f*(o=X[v])-(a=X[I])*i,a*h-l*o)>=t*t&&(M=b,d=k);for(m=new Float64Array(9),fr(Qf[0][M],Qf[1][M],m),d=F=Oa,p=pf;0<=--d;)or(d,d,m,Mf,If,vf);for(ia(m,0,
E=new Float64Array(9),0,9),N=new Float64Array((C=new Float64Array((T=new Float64Array(Qa)).length)).length),S=!1,k=n[M];;){for(b=M+1,d=0;0<=--b;)n[b]==k&&(d+=function(r,e,t,n,a,l,f,o,h,i,g,y){var A,u,s,w,c,b,M,I,v,d,k,m,p,F,E,T,C,N,S,q,U,L,x,R,V,X,_,P,B,D,G,O,Y,z,W,Q,j,H=5.421010862427522e-20,J=3.141592653589793,K=6.283185307179586,Z=pf[tr=(E=Qf[0])[r]],$=pf[(T=Qf[1])[r]],rr=Br((C=Qf[2])[r],tr),er=Br((N=Qf[3])[r],tr),tr=T[e],nr=E[e],ar=C[e],lr=Za;r:for(F=2,p=0;0<=--F;){if(0==F){if(e==r&&!t
)return p+1;tr=nr,nr=T[e]}if(!(Math.abs(pf[tr]-Z)>h||Math.abs(pf[nr]-$)>h)){if(fr(tr,nr,i),nf)for(q=L=lr-1;0<=q;q--){for(U=(S=Lf[q]).length;0<=--U;)or(S[U],U,i,l,f,o);if(ir(q,L,Mf,If,vf,l,f,o,Hf,h)<0)continue r}else{if(q=Br(ar,tr),536870912==(x=hr(ar,R=C[r],q,rr,l,f,o,h,i))&&536870912==(x=hr(ar,R=N[r],q,er,l,f,o,h,i)))continue;for(q=lr;0<--q;)for(U=3,S=n[q];0<=--U;)S[U]=0;for(U=lr;0<=--U;)a[U]=0;for(a[(S=n[0])[0]=ar]=1,a[S[1]=R]|=2,S[2]=x,U=1;U<=lr;q++)if(U<=q){if(lr<=U)break;for(
R=lr;0<=--R&&1==(1&a[R]););for(L=(S=Lf[R]).length;0<=--L;)or(S[L],L,i,l,f,o);if((V=ir(R,lr-1,Mf,If,vf,l,f,o,Hf,h))<0||2==(2&a[V]))continue r;for(X=(S=Lf[V]).length,A=l[0],u=f[0],s=o[0];0<=--X&&pa(Mf[x=S[X]]-A,If[x]-u,vf[x]-s)>=h;);if(536870912==(x=hr(R,V,0,X,l,f,o,h,i)))continue r;a[(S=n[U++])[0]=R]|=1,a[S[1]=V]|=2,S[2]=x}else for(L=(S=Vf[R=(_=n[q])[0]]).length,P=(X=_[2])>>30,X=(B=Vf[V=_[1]]).length+(536870911&X);0<=--L;)if(O=2&a[G=C[x=B[(X-=P)%B.length]]+N[x]-V],0==(1&a[D=C[x=S[L]]+N[x]-R])){
if(2==O)continue r;if(536870912==(x=hr(D,G,O=Br(D,Lf[R][L]),Br(G,Lf[V][(X-(P-1>>1))%Lf[V].length]),l,f,o,h,i)))continue r;a[(_=n[U++])[0]=D]|=1,a[_[1]=G]|=2,_[2]=x}else if(0==O)continue r}if(p++,!t){for(U=-1,Y=new Float64Array(9);++U<3;)for(q=3;0<=--q;)for(L=9;0<=(L-=3);)Y[3*q+U]+=g[L+q]*i[L+U];if((I=(M=(z=Y[0])+(W=Y[4]))+(Q=Y[8]))<0&&(I=0==(U=z<W?W<Q?2:1:z<Q?2:0)?z-(W+Q):1==U?W-(Q+z):Q-M),I=.25/(M=.5*Math.sqrt(I+1)),A=(Y[3]+(1-(2&U))*Y[1])*I,u=(Y[2]+(1-(U<<1&2))*Y[6])*I,s=(Y[7]+((2&(U^U<<1))-1
)*Y[5])*I,d=U<2?0==U?M:A:2==U?u:s,k=U<2?0==U?A:M:2==U?s:u,m=U<2?0==U?u:s:2==U?M:A,0==(I=1-(v=U<2?0==U?s:u:2==U?A:M)*v))continue;for(U=0,A=d/(I=Math.sqrt(I)),u=k/I,s=m/I;U<ee&&ma(u*(b=(j=y[0][U])[2])-s*(c=j[1]),s*(w=j[0])-A*b,A*c-u*w)>=H;U++);ee<=U&&(U==y[0].length&&(y[0][U]=new Float64Array(4)),(j=y[0][U])[0]=A,j[1]=u,j[2]=s,j[3]=K,ee++),(I=2*Math.acos(v))>J&&(I=K-I),I<j[3]&&(j[3]=I)}}}return p}(M,b,S,r,e,T,C,N,t,m,E,B));if(S)break;for(S=!0,le=d,d=F;0<=--d;)If[d]=-If[d]}if(ae=d,G=new Int32Array(
6),1<(ne=le)){for(d=ee,ne=0;0<=--d;)for((I=~~(V/B[0][d][3]+.5))>ne&&(ne=I),k=0;k<6;k+=2)if(0==(q=G)[k]||q[k]==I){q[k]=I,q[k+1]++;break}D(4,2),D(2,0),D(4,2)}for(b=k=F,fe=!0;(u=p[--b])<t;)if(b<=0)return;for(c=Array(d=15);0<=--d;)c[d]=new Float64Array(3);for(a=X[d=b],l=_[b],f=P[b],w=R*u;0<=--d;)if((s=p[d])>=t&&pa(g=l*(i=P[d])-f*(h=_[d]),y=f*(o=X[d])-a*i,A=a*h-l*o)>=w*s){for(k=d,w*=s;;){if(--k<0){(U=c[0])[0]=g/(w=u*s),U[1]=y/w,U[2]=A/w,te=1;break}if(Math.abs(X[k]*g+_[k]*y+P[k]*A)>=w)break}break}for(
L=new Uint8Array(Za),I=b;;){for(v=F,a=X[I],l=_[I],f=P[I],w=p[I];0<=--v;)v!=I&&Math.abs(p[v]-w)<=t&&(c=function(r,e,t,n,a,l,f,o,h){var i,g,y,A,u,s,w,c,b,M,I,v,d,k=5.421010862427522e-20,m=3019169939857233e154;if(0==(A=pa(r,e,t))&&0==(A=pa(r*=m,e*=m,t*=m)))return h;for(u=w=te,r/=A,e/=A,t/=A;0<=--u;)if(ma(e*(y=(c=h[u])[2])-t*(g=c[1]),t*(i=c[0])-r*y,r*g-e*i)<k)return h;for(u=f.length;0<=--u;)f[u]=!1;for(b=df,M=kf,I=mf,u=f.length;0<=--u;)if(!f[u]){for(s=(d=Lf[u]).length;0<=--s;)A=2*((i=b[v=d[s]])*r+(
g=M[v])*e+(y=I[v])*t),n[s]=i-r*A,a[s]=g-e*A,l[s]=y-t*A;if((s=ir(u,u,b,M,I,n,a,l,f,o))<0)return h;f[s]=!0}return w==h.length&&(h[w]=new Float64Array(3)),(c=h[w])[0]=r,c[1]=e,c[2]=t,te++,h}(X[v]-a,_[v]-l,P[v]-f,T,C,N,L,t,c));if(I==k||(I=I==b?d:k)<0)break}for(d=L.length;0<=--d;)L[d]=!1;for(d=L.length;0<=--d;)if(!L[d]){for(k=(x=Lf[d]).length;0<=--k;)T[k]=-X[I=x[k]],C[k]=-_[I],N[k]=-P[I];if((k=ir(d,d,X,_,P,T,C,N,L,t))<0)return void(fe=!1);L[k]=!0}}function gr(r,e,t,n,a){var l;r[3]=a,1<=Math.abs(
r[0]=e/=l=pa(e,t,n))?r[1]=r[2]=0:1<=Math.abs(r[1]=t/=l)?r[0]=r[2]=0:1<=Math.abs(r[2]=n/=l)?r[0]=r[1]=0:1<=e*e+t*t?r[2]=0:1<=e*e+(l=n*n)?r[1]=0:1<=t*t+l&&(r[0]=0)}function va(r,e,t,n,a){for(var l,f,o,h,i,g,y,A,u,s,w,c,b,M,I,v,d,k,m,p,F,E,T,C,N,S,q,U,L,x,R,V,X,_,P,B,D,G,O,Y,z,W,Q,j,H,J,K,Z,$,rr,er,tr,nr,ar=l=f=o=h=i=g=y=A=u=s=0,lr=Za;0<=--lr;)for(m=2,F=r[p=(k=Lf[lr])[0]],E=e[p],T=t[p],C=r[p=k[1]],N=e[p],S=t[p];m<k.length;m++)w=(R=N-E)*(P=(L=t[p=k[m]])-T)-(V=S-T)*(_=(U=e[p])-E),c=V*(X=(q=r[p])-F)-(
x=C-F)*P,b=x*_-R*X,B=(M=F+C)+q,D=(v=(I=F*F)+C*M)+q*B,G=F*I+C*v+q*D,O=D+F*(B+F),Y=D+C*(B+C),z=D+q*(B+q),W=(M=E+N)+U,Q=(v=(I=E*E)+N*M)+U*W,j=E*I+N*v+U*Q,H=Q+E*(W+E),J=Q+N*(W+N),K=Q+U*(W+U),Z=(M=T+S)+L,$=(v=(I=T*T)+S*M)+L*Z,rr=T*I+S*v+L*$,er=$+T*(Z+T),tr=$+S*(Z+S),nr=$+L*(Z+L),ar+=d=w*B,l+=Math.abs(d),f+=w*D,o+=c*Q,h+=b*$,i+=w*G,g+=c*j,y+=b*rr,A+=w*(E*O+N*Y+U*z),u+=c*(T*H+S*J+L*K),s+=b*(F*er+C*tr+q*nr),C=q,N=U,S=L;n[0]=f/(d=4*(Math.abs(ar)>=16*hf?ar:0!=l?l:.25)),n[1]=o/d,n[2]=h/d,null!=a&&(w=(
M=n[0]/24)*f,function(r,e,t,n,a,l,f,o,h){var i,g,y,A,u,s,w,c,b,M,I,v,d,k,m,p,F,E,T,C,N,S,q,U,L=.7071067811865476,x=m=p=F=E=T=C=N=S=0,R=0==r&&0==n&&0==l;r:for(;;){if(0==e){if(0==t){if(v=r,x=1,0==a){d=n,k=l,E=S=1;break r}if(R){k=-(d=a),N=-(E=T=S=L);break r}s=Math.hypot(n-l,2*a),k=(n*l-a*a)/(d=.5*((i=n+l)<0?i-s:i+s)),Math.abs(s=d-n)>Math.abs(i=k-n)?(E=S=a/(g=Math.hypot(a,s)),N=-(T=s/g)):(T=-(N=a/(g=Math.hypot(a,i))),E=S=i/g);break r}if(0==a){if(v=n,m=1,R){k=-(d=t),S=-(F=C=T=L);break r}s=Math.hypot(
r-l,2*t),k=(r*l-t*t)/(d=.5*((i=r+l)<0?i-s:i+s)),Math.abs(s=d-l)>Math.abs(i=k-l)?(S=-(F=s/(g=Math.hypot(t,s))),C=T=t/g):(C=T=i/(g=Math.hypot(t,i)),F=-(S=t/g));break r}if(0==r&&0==n){s=Math.sqrt(l*l+4*(i=t*t+a*a)),k=-i/(d=.5*(l<0?l-s:l+s)),F=t/(g=Math.sqrt(d*d+i)),E=a/g,T=d/g,C=t/(g=Math.sqrt(k*k+i)),N=a/g,S=k/g,v=0,x=a/(g=Math.hypot(t,a)),m=-t/g,k<d&&(x=-x,m=-m);break r}}if(0==t&&0==a){if(v=l,p=1,R){k=-(d=e),C=-(F=E=N=L);break r}s=Math.hypot(r-n,2*e),k=(r*n-e*e)/(d=.5*((i=r+n)<0?i-s:i+s)),
Math.abs(s=d-r)>Math.abs(i=k-r)?(F=N=e/(g=Math.hypot(e,s)),C=-(E=s/g)):(E=-(C=e/(g=Math.hypot(e,i))),F=N=i/g);break r}if(0==l){if(0==r&&0==t){s=Math.sqrt(n*n+4*(i=e*e+a*a)),k=-i/(d=.5*(n<0?n-s:n+s)),F=e/(g=Math.sqrt(d*d+i)),E=d/g,T=a/g,C=e/(g=Math.sqrt(k*k+i)),N=k/g,S=a/g,v=0,x=-a/(g=Math.hypot(e,a)),p=e/g,k<d&&(x=-x,p=-p);break r}if(0==n&&0==a){s=Math.sqrt(r*r+4*(i=e*e+t*t)),k=-i/(d=.5*(r<0?r-s:r+s)),F=d/(g=Math.sqrt(d*d+i)),E=e/g,T=t/g,C=k/(g=Math.sqrt(k*k+i)),N=e/g,S=t/g,v=0,m=t/(
g=Math.hypot(e,t)),p=-e/g,k<d&&(m=-m,p=-p);break r}}for(v=r,(U=0!=t)?(S=-(E=e/(M=Math.hypot(e,t))),d=n+(g=(N=T=t/M)*(i=2*E*a+N*(l-n))),k=l-g,I=a-E*i):(d=n,k=l,M=e,I=a,E=S=1),x=1,q=8;0<=--q&&(w=Math.abs(v)+Math.abs(d),Math.abs(M)+w!=w);){if(w=Math.abs(d)+Math.abs(k),A=Math.hypot(i=(d-v)/(2*M),1),s=M/(i<0?i-A:i+A),Math.abs(I)+w!=w)if(Math.abs(I)>=Math.abs(i=k-v+s)?(c=i/I,c*=u=1/(A=Math.hypot(c,1))):(u=I/i,u*=c=1/(A=Math.hypot(u,1))),k+=y=u*(A=(d-k)*u+2*c*I),C=u*F+c*(s=C),F=c*F-u*s,N=u*E+c*(s=N),
E=c*E-u*s,S=u*T+c*(s=S),T=c*T-u*s,b=c*M,Math.abs(s=u*M)>=Math.abs(i=c*A-I)){if(0==s){I=0,d-=y;continue}I=s*(A=Math.hypot(c=i/s,1)),c*=u=1/A}else I=i*(A=Math.hypot(u=s/i,1)),u*=c=1/A;else i=d-v+s,y=I=0,Math.abs(s=b=M)>=Math.abs(i)?(c=i/s,c*=u=1/(A=Math.hypot(c,1))):(u=s/i,u*=c=1/(A=Math.hypot(u,1)));d=(i=d-y)+(y=u*(A=(v-i)*u+2*c*b)),F=u*x+c*(s=F),x=c*x-u*s,E=u*m+c*(s=E),m=c*m-u*s,T=u*p+c*(s=T),p=c*p-u*s,v-=y,M=c*A-b}for(q=8;0<=--q&&(w=Math.abs(d)+Math.abs(k),Math.abs(I)+w!=w);)A=Math.hypot(i=(
y=k-d)/(2*I),1),Math.abs(I)>=Math.abs(i=y+I/(i<0?i-A:i+A))?(c=i/I,c*=u=1/(A=Math.hypot(c,1))):(u=I/i,u*=c=1/(A=Math.hypot(u,1))),k+=y=u*(A=(d-k)*u+2*c*I),C=u*F+c*(s=C),F=c*F-u*s,N=u*E+c*(s=N),E=c*E-u*s,S=u*T+c*(s=S),T=c*T-u*s,d-=y,I=c*A-I;U&&(C=-C,N=-N,S=-S);break r}gr(f,x,m,p,v),gr(o,F,E,T,d),gr(h,C,N,S,k)}((g+y)/60-((c=(I=n[1]/24)*o)+(b=(v=n[2]/24)*h)),M*o-A/120,v*f-s/120,(i+y)/60-(w+b),I*h-u/120,(i+g)/60-(w+c),a[0],a[1],a[2]))}function v(r,e){var t;return r-(t=r-e)==e&&t+e==r}function d(r,e,t
){var n,a;return r?isFinite(r)?(e[0]=r=Math.abs(r),n=t[0],t[1],4294967295<++n&&(n=0,0),a=e[0],isFinite(a)?a-r:199584030953472e278):1/0:Number.MIN_VALUE}function da(r,e){for(var t,n,a,l,f,o,h,i,g,y,A,u,s,w,c,b,M=e,I=t=r[0];0<--M;)(h=r[M])<I&&(I=h),t<h&&(t=h);if((f=I)*(o=t)<=0)return 0;y=new Uint32Array((g=new Float64Array(1)).buffer);r:for(a=.5*(I+t),l=0;(n=.5*(I+t))!=I&&n!=t;)e:for(i=n;;){for(M=e;0<=--M;)if(!v(r[M],i)){if(g[0]=i,A=s=y[0],0==(2146435072&(u=w=y[1])))for(;u=u<<1|A>>>31,A<<=1,0==(
2146435072&u););if(!(A||1048575&u)){for(c=M+1,b=0;0<=--c;)if(!v(h=r[c],i)&&3==(b|=h<i?1:2))break r;1==b?t=n:I=n;continue r}if(s){for(A=1;!(s&A);A<<=1);y[0]=s&~A,y[1]=w}else{for(u=1;!(w&u);u<<=1);y[0]=s,y[1]=w&~u}i=g[0];continue e}if((l=i)==a)break r;l<a?I=n:t=n;continue r}return 0!=l&&((h=d(f,g,y))>(i=d(o,g,y))?h:i)>((I=d(f-l,g,y))>(t=d(o-l,g,y))?I:t)?l:0}function ka(r,e){for(var t,n,a=e,l=t=r[0];0<--a;)(n=r[a])<l&&(l=n),t<n&&(t=n);return t-l}function Gr(r,e,t,n,a,l,f){var o,h,i,g;if(t<=3
)return 1==e?"equilateral triangle":2==e?"isosceles triangle":"scalene triangle";if(4==t)return 1==e?1==r?"square":"rhombus":1==l?"bowtie":2==e?a[0]==a[2]&&a[1]==a[3]?1==r?"rectangle":"parallelogram":a[0]==a[1]&&a[2]==a[3]||a[0]==a[3]&&a[1]==a[2]?2==r?0==f?"tri-equiangular kite":"tri-equiangular dart":0==f?"kite":"dart":2==r?"tri-equilateral trapezoid":"tri-equilateral tetragon":2==r&&(n[0]==n[1]&&n[2]==n[3]||n[0]==n[3]&&n[1]==n[2])?"isosceles trapezoid":"irregular tetragon";if(o=h=!1,0==(1&t)
)if(1==e&&2==r){for(i=0,g=2;g<t&&n[i]==n[g];i++,g++);o=t<=g}else if(1==r&&2==e){for(i=0,g=2;g<t&&a[i]==a[g];i++,g++);h=t<=g}return!(o|h)||16<t?(0==(i=~~(l/t))||i*t==l&&++i%t!=0||(i=0),(1==e&&1==r?"regular ":function(r,e,t){for(var n,a,l,f=0,o=(n=r)>>1,h=r+1>>1;0<=--n;){for(a=1,l=n+r;a<h&&t[(l-a)%r]==t[(n+a)%r];a++);if(h<=a){for(a=0;a<o&&e[(l-a)%r]==e[(n+a+1)%r];a++);o<=a&&f++}}for(n=r;0<=--n;){for(a=1,l=n+r;a<h&&e[(l-a)%r]==e[(n+a)%r];a++);if(h<=a){for(a=0;a<o&&t[(l-a-1)%r]==t[(n+a)%r];a++);
o<=a&&f++}}if(0<f)return((f>>=1)<=3?_e[f-1]:f+"-")+"mirror-symmetric ";for(n=r>>1;2<=n;n--)if(r%n==0){for(a=r/n,l=0;l<a;l++){for(f=1;f<n&&e[l]==e[l+a*f]&&t[l]==t[l+a*f];f++);if(f<n)break}if(l==a)break}return 1<n?"C"+n+"-symmetric ":"irregular "}(t,n,a))+(0==i?"":t+"/"+i+" ")+(t<=16?_q[t-5]:t+"-")+(0==i?"gon":"gram")):_q[t+(o?7:6)]}function ma(r,e,t){return e*=e,(r*=r)<(t*=t)&&e<t?r+e+t:r<e?r+t+e:e+t+r}function pa(r,e,t){return Math.sqrt(ma(r,e,t))}function Or(r,e){var t,n;return Math.abs((t=r[e]
)+(n=bf[e]))<hf?-n:t}function Yr(r,e,t,n,a,l,f,o,h,i){for(var g,y,A,u,s,w,c,b,M,I,v,d=0==n?Xf:Vf,k=Qf[n+1],m=Qf[n],p=Oa;0<=--p;)f[p]=0;for(p=h.length;0<=--p;)h[p]=!1;for(w=r,f[A=e?k[w]:m[w]]=g=y=1,i&&(I=l[0]==(a[0]=1));;){for(o[w]=1,h[M=(u=m[w]+k[w]-A)<A?w+Wa:w]=!0,p=c=(v=d[u]).length;0<=--p&&v[p]!=w;);if(0==(s=f[u]))w=v[(p+c+t)%c],f[u]=s=++g;else if(h[Wa+(w<<1)-M]){for(b=1,p+=c;b<c&&h[m[w=v[(p+t*b)%c]]+k[w]<u<<1?w+Wa:w];b++);if(c<=b)return void(i&&(a[y++]=1,ha(a,0,l,0,y)))}if(i){if(I){if(s>l[y]
)return;I=s==l[y]}a[y++]=s}A=u}}function zr(r,e,t,n,a,l,f){var o,h=r;for(n[0]=2147483647;h<Wa;h++)if(h==r||1==l[h])for(o=-3;(o+=2)<=1;)Yr(h,!1,o,e,t,n,a,l,f,!0),Yr(h,!0,o,e,t,n,a,l,f,!0)}function xr(){for(var r,e,t,n,a,l,f,o,h,i,g,y,A,u,s,w,c,b,M,I,v,d,k,m,p,F,E,T,C,N,S,q,U,L,x,R,V,X,_,P,B,D,G,O,Y,z,W,Q,j,H,J,K,Z,$,rr,er,tr,nr,ar,lr,fr,or,hr,ir,gr,yr,Ar,ur,sr,wr,cr,br,Mr,Ir,vr,dr,kr,mr,pr,Fr,Er,Tr,Cr,Nr,Sr=2.3283064365386963e-10,qr=3.141592653589793,Ur=1.4629180792671596e-9,Lr=af*Sr,
xr=new Float64Array((s=new Float64Array((u=new Int32Array((A=new Int32Array((y=new Int32Array((g=new Int32Array(i=Wa)).length)).length)).length)).length<<1)).length),Rr=new Int32Array((c=Array(e=w=Za)).length),Vr=0;0<=--e;)Vr+=t=Lf[e].length,c[e]=new Int32Array(t);for(M=new Float64Array((b=new Int32Array(Vr)).length<<1),k=new Int32Array((d=new Int32Array((v=new Int32Array((I=Array(w)).length)).length)).length),p=0,m=new Float64Array(Vr>(e=i)?Vr:i);0<=--e;)p=Xr(s,y,p,m[e]=pa(
df[f=Qf[0][e]]-df[o=Qf[1][e]],kf[f]-kf[o],mf[f]-mf[o]),Lr,!0);for(e=i;0<=--e;)g[e]=Xr(s,y,p,m[e],Lr,!1);for(Me=Pr(s,p,Lr,!1),me=Aa(y,Kr=p),F=0,e=i;0<=--e;)F=Xr(xr,u,F,m[e]=(x=e,Q=Q=W=z=Y=B=void 0,z=3.141592653589793,W=Lf[B=(O=Qf)[2][x]],Q=Br(B,_=O[0][x]),j=(Y=wf[to[B+=(G=O[3][x])-(D=W[(Q+1)%W.length]==(P=O[1][x])?B:G)]])[0],H=Y[1],J=Y[2],K=(Y=wf[to[D]])[0],Z=Y[1],$=Y[2],rr=Math.atan2(pa(R=H*$-J*Z,V=J*K-j*$,X=j*Z-H*K),j*K+H*Z+J*$),Q=Br(G,_),((W=Lf[G])[(Q+1)%W.length]==P?B:D)==G?rr:z+rr*(0<=R*(
df[P]-df[_])+V*(kf[P]-kf[_])+X*(mf[P]-mf[_])?1:-1)),Ur,!0);for(e=i;0<=--e;)A[e]=Xr(xr,u,F,m[e],Ur,!1);for(Ie=Pr(xr,F,Ur,!0),pe=Aa(u,Zr=F),e=w,Vr=E=0;0<=--e;)for(t=(r=Lf[e]).length,o=r[0],h=r[1];0<=--t;)E=Xr(M,b,E,m[Vr++]=(er=e,tr=f=r[t],ar=h,Ir=Mr=br=cr=wr=sr=ur=Ar=yr=or=fr=lr=void 0,Ar=3.141592653589793,ur=(lr=(hr=df)[nr=o])-hr[tr],sr=(fr=(ir=kf)[nr])-ir[tr],wr=(or=(gr=mf)[nr])-gr[tr],cr=hr[ar]-lr,br=ir[ar]-fr,Mr=gr[ar]-or,Ir=Math.atan2(pa(lr=sr*Mr-wr*br,fr=wr*cr-ur*Mr,or=ur*br-sr*cr),
ur*cr+sr*br+wr*Mr),Ar+Ir*(0<=lr*(yr=wf[to[er]])[0]+fr*yr[1]+or*yr[2]?-1:1)),Ur,!0),h=o,o=f;for(e=w,Vr=0;0<=--e;)for(t=(r=c[e]).length;0<t;t--)(T=m[Vr++])>qr&&k[e]++,r[t%r.length]=Xr(M,b,E,T,Ur,!1);for(ve=Pr(M,E,Ur,!0),Fe=Aa(b,$r=E),e=w;0<=--e;)for(C=c[e],t=(r=Vf[e]).length;0<=--t;)C[t]|=g[r[t]]<<16;for(e=N=0;e<w;e++){for(S=go[e],t=Vr=0,r=c[e];++t<r.length;)for(n=0;n<r.length;n++)if(0!=(q=r[(n+Vr)%r.length]-r[(n+t)%r.length])){0<q&&(Vr=t);break}r:for(t=0;t<N;t++)if(v[t]==S&&(U=I[t]
).length==r.length){for(l=r.length;0<=--l;)if(U[l]!=r[(l+Vr)%r.length])continue r;break}if(N<=t){for(U=I[t]=new Int32Array(l=r.length);0<=--l;)U[l]=r[(l+Vr)%r.length];N++,v[t]=S,k[t]=k[e]}d[Rr[e]=t]++}for(dr=N,(vr=I).length=dr,de=vr,Aa(v,N),Ee=Aa(d,N),Aa(k,N),L=new Int32Array((C=new Int32Array(Qa)).length),Ne=new Int32Array((Ce=new Int32Array((Te=new Int32Array((ke=Array(e=re=N)).length)).length)).length);0<=--e;){for(t=(r=I[e]).length,Vr=0;0<=--t;){for(l=0,a=65535&r[t];l<Vr&&a!=C[l];l++);
Vr<=l&&(C[Vr++]=a)}for(Ce[e]=Vr,t=(r=I[e]).length,Vr=0;0<=--t;){for(l=0,a=r[t]>>>16;l<Vr&&a!=C[l];l++);Vr<=l&&(C[Vr++]=a)}Ne[e]=Vr,ke[e]=new Int32Array(d[e]),d[e]=0}for(e=w;0<=--e;)c[ke[t=Rr[e]][d[t]++]=e].length<3&&(c[e]=new Int32Array(3));for(Ue=Array(e=N);0<=--e;){for(t=Vr=(r=I[e]).length;0<=--t;)C[t]=65535&r[t],L[t]=r[t]>>>16;Ue[e]=Gr(Ce[e],Ne[e],Vr,C,L,v[e],k[e])}nf||(Qr=Oa-i+w),function(r){var e,t,n,a,l,f,o,h,i,g,y,A,u,s,w,c,b,M,I,v,d,k,m,p,F,E,T,C,N,S,q,U,L,x,R,V,X,_,P,
B=3019169939857233e154,D=df,G=kf,O=mf,Y=hf;for(we=new Float64Array(3),A=u=s=q=0,m=Number.MAX_VALUE;;){for(S=Oa,p=Number.MAX_VALUE,F=0;0<=--S;)(t=ma((w=D[S])-A,(c=G[S])-u,(b=O[S])-s))<p&&(p=t,f=w,o=c,h=b),F<t&&(F=t,i=w,g=c,y=b);if((t=Math.sqrt(F)-Math.sqrt(p))<m){if(we[0]=A,we[1]=u,we[2]=s,0==(m=t))break;q=0}else if(5<++q)break;0==(t=pa(M=i-f,I=g-o,v=y-h))&&(t=pa(M*=B,I*=B,v*=B)),A-=(e=A*(M/=t)+u*(I/=t)+s*(v/=t)-.5*((f+i)*M+(o+g)*I+(h+y)*v))*M,u-=e*I,s-=e*v}if(he=m<r){for(A=Or(we,0),u=Or(we,1),
s=Or(we,2),S=Oa,E=Number.MAX_VALUE,T=0;0<=--S;)(t=ma(D[S]-A,G[S]-u,O[S]-s))<E&&(E=t),T<t&&(T=t);Math.sqrt(T)-Math.sqrt(E)<r&&(we[0]=A,we[1]=u,we[2]=s,p=E,F=T),Ae=Ia(Math.sqrt(F)+Y,Math.sqrt(p)-Y,!1)}for(ce=new Float64Array(3),A=u=s=q=0,m=Number.MAX_VALUE;;){for(S=Za,p=Number.MAX_VALUE,F=0;0<=--S;)R=(t=-(A*(w=(x=wf[to[S]])[0])+u*(c=x[1])+s*(b=x[2])+(e=x[3])))<0&&tf?-1:1,w*=R,c*=R,b*=R,e*=R,(t*=R)<p&&(p=t,f=w,o=c,h=b,d=e),F<t&&(F=t,i=w,g=c,y=b,k=e);if((t=F-p)<m){if(ce[0]=A,ce[1]=u,ce[2]=s,0==(m=t)
)break;q=0}else if(5<++q)break;if(0==(t=pa(M=i-f,I=g-o,v=y-h)))break;A-=(e=A*(M/=t)+u*(I/=t)+s*(v/=t)+(k-d)/t)*M,u-=e*I,s-=e*v}if(ie=m<r){for(A=Or(ce,0),u=Or(ce,1),s=Or(ce,2),S=Za,E=Number.MAX_VALUE,T=0;0<=--S;)(t=-(A*(x=wf[to[S]])[0]+u*x[1]+s*x[2]+x[3]))<E&&(E=t),T<t&&(T=t);T-E<r&&(ce[0]=A,ce[1]=u,ce[2]=s,p=E,F=T),ue=Ia(F+Y,p-Y,!1)}for(V=Qf[0],X=Qf[1],_=Wa,be=new Float64Array(3),A=u=s=q=U=0,m=Number.MAX_VALUE;;){for(S=_,E=Number.MAX_VALUE,T=0;0<=--S;)w=D[C=V[S]]-(n=D[N=X[S]]),c=G[C]-(a=G[N]),
b=O[C]-(l=O[N]),n+=(t=((A-n)*w+(u-a)*c+(s-l)*b)/ma(w,c,b))*w-A,(t=ma(n,a+=t*c-u,l+=t*b-s))<E&&(E=t),T<t&&(T=t);if((t=Math.sqrt(T)-Math.sqrt(E))<m){if(be[0]=A,be[1]=u,be[2]=s,p=E,F=T,0==(m=t))break;q=0}else if(5<++q)break;for(C=Oa,L=f=o=h=T=0;0<=--C;)for(S=(x=Xf[C]).length,w=A-(i=D[C]),c=u-(g=G[C]),b=s-(y=O[C]);0<=--S;)for(t=pa(n=D[N=V[R=x[S]]+X[R]-C]-i,a=G[N]-g,l=O[N]-y),n*w+a*c+l*b<0&&(n=-n,a=-a,l=-l),R=S,n/=t,a/=t,l/=t;0<=--R;)t=pa(M=D[N=V[P=x[R]]+X[P]-C]-i,I=G[N]-g,v=O[N]-y),M*w+I*c+v*b<0&&(
M=-M,I=-I,v=-v),0!=(e=pa(M=M/t-n,I=I/t-a,v=v/t-l))&&(L++,f+=(t=w*(M/=e)+c*(I/=e)+b*(v/=e))*M,o+=t*I,h+=t*v,(t=Math.abs(t))>T&&(T=t));if(r<T&&1e4<++U)break;A-=f/L,u-=o/L,s-=h/L}if(ye=!1,ge=m<r){for(A=Or(be,0),u=Or(be,1),s=Or(be,2),S=_,f=o=h=0,E=Number.MAX_VALUE,T=0;0<=--S;)w=D[C=V[S]]-(n=D[N=X[S]]),c=G[C]-(a=G[N]),b=O[C]-(l=O[N]),i=(n+=(t=((A-n)*w+(u-a)*c+(s-l)*b)/ma(w,c,b))*w)-A,(t=ma(i,g=(a+=t*c)-u,y=(l+=t*b)-s))<E&&(E=t),T<t&&(T=t),f+=n,o+=a,h+=l;Math.sqrt(T)-Math.sqrt(E)<r&&(be[0]=A,be[1]=u,
be[2]=s,p=E,F=T),se=Ia(Math.sqrt(F)+Y,Math.sqrt(p)-Y,!1),ye=ma(f/_-be[0],o/_-be[1],h/_-be[2])<r*r}}(Lr),function(){var r,e,t,n,a,l,f,o,h,i,g,y=new Uint8Array(r=(l=new Int8Array(Wa)).length<<1),A=new Int32Array((f=Oa)>(o=Za)?f:o);for((oe=f==o&&ja==Qa)&&(h=new Int32Array((g=new Int32Array((i=new Int32Array(++r)).length)).length)),e=Wr=0,a=!1;!a;){if(oe){for(zr(e,0,i,g,A,l,y),ha(g,0,h,0,r),zr(e,2,i,g,A,l,y),t=r;0<=--t&&h[t]==g[t];);oe=t<0}else Yr(e,!1,-1,0,i,g,A,l,y,!1);for(t=e-1,a=!0,
Wr++;++t<l.length;)1==(n=l[t])?l[t]=2:a&&0==n&&(e=t,a=!1)}}(),Dr(c,Rr,Lr,g),mr="U",pr="Unknown",Fr=te,Er=ne,Tr=ae,Cr=le,Nr=fe,0==(kr=ee)?1==Er&&1==Cr&&(1==Fr?1!=Tr||Nr||(mr="Cs = C1h = C1v",pr="Reflection"):0==Fr&&(1==Tr?Nr&&(mr="Ci = S2",pr="Inversion"):0!=Tr||Nr||(mr="C1",pr="No Symmetry"))):1==kr?2<=Er&&Er==Cr&&(Tr==Er?0==Fr?1==(1&Er)==Nr&&(mr="S"+(Er<<1),pr=Er+"-fold Rotoreflection"):1==Fr?1==(1&Er)!=Nr&&(mr="C"+Er+"h",pr=Er+"-fold Cyclic + Perpendicular Reflection"):Fr!=Er||Nr||(
mr="C"+Er+"v",pr=Er+"-fold Pyramidal"):0!=Tr||0!=Fr||Nr||(mr="C"+Er,pr=Er+"-fold Cyclic")):kr==Er+1?2<=Er&&Er<<1==Cr&&(Tr==Cr?Fr==kr?1==(1&Er)!=Nr&&(mr="D"+Er+"h",pr=Er+"-fold Prismatic"):Fr==Er&&1==(1&Er)==Nr&&(mr="D"+Er+"v",pr=Er+"-fold Antiprismatic"):0!=Tr||0!=Fr||Nr||(mr="D"+Er,pr=Er+"-fold Dihedral")):7==kr?3==Er&&12==Cr&&(12==Tr?6==Fr?Nr||(mr="Td",pr="Full Tetrahedral"):3==Fr&&Nr&&(mr="Th",pr="Pyritohedral"):0!=Tr||0!=Fr||Nr||(mr="T",pr="Chiral Tetrahedral")):13==kr?4==Er&&24==Cr&&(
24==Tr?9==Fr&&Nr&&(mr="Oh",pr="Full Octahedral"):0!=Tr||0!=Fr||Nr||(mr="O",pr="Chiral Octahedral")):31==kr&&5==Er&&60==Cr&&(60==Tr?15==Fr&&Nr&&(mr="Ih",pr="Full Icosahedral"):0!=Tr||0!=Fr||Nr||(mr="I",pr="Chiral Icosahedral")),Se=mr,qe=pr,vf=pf=wf=null,Vf=Xf=Qf=null,to=go=null,rf=!0}function Fa(r,e){var t;return r=r.substring(1-(t="-"==r.charAt(0)?-1:1)>>1),t*("C"==r.charAt(0)?e[parseInt(r.substring(1),10)]:parseFloat(r))}function Ea(r){r.preventDefault()}function t(r,e,t){var n,a,l,f,o,h
;r?Jl=!0:Hl=!0,l=~~(e-(a=Kn.getBoundingClientRect()).left+.5),f=~~(t-a.top+.5),w=0,Sl<l&&l<=ql&&Tl<f&&f<=Cl?(w=1,($l^=!0)?(Kn.style.cursor="all-scroll",A=l,u=f):Kn.style.cursor="default",nl=el,al=tl,Ra()):$l?(A=l,u=f):(il<l&&l<=gl&&yl<f&&f<=Al?0<=(w=0<(s=l-(n=cl))&&s<=Il&&bl<f&&f<=Ml?-1:1)&&(l<=n?kl<n&&cl--:n+Il<l&&n<ml&&cl++):Fl<l&&l<=El&&Tl<f&&f<=Cl?(w=1,Kl^=!0):Fl<l&&l<=El&&Ul<f&&f<=Ll?(w=1,Zl^=!0):Zl&&xl<f&&f<=Rl&&0!=(n=ro[(f-xl-1)*Va+l])?(w=1)==n?(jl=(jl+re-1)%re,Mo="lightGray"):2==n?(jl=0,
vo="lightGray"):3==n?(jl=(jl+1)%re,Io="lightGray"):(5==n?(o=0,po="lightGray"):(o=Te[jl],h=Ee[jl],4==n?(o=(o+h-1)%h,ko="lightGray"):(o=(o+1)%h,mo="lightGray")),Te[jl]=o):(el=l,tl=g=f),0<w&&(nl=el,al=tl,xa(),Ra()))}function Ta(r){r.button&&2!=r.button||t(r.button,r.clientX,r.clientY)}function Ca(r){var e;r.preventDefault(),t(0,(e=r.targetTouches[0]).clientX,e.clientY)}function e(r){r?Jl=!1:Hl=!1,Mo=Io=vo=ko=mo=po="black",Ra()}function Na(r){r.button&&2!=r.button||e(r.button)}function Sa(r){
r.preventDefault(),e(0)}function n(r,e){var t,n,a,l,f,o,h,i;Hl|Jl&&($l||w<=0)&&(n=~~(r-(t=Kn.getBoundingClientRect()).left+.5),$l?(a=~~(e-t.top+.5),Hl&&((fl+=n-A)<-1600&&(fl=-1600),ol+=a-u),Jl&&(768<(l=hl+(a-u))?l=768:l<160&&(l=160),ol=(f=Xa>>1)-~~((f-ol)*(f=l>>5)/(o=hl>>5)),hl=l,(q=Xa-~~((Xa-q)*f/o))>ll&&(q=ll)),A=n,u=a,ol<q&&(ol=q),ll<ol&&(ol=ll)):(nl=el,al=tl,w<0?cl=(n-=s)<kl?kl:ml<n?ml:n:(a=~~(e-t.top+.5),Hl&&(el=n,tl=a),Jl&&.5<=(i=(h=lf*Math.exp((a-g)*Af))*af)&&(lf=h,ff=.75/(gf<i?.5*(i+gf
):i)),g=a),xa()),Ra())}function qa(r){n(r.clientX,r.clientY)}function Ua(r){var e;r.preventDefault(),n((e=r.targetTouches[0]).clientX,e.clientY)}function La(){Hl=Jl=!1,Mo=Io=vo=ko=mo=po="black"}function xa(){var r,e,t,n,a,l,f,o,h,i,g,y,A,u,s,w,c,b,M,I,v,d,k,m,p,F,E,T,C,N,S,q,U,L,x,R,V,X,_,P,B,D,G,O,Y,z,W,Q,j,H,J,K,Z,$,rr,er,tr,nr,ar,lr,fr,or,hr,ir,gr,yr,Ar,ur,sr,wr,cr,br,Mr,Ir,vr,dr,kr,mr,pr,Fr,Er,Tr,Cr,Nr=1.5707963267948966,Sr=(nl-Pa)*(R=ff),qr=(Ba-al)*R,Ur=(el-Pa)*R,Lr=(Ba-tl)*R;for(1<=(
X=Math.hypot(Sr,qr))?(0!=(R=Math.hypot(Ur,Lr))&&(Ur*=R=1-(X-1)/R,Lr*=R),e=0):(X=pa(Sr,qr,e=Math.cos(X*Nr)),e/=X),Sr/=X,qr/=X,1<(X=Math.hypot(Ur,Lr))&&(Ur*=R=(V=X%4)/X,Lr*=R,1<V&&(Ur*=R=(V<=3?2-V:V-4)/V,Lr*=R)),n=e*(Ur/=X=pa(Ur,Lr,r=Math.cos(X*Nr)))-(r/=X)*Sr,a=Sr*(Lr/=X)-Ur*qr,f=(t=qr*r-Lr*e)*(X=.5/(l=Math.sqrt(.5*(1+Sr*Ur+qr*Lr+e*r)))),o=n*X,h=a*X,(er=cf)[0]=i=l*(u=er[0])-f*(s=er[1])-o*(w=er[2])-h*(c=er[3]),er[1]=g=l*s+f*u+o*c-h*w,er[2]=y=l*w-f*c+o*u+h*s,er[3]=A=l*c+f*w-o*s+h*u,b=i*(R=2*g),
v=R*g,d=R*y,k=R*A,M=i*(R=2*y),m=R*y,p=R*A,I=i*(R=2*A),E=1-(m+(F=R*A)),T=d-I,C=k+M,N=d+I,S=1-(v+F),q=p-b,U=k-M,L=p+b,x=1-(v+m),j=(cl-pl)*of,tr=Ff,nr=Ef,ar=Tf,lr=lf,Z=Ga,Hr=fr=0;0<=--Z;)Rr(Z,E*(t=Cf[Z])+T*(n=Nf[Z])+C*(a=Sf[Z]),N*t+S*n+q*a,j*(ar[Z]=(U*t+L*n+x*a)*lr),lr,tr,nr);if(0==++Ql)for(Z=Da;0<=--Z;)eo[Z]=0;for(Ar=++Ql,Zl&&(rf||xr(),ir=ke[jl][Te[jl]]),($=Kl&Zl)&&(gr=((yr=ho[ir])+1)*Za),rr=Kl|Zl,Z=hr=12,ur=fo;0<=--Z;)ur[Z]=-1;for(sr=ao,wr=jf,cr=Kf,br=za-Za,Z=Kl||!Zl?Za:ir+1;0<=--Z;)if(K=1+(J=1+(
H=3*Z)),cr[Z]=(Q=(D=tr[J]-(_=tr[H]))*(z=nr[K]-(P=nr[H]))-(Y=tr[K]-_)*(G=nr[J]-P))<=0?2:1,rr){if($&&3!=(Ir=io[--gr>>4]>>((15&gr)<<1)&3)&&(ur[(Mr=ur[(Ir+=3*(cr[Z]-1))+6])<0?Ir:Mr+1]=hr,ur[ur[Ir+6]=hr++]=Z+br,ur[hr++]=-1),!Zl||Z==ir){for(dr=0<Q?sr:lo,kr=0<Q?fr:Hr,Ir=(vr=Gf[Z]).length,or=~~(191.99*Math.abs(Q)/pa(G*(W=ar[K]-(B=ar[H]))-z*(O=ar[J]-B),O*Y-W*D,Q));0<=--Ir;)$f[Mr=vr[Ir]]=or,Zl||(dr[kr++]=Mr);if(0<Q?fr=kr:Hr=kr,!Kl){fr=1;break}}}else for(Ir=(vr=Df[Z]).length,or=-1;0<=--Ir;)if(!(
wr[Mr=vr[Ir]]=(R=Q*Zf[Mr])<=0))for(or<0&&(or=~~(191.99*R/pa(G*(W=ar[K]-(B=ar[H]))-z*(O=ar[J]-B),O*Y-W*D,Q))),$f[Mr]=or,mr=(dr=Pf[Mr]).length;0<=--mr;)eo[dr[mr]]=Ar;if($)for(hr=2,or=6-cr[no[yr]],yr<<=1;0<=--hr;or=9-or){for(fr=Vr(or,1073741824,Jr=fr),0==hr&&(fr=Vr(3,1073741824,fr)),ha(vr=Of[yr+(1&or)],0,sr,Z=fr,vr.length),mr=(fr+=vr.length)-1;Z<=mr;)1==cr[Jf[(268435455&(gr=sr[Z]))-rl]]?(gr=sr[Z],sr[Z]=sr[mr],sr[mr--]=gr):sr[Z++]|=1073741824;fr=Vr(or-3,0,fr),0==hr&&(fr=Vr(0,0,fr))}for(pr=Mf,Fr=If,
Z=!Kl||Zl?Da:Ya,V=j*lr;0<=--Z;)!rr&&eo[Z]!=Ar||(Rr(Z,E*(t=df[Z])+T*(n=kf[Z])+C*(a=mf[Z]),N*t+S*n+q*a,V*(U*t+L*n+x*a),lr,pr,Fr),Wf[0][Z]=~~(gf+pr[Z]),Wf[1][Z]=~~(yf-Fr[Z]));if(rr)jr=fr;else for(Er=Bf,Tr=oo,Z=or=gr=0;;)if(Cr=Er[Z],0==or&&0<=Cr[or=cr[no[yr=Cr[0]]]])Tr[gr++]=or<<24|Z,Z=Cr[or],or=0;else{for(Ir=2;++Ir<Cr.length;)wr[yr=Cr[Ir]]||(sr[fr++]=yr);if(0<=Cr[3-or])Z=Cr[3-or],or=0;else{if(0==gr)return void(jr=fr);or=(Z=Tr[--gr])>>24,Z&=16777215}}}function Rr(r,e,t,n,a,l,f){
var o=42535295865117303e21,h=-42535295865117303e21;n=n<1?a/(1-n):Number.POSITIVE_INFINITY,f[r]=0!=t?t*n:0,isFinite(l[r]=0!=e?e*n:0)&&isFinite(f[r])||(Math.abs(e)>=Math.abs(t)?f[r]=(l[r]=0<e?o:h)*(t/e):l[r]=(f[r]=0<t?o:h)*(e/t))}function Vr(r,e,t){for(var n=fo[r];0<=n;n=fo[n+1])ao[t++]=fo[n]|e;return t}function k(r){To.fillText(r,fl,U)}function m(r){k(r),U+=L}function p(r,e,t){for(var n=e,a=1;0<=--n;)r[n]>a&&(a=r[n]);return(4+~~Math.log10(a))*t}function F(r,e){m("Center: ("+(r[0]+e[0])+", "+(
r[1]+e[1])+", "+(r[2]+e[2])+")")}function E(r,e,t,n,a){for(var l=r.length;0<=--l;)e[l]=n[r[l]],t[l]=a[r[l]]}function T(r,e,t){var n;for(To.beginPath(),To.moveTo(r[0],e[0]),n=0;++n<t;)To.lineTo(r[n],e[n]);To.stroke()}function C(r,e,t){var n;for(To.beginPath(),To.moveTo(r[0],e[0]),n=0;++n<t;)To.lineTo(r[n],e[n]);To.closePath(),To.stroke()}function N(r,e,t){var n;for(To.beginPath(),To.moveTo(r[0],e[0]),n=0;++n<t;)To.lineTo(r[n],e[n]);To.fill()}function S(r,e,t,n,a){var l,f,o,h,i,g;To.beginPath(),
To.moveTo(l=r+a,e),To.quadraticCurveTo(r,e,r,h=e+a),To.lineTo(r,g=(i=e+n)-a),To.quadraticCurveTo(r,i,l,i),To.lineTo(o=(f=r+t)-a,i),To.quadraticCurveTo(f,i,f,g),To.lineTo(f,h),To.quadraticCurveTo(f,e,o,e),To.lineTo(l,e),To.fill()}function Ra(){var r,e,t,n,a,l,f,o,h,i,g,y,A,u,s,w,c,b,M,I;if(To.fillStyle=so,To.fillRect(0,0,Va,Xa),$l){if(rf||(Kn.style.cursor="wait",xr(),Kn.style.cursor="all-scroll"),U=ol+(L=hl>>5),To.fillStyle="black",To.font=_d[L-5],r=~~(To.measureText("m").width+.5),m(
"----- EMPIRICALLY GENERATED DATA -----"),U+=L,m("Faces: "+Za+"  Edges: "+Wa+"  Vertices: "+Oa),U+=L,m("Euler Characteristic:"),m("Rotation Symmetries:"),m("Mirror Rotation Symmetries:"),m("Rotation Axes:"),m("Mirror Planes:"),m("Invertible:"),m("Symmetry Classification:"),m("Orientable Surface:"),m("Connected Components:"),m("Topologically Self-Dual:"),m("Canonical:"),U-=11*L,fl+=28*r,m(nf?"(not a closed 2-manifold)":Qr),m(le),m(ae),e=""+ee,0<ee){for(e+=" (",t=-2;(t+=2)<6&&0<(n=G[t]);)e+=(
0<t?" + ":"")+G[t+1]+"["+n+"]";e+=")"}for(m(e),m(te),m(fe?"yes":"no"),m(qe+" ("+Se+")"),m(tf?"no":ef?"yes but "+Ja+(1==Ja?" face is reversed":" faces are reversed"):"yes"),m(Wr),m(oe?"yes":"no"),m(ye?"yes (sphere radius "+se+")":"no"),fl-=28*r,U+=L,m("Sphere Touching All Vertices:"),fl+=r<<2,he?(F(we,bf),m("Radius: "+Ae)):m("None"),fl-=r<<2,m("Sphere Tangent to (and below) All Face Planes:"),fl+=r<<2,ie?(F(ce,bf),m("Radius: "+ue)):m("None"),fl-=r<<2,m("Sphere Tangent to All Edges:"),fl+=r<<2,
ge?(F(be,bf),m("Radius: "+se)):m("None"),fl-=r<<2,U+=L,m("Volume = "+uf+" ("+Ka+(1==Ka?" interior chamber)":" interior chambers)")),U+=L,m("Edge Dihedral Angles:"),a=p(pe,Zr,r),t=-1;++t<Zr;)k("("+pe[t]+")"),fl+=a,m("D"+(t+1)+" = "+Ie[t]+" degrees"),fl-=a;for(U+=L,m("Edge Lengths:"),a=p(me,Kr,r),t=-1;++t<Kr;)k("("+me[t]+")"),fl+=a,m("E"+(t+1)+" = "+Me[t]),fl-=a;for(U+=L,m("Face Vertex Angles:"),a=p(Fe,$r,r),t=-1;++t<$r;)k("("+Fe[t]+")"),fl+=a,m("A"+(t+1)+" = "+ve[t]+" degrees"),fl-=a;for(U+=L,m(
"Face Types:"),a=p(Ee,re,r),t=0;t<re;t++){for(l=de[t],k("("+Ee[t]+")"),fl+=a,m("F"+(t+1)+" = "+Ue[t]),n=-1,e="sides: {";++n<l.length;)e+=" E"+(1+(l[n]>>>16));for(n=-1,e+=" } angles: {";++n<l.length;)e+=" A"+(1+(65535&l[n]));m(e+=" }"),fl-=a}for(U+=L,m("Center of Mass:"),m("("+bf[0]+", "+bf[1]+", "+bf[2]+")"),U+=L,m("Principal Moments and Axes of Inertia:"),t=0;t<3;t++)m("MOMENT: "+(f=sf[t])[3]),m("AXIS: ("+f[0]+", "+f[1]+", "+f[2]+")");(q=Xa+ol-U)>ll&&(q=ll),To.fillRect(Sl,Tl,Nl,Nl),To.font=Fo
}else{if(o=Yf[0],h=Yf[1],i=Wf[0],g=Wf[1],Zl)for(n=0;n<jr;n++){if(!Kl||n==Jr)for(y=(A=Gf[ke[jl][Te[jl]]]).length;0<=--y;)E(l=Rf[$a+(t=A[y])],o,h,i,g),To.fillStyle=Ao[t][255&$f[t]],N(o,h,l.length),Kl||(To.strokeStyle=wo,C(o,h,l.length));if(Kl)if(y=268435455&(t=ao[n]),To.strokeStyle=1073741824<=t?bo:co,$a<=y)E(l=Rf[y],o,h,i,g),C(o,h,l.length);else for(s=(u=qf[y]).length;0<=--s;)E(l=u[s],o,h,i,g),T(o,h,l.length)}else if(Kl)for(w=Hr,c=lo,b=bo;;){for(n=0;n<w;n++)E(l=xf[t=c[n]],o,h,i,g),
To.fillStyle=uo[t][255&$f[t]],N(o,h,l.length),To.strokeStyle=b,C(o,h,l.length);if(c==ao)break;w=jr,c=ao,b=co}else for(n=0;n<jr;n++)for(E(l=Rf[t=ao[n]],o,h,i,g),To.fillStyle=To.strokeStyle=yo[t][255&$f[t]],N(o,h,l.length),M=Uf;;){if(null==M[t])C(o,h,l.length);else for(s=(u=M[t]).length;0<=--s;)E(A=u[s],o,h,i,g),T(o,h,A.length);if(M==qf)break;To.strokeStyle=wo,M=qf}To.fillStyle="lightGray",S(il,t=yl,ul,sl,n=dl),To.strokeStyle=so,To.beginPath(),To.moveTo(wl,t),To.lineTo(wl,Al),To.closePath(),
To.stroke(),To.fillStyle="#505050",S(cl,bl,Il,vl,n),Kl||(To.fillStyle=_b[4][64],To.fillRect(Fl,Tl,Nl,Nl)),To.strokeStyle=To.fillStyle="black",To.strokeRect(Fl,Tl,Nl,Nl),0<(t=Ha)&&(To.font=~~(Va/20)+"px Courier New",To.fillText("WARNING: "+t+(1==t?" face is non-planar":" faces are non-planar"),0,63*Xa>>6)),To.strokeRect(Sl,Tl,Nl,Nl),Zl?(To.fillRect(Fl,Ul,Nl,Nl),To.font=Eo,I=Ue[jl],To.fillText(I,Va-zl*I.length>>1,Rl-Wl),To.fillText(t=jl+1,Bl-(zl*~~Math.log10(t)>>1),Rl-Wl),To.fillText(t=Te[jl]+1,
Dl-(zl*~~Math.log10(t)>>1),Rl-Wl),To.fillText("face type",Bl-(9*zl>>1),xl-Wl),To.fillText("occurrence",Dl-(9*zl>>1),xl-Wl),To.strokeStyle=vo,To.strokeRect(Vl,xl,Pl,Gl),To.fillStyle=Mo,N(zf[0],zf[1],3),To.fillStyle=Io,N(zf[2],zf[3],3),To.strokeStyle=po,To.strokeRect(Xl,xl,Pl,Gl),To.fillStyle=ko,N(zf[4],zf[5],3),To.fillStyle=mo,N(zf[6],zf[7],3),To.fillStyle="lightGray"):To.strokeRect(Fl,Ul,Nl,Nl),To.font=Fo,To.fillText("F",Fl+Ol,Ll-Yl)}To.fillStyle=$l?"lightGray":"black",To.fillText("M",Sl+Ol,
Cl-Yl)}var Va,Xa,Pa,Ba,Da,Ga,Oa,Ya,za,Wa,Qa,ja,Wr,Qr,Ha,Ja,Ka,Za,$a,rl,g,el,tl,nl,al,ll,q,fl,ol,U,A,u,hl,L,il,gl,yl,Al,ul,sl,wl,cl,bl,Ml,Il,vl,dl,kl,ml,pl,s,Fl,El,Tl,Cl,Nl,Sl,ql,Ul,Ll,xl,Rl,Vl,Xl,Pl,Bl,Dl,Gl,Ol,Yl,zl,Wl,jr,Hr,Jr,Ql,Kr,Zr,$r,re,ee,te,ne,ae,le,jl,w,Hl,Jl,Kl,Zl,$l,rf,fe,oe,he,ie,ge,ye,ef,tf,nf,af,lf,ff,of,hf,gf,yf,Af,uf,Ae,ue,se,sf,wf,cf,bf,we,ce,be,Mf,If,vf,df,kf,mf,pf,Ff,Ef,Tf,Cf,Nf,Sf,Me,Ie,ve,qf,Uf,Lf,xf,Rf,de,ke,Vf,Xf,Pf,Bf,Df,Gf,Of,Yf,zf,Wf,Qf,jf,Hf,Jf,Kf,Zf,$f,ro,G,eo,to,no,
ao,lo,fo,oo,ho,io,go,me,pe,Fe,Ee,Te,Ce,Ne,Se,qe,Ue,yo,Ao,uo,so,wo,co,bo,Mo,Io,vo,ko,mo,po,Fo,Eo,To;_p[_p.length]=(To=Kn.getContext("2d"),void function(){var r,e,t,n,a,l,f,o,h,i,g,y,A,u,s,w,c,b,M,I,v,d,k,m,p,F,E,T,C,N,S,q,U,L,x,R,V,X,_,P,B,D,G,O,Y,z,W,Q,j,H,J,K,Z,$,rr,er,tr,nr,ar,lr,fr,or,hr,ir,gr,yr,Ar,ur,sr,wr,cr,br,Mr,Ir,vr,dr,kr,mr,pr,Fr,Er,Tr,Cr,Nr,Sr,qr,Ur,Lr,xr,Rr,Vr,Xr,Pr,Br,Dr,Gr,Or,Yr,zr,Wr,Qr,jr,Hr,Jr,Kr,Zr,$r,re,ee,te,ne,ae,le,fe,oe,he,ie,ge,ye,Ae,ue,se,we,ce,be,Me,Ie,ve,de,ke,me,pe,
Fe,Ee,Te,Ce,Ne,Se,qe,Ue,Le,xe,Re,Ve,Xe,Pe,Be,De,Ge,Oe,Ye,ze,We,Qe,je,He,Je,Ke,Ze,$e,rt,et,tt,nt,at,lt,ft,ot,ht,it,gt,yt,At,ut,st,wt,ct,bt,Mt,It,vt,dt,kt,mt,pt,Ft,Et,Tt,Ct,Nt,St,qt,Ut,Lt,xt,Rt,Vt,Xt,_t,Pt,Bt,Dt,Gt,Ot,Yt,zt,Wt,Qt,jt,Ht,Jt,Kt,Zt,$t,rn,en,tn,nn,an,ln,fn,on,hn,gn,yn,An,un,sn,wn,cn,bn,Mn,In,vn,dn,kn,mn,pn,Fn,En,Tn,Cn,Nn,Sn,qn,Un,Ln,xn,Rn,Vn,Xn,Pn,Bn,Dn,Gn=5820766091346741e-26,On=33881317890172014e-37,Yn=2.3283064365386963e-10,zn=1.4629180792671596e-9,Wn=6.283185307179586,
Qn=-3.141592653589793,jn=5.960464477539063e-8,Hn=3019169939857233e154;for(el=nl=Pa=(Nr=Va=Kn.width)>>1,tl=al=Ba=(Sr=Xa=Kn.height)>>1,so=(qr=Jn.getElementsByClassName("Background")).length?qr[0].value:"#606060",wo=(qr=Jn.getElementsByClassName("EdgeColor")).length?qr[0].value:"black",co=(qr=Jn.getElementsByClassName("WireColor")).length?qr[0].value:"black",To.fillStyle=so,To.fillRect(0,0,Nr,Sr),Mo=Io=vo=ko=mo=po="black",Ml=(Al=(yl=rr=Sr>>6)+(sl=er=Sr<256?8:Sr>>5))-1,bl=rr+1,dl=er>>1,cl=(pl=tr=(
3*(_=(ml=(gl=(il=Nr>>2)+(ul=Nr>>1))-(Il=vl=er-2)-1)-(kl=il+1))>>2)+kl)+(_>>4),wl=tr+(Il>>1),of=(Af=.5/(gf=Nr>>1))/(V=3*(ml-tr)>>3),(qr=Jn.getElementsByClassName("Perspective")).length&&((cl=tr+~~(parseFloat(qr[0].value)*V))>ml&&(cl=ml),cl<kl&&(cl=kl)),El=(Fl=fl=Nr>>6)+(Nl=fr=er<<1),Cl=ol=ll=(Tl=rr)+fr,Sl=(ql=Nr-Fl)-fr,To.font=Fo=fr+"px Verdana",Ol=Yl=fr-~~(To.measureText("M").width+.5)+1>>1,hl=384,To.font=Eo=~~((fr<<1)/5)+"px Courier New",Wl=er-(zl=tr=~~(To.measureText("M").width+.5))>>1,
zf=Array(or=8);0<=--or;)zf[or]=new Uint32Array(3);for((dr=zf[2])[0]=(dr[1]=dr[2]=(Vl=((vr=zf[0])[1]=vr[2]=(vr[0]=El+(Gl=er))+er)+2)+(Pl=6*tr)+2)+er,(cr=zf[4])[0]=(cr[1]=cr[2]=(Xl=((pr=zf[6])[1]=pr[2]=(pr[0]=Sl-er)-er)-2-Pl)-2)-er,xl=(br=zf[1])[2]=(Mr=zf[3])[1]=(Ir=zf[5])[2]=(kr=zf[7])[1]=(Ll=Rl=br[1]=Mr[2]=Ir[1]=kr[2]=Sr-rr)-er,Ul=Ll-fr,Bl=Vl+(or=Pl-tr>>1),Dl=Xl+or,br[0]=Ir[0]=br[1]+br[2]>>1,Mr[0]=kr[0]=Mr[1]+Mr[2]>>1,ro=new Int8Array(or=er*Nr);0<=(or-=Nr);){for(rr=or+vr[1],tr=or+vr[0];--rr>=tr;
)ro[rr]=1;for(rr=or+Vl+Pl,tr=or+Vl;--rr>=tr;)ro[rr]=2;for(rr=or+dr[0],tr=or+dr[1];--rr>=tr;)ro[rr]=3;for(rr=or+cr[1],tr=or+cr[0];--rr>=tr;)ro[rr]=4;for(rr=or+Xl+Pl,tr=or+Xl;--rr>=tr;)ro[rr]=5;for(rr=or+pr[0],tr=or+pr[1];--rr>=tr;)ro[rr]=6}if((Ur=cf=new Float64Array(4))[0]=1,(qr=Jn.getElementsByClassName("Quaternion")).length){for(e=qr[0].value.match(/[^ \t\n\r\f,;]+/g),rr=-1,V=0;++rr<4;)V+=(Ur[rr]=parseFloat(e[rr]))*Ur[rr];for(0==V&&(Ur[0]=V=1,Ur[1]=Ur[2]=Ur[3]=0),rr=4,V=Math.sqrt(V);0<=--rr;
)Ur[rr]/=V}for(e=Jn.getElementsByClassName("Counts")[0].value.match(/[^ \t\n\r\f,;]+/g),X=parseInt(e[0],10),xr=Lr=Oa=parseInt(e[1],10),Xr=Lf=Array(Vr=Rr=Za=parseInt(e[2],10)),sf=Array(rr=3);0<=--rr;)sf[rr]=new Float64Array(4);if(Hf=new Uint8Array(Rr),Br=Df=Array((Pr=new Int32Array(Vr)).length),Or=Sf=new Float64Array((Gr=Nf=new Float64Array((Dr=Cf=new Float64Array((Tf=new Float64Array((Ef=new Float64Array((Ff=new Float64Array(3*Rr)).length)).length)).length)).length)).length),fo=new Int32Array(
12+(Kf=new Int8Array((go=new Int32Array((Gf=Array(Rr)).length)).length)).length<<1),Yr=new Float64Array(X),pf=new Float64Array((vf=new Float64Array(Lr)).length),0<X)for(e=Jn.getElementsByClassName("Constants")[0].value.match(/[^ \t\n\r\f,;]+/g),rr=-1;++rr<X;)Yr[rr]=parseFloat(e[rr]);for(Qr=mf=new Float64Array((Wr=kf=new Float64Array((zr=df=new Float64Array((If=new Float64Array((Mf=new Float64Array(xr)).length)).length)).length)).length),e=Jn.getElementsByClassName("Vertices")[0].value.match(
/[^ \t\n\r\f,;]+/g),jr=0,ir=rr=-1;++ir<xr;)(V=ma(zr[ir]=Fa(e[++rr],Yr),Wr[ir]=Fa(e[++rr],Yr),Qr[ir]=Fa(e[++rr],Yr)))>jr&&(jr=V);for(jr=Math.sqrt(jr),hf=jr*Gn,Yr=null,Hr=Vf=Array(Rr),Jr=Xf=Array(Lr),b=da(zr,xr),M=da(Wr,xr),I=da(Qr,xr),ir=-1;++ir<xr;)Mf[ir]=zr[ir]-=b,If[ir]=Wr[ir]-=M,vf[ir]=Qr[ir]-=I;for(Kr=new Int32Array((kr=new Int32Array(xr)).length),ne=Array((Zr=Array(512)).length),$r=Array(rr=3);0<=--rr;)$r[rr]=Array(ne.length);for(rr=Vr+511>>9,re=$r[0],ee=$r[1],te=$r[2];0<=--rr;
)te[rr]=new Int16Array((ee[rr]=new Int16Array((re[rr]=new Int16Array((ne[rr]=new Int8Array((Zr[rr]=Array(512)).length)).length)).length)).length);for(ae=Array((Er=new Int32Array(Vr)).length),rr=Vr;0<=--rr;)ae[rr]=new Float64Array(4);for(e=Jn.getElementsByClassName("Faces")[0].value.match(/[^ \t\n\r\f,;]+/g),Fr=new Int32Array(D=0),fe=le=0,rr=ir=-1;++rr<Rr;){for(tr=0;"#"!=(r=e[++ir]).charAt(0);)Kr[kr[tr++]=parseInt(r,10)]++;if(fe+=tr,Hr[rr]=new Int32Array(tr),Er[rr]=-tr,ha(kr,0,
Xr[rr]=new Int32Array(tr),0,tr),ha(kr,0,Zr[nr=rr>>9][or=511&rr]=new Int32Array(tr),0,tr),le<tr&&(le=tr),1<r.length){for(er=16777215&parseInt(r.substring(1),16),lr=D;0<=--lr&&Fr[lr]!=er;);lr<0&&(Fr=ga(Fr,lr=D++,er,32)),Er[rr]=lr}re[nr][or]=rr}for(Qf=Array(rr=4);0<=--rr;)Qf[rr]=new Int32Array(fe);for(oe=Array(rr=Lr),ja=0;0<=--rr;)for(oe[rr]=new Int32Array(er=Kr[rr]),ja<er&&(ja=er),Jr[rr]=kr=new Int32Array(er<<=1);0<=--er;)kr[er]=-1;for(rr=Rr;0<=--rr;)for(er=(kr=Xr[rr]).length;0<=--er;
)oe[tr=kr[er]][--Kr[tr]]=er<<18|rr;for(rr=Lr,ef=nf=!1;0<=--rr;)if(0<(kr=oe[rr]).length)for(ie=(he=Xr[262143&(tr=kr[or=0])]).length-1,tr>>>=18;or<kr.length-1;){for(hr=he[(tr+ie)%he.length],er=++or;er<kr.length;er++)if(lr=(he=Xr[262143&(tr=kr[er])]).length-1,(ge=he[((tr>>>=18)+1)%he.length]==hr)||he[(tr+lr)%he.length]==hr){(ge?1==ie:1<ie)&&(ef=!0),ie=ge?lr:1;break}er>=kr.length?(nf=!0,ie=(he=Xr[262143&(tr=kr[or])]).length-1,tr>>>=18):er!=or&&(fr=kr[or],kr[or]=kr[er],kr[er]=fr)}for(rr=Rr,
ye=Qf[fe=0],Ae=Qf[1],ue=Qf[2],se=Qf[3];0<=--rr;)for(er=(kr=Xr[rr]).length,ce=kr[0],we=Hr[rr];0<=--er;){for(lr=ce+(be=kr[er])-(nr=ce<be?ce:be),tr=0,he=Jr[ce];0<=(or=he[tr])&&(ye[or]!=nr||Ae[or]!=lr);tr++);or<0?(ye[he[Kr[ce]++]=Jr[be][Kr[be]++]=or=fe++]=nr,Ae[or]=lr,ue[or]=se[or]=rr):(se[or]!=ue[or]&&(nf=!0),ue[or]+=rr-(se[or]=rr<(tr=ue[or])?tr:rr)),we[er]=or,ce=be}for(rr=Lr;0<=--rr;)if(Jr[rr]=he=Aa(Jr[rr],Kr[rr]),0<(kr=oe[rr]).length)if(1==kr.length)nf=!0;else for(er=1,Me=262143&kr[ar=0];;){for(
lr=Me+(Ie=262143&kr[er])-(nr=Me<Ie?Me:Ie),tr=ar;tr<he.length&&(ue[or=he[tr]]!=nr||se[or]!=lr);tr++);if(tr<he.length?(he[tr]=he[ar],he[ar++]=or):nf=!0,ar>=he.length||1==(er=(er+1)%kr.length))break;Me=Ie}if(oe=null,!(tf=nf)&&ef){r:for(ke=new Uint8Array((de=new Uint8Array((ve=new Int32Array(rr=Rr)).length)).length),$=0;0<=--rr;)if(!de[rr])for(de[ve[tr=0]=rr]=!0,er=1;tr<er;tr++)for(nr=(he=Hr[ar=ve[tr]]).length,kr=Xr[ar],me=ke[ar];0<=--nr;){for(fr=(pe=Hr[lr=ue[or=he[nr]]+se[or]-ar]).length,
we=Xr[lr];0<=--fr&&pe[fr]!=or;);if(Fe=me!=(kr[nr]==we[fr]),de[lr]){if(ke[lr]!=Fe){tf=!0;break r}}else de[ve[er++]=lr]=!0,(ke[lr]=Fe)&&$++}tf||(Ja=$<(rr=Rr-$)?$:rr)}for(bo=tf?co:"#888888",Qf[2]=Aa(ue,fe),Qf[3]=Aa(se,Wa=Ee=fe),er=1,s=w=c=h=i=g=0,l=Number.MAX_VALUE,Te=new Float64Array(3);!(ef|nf);){if(va(Mf,If,vf,Te,null),(V=ma(Te[0],Te[1],Te[2]))<l){if(h=s,i=w,g=c,0==(l=V))break;er=1}else if(h+=s,i+=w,g+=c,4<=++er){h*=.25,i*=.25,g*=.25;break}for(ir=-1,s+=Te[0],w+=Te[1],c+=Te[2];++ir<xr;
)Mf[ir]=zr[ir]-s,If[ir]=Wr[ir]-w,vf[ir]=Qr[ir]-c}for(Math.abs(h)<ka(zr,xr)*Gn&&(h=0),Math.abs(i)<ka(Wr,xr)*Gn&&(i=0),Math.abs(g)<ka(Qr,xr)*Gn&&(g=0),ir=-1,Ne=Ce=zr[0],jr=0,(bf=new Float64Array(3))[0]=b+h,bf[1]=M+i,bf[2]=I+g;++ir<xr;)(pf[ir]=V=pa(Se=zr[ir]-=h,Wr[ir]-=i,Qr[ir]-=g))>jr&&(jr=V),Se<Ce&&(Ce=Se),Ne<Se&&(Ne=Se);for(1==(qe=new Int32Array(isFinite(Se=4095.99/(Ne-Ce))?4096:1)).length&&(Se=0),rr=qe.length;0<=--rr;)qe[rr]=-1;if(lf=gf*((qr=Jn.getElementsByClassName("Scale")
).length?.75*parseFloat(qr[0].value):.75)/jr,ff=1/gf,gf+=.5,yf=.5+(Sr>>1),Ue=(hf=(af=jr)*Gn)*hf,va(zr,Wr,Qr,Te,sf),Tr=Cr=Te=null,0!=D)for(Cr=Array((Tr=Array(rr=D)).length);0<=--rr;)for(Cr[rr]=Array(192),Tr[rr]=Array(192),er=192,he=Tr[rr],we=Cr[rr],xe=(Le=Fr[rr])>>8&255,Re=255&Le,Le>>=16;0<=--er;)he[er]="rgb("+~~((Le*(tr=er+64)+127)/255)+","+~~((xe*tr+127)/255)+","+~~((Re*tr+127)/255)+")",we[er]="rgba"+he[er].slice(3,-1)+",.125)";for(ir=-1,Da=tr=0,Ve=Array((Xe=Array(1024)).length);++ir<xr;)(
Kr[ir]=ca(Ve,t=zr[ir],n=Wr[ir],a=Qr[ir],Ue,Ce,Se,qe,Xe))!=ir&&(Da++,tr=1,(ur=Ve[rr=ir>>7]=null==Ve[rr]?new Float64Array(640):Ve[rr])[er=127&ir]=t,ur[er+128]=n,ur[er+256]=a);if(0!=tr)for(rr=Vr;0<=--rr;)for(er=(kr=Zr[rr>>9][511&rr]).length;0<=--er;)for(;(kr[er]=Kr[ar=kr[er]])!=ar;);for(Ar=new Float64Array((yr=new Float64Array((cr=new Int32Array(G=le)).length)).length),rr=Ga=Ha=Z=Y=z=Q=j=0,Fr=null,Da=xr;rr<Rr;rr++){for(er=(kr=Zr[or=rr>>9][ar=511&rr]).length,s=w=c=0,l=(ur=Ve[(ir=kr[1])>>7])[ir&=127]
,f=ur[ir+128],o=ur[ir+256],h=(ur=Ve[(ir=kr[0])>>7])[ir&=127],i=ur[ir+128],g=ur[ir+256];s+=(tr=(t=(f-i)*((u=(ur=Ve[(ir=kr[--er])>>7])[256+(ir&=127)])-g)-(o-g)*((A=ur[ir+128])-i))*s+(n=(o-g)*((y=ur[ir])-h)-(l-h)*(u-g))*w+(a=(l-h)*(A-i)-(f-i)*(y-h))*c<0?-1:1)*t,w+=tr*n,c+=tr*a,!(er<=0);)l=h,f=i,o=g,h=y,i=A,g=u;for(0==(V=pa(s,w,c))&&0==(V=pa(s*=Hn,w*=Hn,c*=Hn))&&(V=c=1),s/=V,w/=V,c/=V,tr=-1,te[or][ar]=rr;++tr<rr&&ma(w*(a=(we=ae[Pr[tr]])[2])-(n=we[1])*c,c*(t=we[0])-a*s,s*n-t*w)>On;);for(Pe=0,
te[or][ar]=te[tr>>9][511&tr];;){for(h=(1-(g=-s)*g/(V=1+c*(Be=c<0?-1:1)))*Be,A=1-(u=-w*Be)*u/V,y=(i=s*u/V)*Be,er=kr.length,l=(ur=Ve[(ir=kr[0])>>7])[ir&=127],f=ur[ir+128],o=ur[ir+256];0<=--er;)yr[er]=(ur=Ve[(ir=kr[er])>>7])[384+(ir&=127)]=h*(t=ur[ir]-l)+i*(n=ur[ir+128]-f)+g*(a=ur[ir+256]-o),Ar[er]=ur[ir+512]=y*t+A*n+u*a;if(0!=Pe)break;for(er=kr.length,Pe=0,k=yr[1]-(t=yr[0]),m=Ar[1]-(n=Ar[0]);0<=--er;)Pe+=Math.atan2((v=t-(t=yr[er]))*m-(d=n-(n=Ar[er]))*k,v*k+d*m),k=v,m=d;if(0<=Pe)break;s=-s,w=-w,
c=-c}for(V=-(l*s+f*w+o*c);tr<rr&&(Math.abs(V-(we=ae[Pr[tr]])[3])>hf||ma(s-we[0],w-we[1],c-we[2])>On);tr++);if((we=ae[Pr[rr]=tr==rr?Z++:Pr[tr]])[0]=s,we[1]=w,we[2]=c,we[3]=V,Ma(t=l+h*(p=function(r,e,t,n,a,l){var f,o,h,i,g,y,A,u,s,w,c,b,M,I;r:for(f=t;;)for(M=.5*((o=r[n])+r[a]),I=.5*((h=e[n])+e[a]),g=l,i=(o-=M)*o+(h-=I)*h;;){for(;g<t;g++)if((o=r[g]-M)*o+(h=e[g]-I)*h>i){if(0!=l){a=n,t=n=g,l--;continue r}M=(M=r[n])+(c=((A=e[g]-(I=e[n]))*(u=(o=r[a]-M)*o+(h=e[a]-I)*h)-h*(s=(y=r[g]-M)*y+A*A))*(w=.5/(
o*A-h*y))),I+=b=(o*s-y*u)*w,i=c*c+b*b}if(2==l)return e[0]=I,M;g=t+1,t=0==l?a:f,n=a,a=l++}}(yr,Ar,kr.length,0,1,2))+y*(F=Ar[0]),n=f+i*p+A*F,a=o+g*p+u*F),Ma(t+(V=jr*jn)*h,n+V*i,a+V*g),Ma(t+V*y,n+V*A,a+V*u),K=0,2<(er=kr.length-1)){r:for(;0<=(tr=er--);)for(l=(ur=Ve[(ir=kr[tr])>>7])[ir&=127],f=ur[ir+128],o=ur[ir+256];0<=--tr;)if(Math.abs((s*((ur=Ve[(ir=kr[tr])>>7])[hr=127&ir]-l)+w*(ur[hr+128]-f)+c*(ur[hr+256]-o))/pf[ir])>Yn){Ha++;break r}for(er=kr.length,v=(ur=Ve[(ir=kr[$=0])>>7])[384+(ir&=127)],
d=ur[ir+512],nr=1;1<--er;$=er,nr=0){for(x=(k=(ur=Ve[(ir=kr[er])>>7])[384+(ir&=127)])-v,R=(m=ur[ir+512])-d,p=(ur=Ve[(ir=kr[tr=er-1])>>7])[384+(ir&=127)],F=ur[ir+512];nr<tr;tr--){if(S=(E=(ur=Ve[(ir=kr[tr-1])>>7])[384+(ir&=127)])-p,q=(T=ur[ir+512])-F,Math.abs(V=q*x-S*R)>hf&&0<=(De=(S*(L=d-F)-q*(U=v-p))/V)&&De<=1&&0<=(Ge=(x*L-R*U)/V)&&Ge<=1){if(0==K){if(0==Y&&(Ir=new Int32Array(Y=le<<1)),G<(ar=kr.length<<2)&&(Ar=new Float64Array((yr=new Float64Array((cr=new Int32Array(G=ar)).length)).length)),
z<kr.length)for(gr=Array((sr=Array((br=new Int32Array(ar=z=kr.length)).length)).length);0<=--ar;)gr[ar]=new Float64Array((sr[ar]=new Int32Array(z-3)).length);for(ar=O=kr.length;0<=--ar;)yr[ar]=(ur=Ve[(ir=cr[ar]=kr[ar])>>7])[384+(ir&=127)],Ar[ar]=ur[ir+512],br[ar]=0}for(ar=O,C=v+De*x,N=d+De*R;0<=--ar&&Math.hypot(yr[ar]-C,Ar[ar]-N)>hf;);K+=4,0<=ar&&ar<kr.length&&(K-=1+((C=yr[ar])==v&&(N=Ar[ar])==d||C==k&&N==m?1:0)+(C==p&&N==F||C==E&&N==T?1:0)),ar<0&&(G<=O&&(Oe=G,ia(yr,0,yr=new Float64Array(
G+=kr.length),0,Oe),ia(Ar,0,Ar=new Float64Array(G),0,Oe),ha(cr,0,cr=new Int32Array(G),0,Oe)),yr[ar=O++]=C,Ar[ar]=N,cr[ar]=ca(Ve,l+h*C+y*N,f+i*C+A*N,o+g*C+u*N,Ue,Ce,Se,qe,Xe),xr=Da),fa(br,sr[$],gr[$],$,er,ar,De),fa(br,sr[tr],gr[tr],tr,tr-1,ar,Ge)}p=E,F=T}v=k,d=m}}if(0!=(go[rr]=K>>=2)){if(Q<O)wr=Array((Mr=new Int32Array(Q=O)).length),j=0;else for(er=O;0<=--er;)Mr[er]=0;if(j<(ar=4294967294&kr.length))for(er=O,j=ar;0<=--er;)wr[er]=new Int32Array(ar);for(er=kr.length,tr=fr=0;0<=--er;tr=er){for(
ar=br[tr],he=sr[tr],lr=er;0<=--ar;)wr[wr[lr][Mr[lr]++]=nr=he[ar]][Mr[nr]++]=lr,lr=nr;wr[wr[lr][Mr[lr]++]=tr][Mr[tr]++]=lr}for(er=O;0<=--er;)for(;0<Mr[er];){for(Pe=Ye=0,x=(v=yr[tr=hr=wr[lr=er][Mr[lr]-1]])-yr[lr],R=(d=Ar[tr])-Ar[lr];;){for(nr=ie=--Mr[tr],he=wr[tr],ze=-Number.MAX_VALUE;0<=nr;nr--)(ar=he[nr])!=lr&&(S=yr[ar]-v,q=Ar[ar]-d,(We=Math.atan2(x*q-R*S,x*S+R*q))>ze&&(ze=We,$=nr,or=ar));if(he[$]=he[ie],Pe+=ze,Ir[Ye++]=cr[lr=tr],tr==er&&or==hr)break;x=-v+(v=yr[tr=or]),R=-d+(d=Ar[tr])}0<Pe&&(
null==Zr[nr=(tr=0==fr?rr:Vr++)>>9]&&(te[nr]=new Int16Array((ee[nr]=new Int16Array((re[nr]=new Int16Array((ne[nr]=new Int8Array((Zr[nr]=Array(512)).length)).length)).length)).length)),ha(Ir,0,Zr[nr][ar=511&tr]=0==fr&&Ye==kr.length?Zr[nr][ar]:new Int32Array(Ye),0,Ye),fr=1,te[nr][ar]=te[(or=re[nr][ar]=rr)>>9][511&or])}}}for(je=0,Qe=new Int32Array(rr=Z),kr=new Int32Array(Z);0<=--rr;){for(s=(we=ae[rr])[er=tr=0],w=we[1],c=we[2],V=we[3];tr<je;tr++)if(ma(s-(we=ae[Qe[tr]])[0],w-we[1],c-we[2])<=On){if(
Math.abs(V-we[3])<=hf)break}else if(ma(s+we[0],w+we[1],c+we[2])<=On){if(Math.abs(V+we[3])<=hf)break}else er++;(kr[rr]=tr)==je&&(Qe[je++]=rr,Ee+=er)}for(ho=new Int32Array(rr=Rr),no=new Int32Array(je);0<=--rr;)Qe[ho[rr]=er=kr[tr=Pr[rr]]]==tr&&(no[er]=rr);for(Ao=Array((Jf=new Int16Array(rr=Vr)).length),vr=new Int32Array(Za),He=Array((dr=new Int32Array(je)).length);0<=--rr;)vr[er=Jf[rr]=re[rr>>9][511&rr]]++,Ao[rr]=(tr=Er[er])<0?_b[31&-tr]:Tr[tr],dr[ho[er]]++;for(rr=Rr;0<=--rr;)Gf[rr]=new Int32Array(
vr[rr]);for(rr=je;0<=--rr;)He[rr]=new Int32Array(dr[rr]);for(uo=Array((xf=Array((lo=new Int32Array(rr=H=Vr)).length)).length),Je=Array(512);0<=--rr;)uo[Gf[er=re[nr=rr>>9][or=511&rr]][--vr[er]]=rr]=(tr=Er[er])<0?_c[31&-tr]:Cr[tr],He[er=ho[er]][--dr[er]]=rr,$n(kr=Zr[nr][or],Ve,(Je[nr]=null==Je[nr]?Array(512):Je[nr])[or]=new Float64Array(6)),ha(kr,0,xf[rr]=new Int32Array(kr.length),0,kr.length);for(vr=dr=null,Ya=xr,rr=je,W=z-3;0<=--rr;){for(Ke=Ze=0,kr=He[rr];Ke<kr.length;Ke++)for(rt=kr.length,tt=!0
,et=re[($e=kr[Ke])>>9][511&$e];--rt>Ke;)if(tt&&(tt=!1,t=(we=Je[$e>>9][511&$e])[0],b=we[1],n=we[2],M=we[3],a=we[4],I=we[5]),(ft=re[lt=(nt=kr[rt])>>9][at=511&nt])!=et&&b>(we=Je[lt][at])[0]&&t<we[1]&&M>we[2]&&n<we[3]&&I>we[4]&&a<we[5]){for(0==Ze++&&(V=1+(c=(we=ae[Qe[rr]])[2])*(Be=c<0?-1:1),h=(1-(g=-we[0])*g/V)*Be,A=1-(u=-we[1]*Be)*u/V,y=(i=-g*u/V)*Be),Zn(he=Zr[$e>>9][511&$e],Ve,l=Dr[ir=3*et],f=Gr[ir],o=Or[ir],h,i,g,y,A,u),Zn(pe=Zr[lt][at],Ve,l,f,o,h,i,g,y,A,u),er=he.length,v=(ur=Ve[(ir=he[K=0])>>7]
)[384+(ir&=127)],d=ur[ir+512];;){for(tr=pe.length,x=(k=(ur=Ve[(ir=he[--er])>>7])[384+(ir&=127)])-v,R=(m=ur[ir+512])-d,p=(ur=Ve[(ir=pe[0])>>7])[384+(ir&=127)],F=ur[ir+512];;){for(ht=ot=0,S=(E=(ur=Ve[(ir=pe[--tr])>>7])[384+(ir&=127)])-p,q=(T=ur[ir+512])-F;ht<4;ot++){if(0==ot){if((Ge=na(v,d,p,F,E,T))<0)continue;ht++,De=0}else if(1==ot){if((Ge=na(k,m,p,F,E,T))<0)continue;ht++,De=1}else if(2==ot){if((De=na(p,F,v,d,k,m))<0)continue;ht++,Ge=0}else if(3==ot){if((De=na(E,T,v,d,k,m))<0)continue;ht++,Ge=1
}else{if(0!=ht||Math.abs(V=q*x-S*R)<=hf||(De=(S*(L=d-F)-q*(U=v-p))/V)<0||1<De||(Ge=(x*L-R*U)/V)<0||1<Ge)break;ht=4}if(0==K){if(G<(ar=(fr=he.length+pe.length)<<1)&&(Ar=new Float64Array((yr=new Float64Array((cr=new Int32Array(G=ar)).length)).length)),Y<(ar=he.length+pe.length<<1)&&(Ir=new Int32Array(Y=ar)),z<fr&&(gr=Array((sr=Array((br=new Int32Array(z=fr)).length)).length),W=0),W<(fr=he.length>pe.length?he.length:pe.length))for(ar=z;0<=--ar;)gr[ar]=new Float64Array((sr[ar]=new Int32Array(W=fr)
).length);for(it=he,O=0;;){for(ar=-1;++ar<it.length;)yr[O]=(ur=Ve[(ir=cr[O]=it[ar])>>7])[384+(ir&=127)],Ar[O]=ur[ir+512],br[O++]=0;if(it==pe)break;it=pe}}for(ar=O,C=v+De*x,N=d+De*R,hr=ir=0;0<=--ar&&Math.hypot(yr[ar]-C,Ar[ar]-N)>hf;);K+=8,0<=ar&&ar<he.length+pe.length&&(N=Ar[ar],K-=1+(hr=(C=yr[ar])==v&&N==d||C==k&&N==m?3:0)+(ir=C==p&&N==F||C==E&&N==T?3:0)),ar<0&&(G<=O&&(Oe=G,ia(yr,0,yr=new Float64Array(G+=he.length+pe.length),0,Oe),ia(Ar,0,Ar=new Float64Array(G),0,Oe),ha(cr,0,cr=new Int32Array(G)
,0,Oe)),yr[ar=O++]=C,Ar[ar]=N,cr[ar]=ca(Ve,l+h*C+y*N,f+i*C+A*N,o+g*C+u*N,Ue,Ce,Se,qe,Xe),xr=Da),0==hr&&fa(br,sr[fr=(er+1)%he.length],gr[fr],fr,er,ar,De),0==ir&&fa(br,sr[fr=he.length+(tr+1)%pe.length],gr[fr],fr,he.length+tr,ar,Ge)}if(tr<=0)break;p=E,F=T}if(er<=0)break;v=k,d=m}if(16<=K){if(Q<O)wr=Array((Mr=new Int32Array(Q=O)).length),j=0;else for(er=O;0<=--er;)Mr[er]=0;if(0==j)for(ar=O,j=4;0<=--ar;)wr[ar]=new Int32Array(4);for(er=(tr=he.length)+pe.length;0<=--er;tr=er==he.length?0:er){for(
ar=br[tr],it=sr[tr],lr=er;0<=--ar;)wr[wr[lr][Mr[lr]++]=nr=it[ar]][Mr[nr]++]=lr,lr=nr;wr[wr[lr][Mr[lr]++]=tr][Mr[tr]++]=lr}for(er=O;0<=--er;)for(v=(ur=Ve[(hr=cr[tr=er])>>7])[ir=127&hr],d=ur[ir+128],k=ur[ir+256];0<=--tr;)(ir=cr[tr])!=hr&&(ur=Ve[ir>>7])[ir&=127]==v&&ur[ir+128]==d&&ur[ir+256]==k&&(cr[tr]=hr);for(er=-1;++er<O;)for(ir=cr[tr=er];++tr<O;)if(cr[tr]==ir)for(oa(wr[tr],0,wr[er],Mr[er],Mr[tr]),ar=O,Mr[er]+=Mr[tr],Mr[tr]=0;0<=--ar;)for(lr=Mr[ar],it=wr[ar];0<=--lr;)it[lr]==tr&&(it[lr]=er);for(
er=O;0<=--er;){for(tr=-1,or=Mr[er],it=wr[er];++tr<or;)for(lr=it[ar=tr];++ar<or;)it[ar]==lr&&(it[ar]=it[--or]);Mr[er]=or}for(er=O,fr=0;0<=--er;)for(;0<Mr[er];){for(Pe=Ye=0,x=(v=yr[tr=hr=wr[lr=er][Mr[lr]-1]])-yr[lr],R=(d=Ar[tr])-Ar[lr];;){for(ie=(nr=Mr[tr]--)-1,it=wr[tr],ze=-Number.MAX_VALUE;0<=--nr;)(ar=it[nr])!=lr&&(V=Math.atan2(x*(q=Ar[ar]-d)-R*(S=yr[ar]-v),x*S+R*q))>ze&&(ze=V,$=nr,or=ar);if(it[$]=it[ie],Pe+=ze,(Ir[Ye++]=lr=tr)==er&&or==hr)break;x=-v+(v=yr[tr=or]),R=-d+(d=Ar[tr])}if(0<Pe){
r:for(ar=0,or=Ir[Ye-2],hr=Ir[Ye-1];ar<Ye;or=hr,hr=ir,ar++)if(aa(yr,Ar,or,hr,ir=Ir[ar])>hf){for(lr=ar+Ye-2;--lr>ar;)if(aa(yr,Ar,or,hr,nr=Ir[lr%Ye])>hf&&aa(yr,Ar,hr,ir,nr)>hf&&aa(yr,Ar,ir,or,nr)>hf)continue r;v=(yr[or]+yr[hr]+yr[ir])/3,d=(Ar[or]+Ar[hr]+Ar[ir])/3;break}if(0!=(nr=(0==la(yr,Ar,0,he.length,v,d)?0:1)+(0==la(yr,Ar,he.length,he.length+pe.length,v,d)?0:2))){if(3==nr&&(nr=he.length>pe.length||he.length==pe.length&&(Pr[et]==Qe[rr]||Pr[ft]!=Qe[rr])?1:2),ar=re[(lr=$e+(nr-1)*(nt-$e)
)>>9][511&lr],null==Zr[$=(tr=0==(fr&nr)?lr:Vr++)>>9]&&(te[$]=new Int16Array((ee[$]=new Int16Array((re[$]=new Int16Array((ne[$]=new Int8Array((Zr[$]=Array(512)).length)).length)).length)).length)),ie=511&tr,tr!=lr&&(te[$][ie]=te[(or=re[$][ie]=ar)>>9][511&or],(Je[$]=null==Je[$]?Array(512):Je[$])[ie]=new Float64Array(6),kr=ga(kr,kr.length,tr,1)),tr==$e&&(tt=!0),Pr[ar]!=Qe[rr])for(hr=1+(ir=Ye-1)>>1;0<=--hr;)or=Ir[hr],Ir[hr]=Ir[ir-hr],Ir[ir-hr]=or;for(or=Ye,
Zr[$][ie]=gt=tr==lr&&Ye==Zr[$][ie].length?Zr[$][ie]:new Int32Array(Ye);0<=--or;)gt[or]=cr[Ir[or]];$n(gt,Ve,Je[$][ie]),fr|=nr}}}if(3!=fr){for($n(Zr[nr=(lr=1==fr?nt:$e)>>9][ar=511&lr]=Zr[er=--Vr>>9][tr=511&Vr],Ve,Je[nr][ar]),kr[1==fr?rt:Ke]=kr[ir=kr.length-1],kr=Aa(kr,ir);0<ir--;)if(kr[ir]==Vr){kr[ir]=lr;break}$e==Vr&&($e=lr),2==fr&&(rt=--Ke),re[nr][ar]=re[er][tr],te[nr][ar]=te[er][tr]}}}He[rr]=kr}for(sr=wr=He=cr=br=Mr=Ir=yr=Ar=null,ae.length=Z,wf=ae,to=Pr,yt=Array(rr=J=za=Vr),B=0;0<=--rr;)(tr=(
kr=Zr[(er=ee[or=rr>>9][nr=511&rr]=rr)>>9][511&er]).length)>B&&(B=tr),ha(kr,0,yt[rr]=new Int32Array(tr),0,tr),ne[or][nr]=1;for(ut=Array(3),rr=3,er=(At=Array(B+1)).length;0<=--rr;)ut[rr]=new Int32Array(er);for(rr=B+1,er=je-2+(3*B>>1);0<=--rr;)At[rr]=new Int32Array(er);for(wt=Array((st=new Int32Array(rr=Vr)).length);0<=--rr;)wt[rr]=new Int32Array(0);for(rr=0,bt=new Float64Array((ct=new Float64Array(4294967294&B)).length);rr<Vr;rr++)for(l=(we=Je[nr=(er=rr)>>9][ir=511&rr])[0],h=we[1],f=we[2],i=we[3],
o=we[4],g=we[5],s=(It=ae[Pr[re[nr][ir]]])[0],w=It[1],c=It[2],Mt=te[nr][ir],kr=Zr[nr][ir];++er<Vr;)te[fr=er>>9][or=511&er]!=Mt&&h>(we=Je[fr][or])[0]&&l<we[1]&&i>we[2]&&f<we[3]&&g>we[4]&&o<we[5]&&(a=Math.abs(s*(A=(vt=ae[Pr[re[fr][or]]])[1])-(y=vt[0])*w),0!=(ar=sa(ct,tr=(t=Math.abs(w*(u=vt[2])-A*c))>(n=Math.abs(c*y-u*s))?a<t?-1:1:a<n?0:1,kr,Zr[fr][or],It,vt,Ve))&&0!=(lr=sa(bt,tr,Zr[fr][or],kr,vt,It,Ve))&&(lr<0||ar<0)&&ra(ct,bt,2147483647&ar,2147483647&lr)*pa(t,n,a)>Yn*(tr<0?t:0==tr?n:a)&&(lr<0&&(
wt[er]=ga(wt[er],st[er]++,rr,16)),ar<0&&(wt[rr]=ga(wt[rr],st[rr]++,er,16))));for(Je=null,dt=Array(J<<1),kt=new Int32Array(rr=4096);0<=--rr;)kt[rr]=-1;for(pt=Array(rr=5),er=(mt=new Int32Array(Ee)).length;0<=--rr;)pt[rr]=new Float64Array(er);for(rr=fe,Ft=0;0<=--rr;)0==(V=pa(t=(ur=Ve[(hr=ye[rr])>>7])[hr&=127]-(h=(Et=Ve[(ir=Ae[rr])>>7])[ir&=127]),n=ur[hr+128]-(i=Et[ir+128]),a=ur[hr+256]-(g=Et[ir+256])))&&0==(V=pa(t*=Hn,n*=Hn,a*=Hn))||(t/=V=a<0?-V:V,n/=V,a/=V),ba(t,n,a,h,i,g,hf,pt,kt,mt,Ft)==Ft&&Ft++
;for(Qf[0]=Aa(ye,fe),Qf[1]=Aa(Ae,fe),rr=Vr,Nt=!1,Ct=new Int32Array((Tt=new Int32Array(512)).length<<1);0<=--rr;){for(s=(It=ae[Pr[re[rr>>9][511&rr]]])[0],w=It[1],c=It[2],er=st[Ct[Tt[0]=0]=rr],ir=1,kr=wt[rr],or=(tr=Vr)-1;0<=--er;)for(vt=ae[Pr[re[(rt=kr[er])>>9][511&rt]]],g=Math.abs(a=s*(A=vt[1])-(y=vt[0])*w),St=(ie=(h=Math.abs(t=w*(u=vt[2])-A*c))>(i=Math.abs(n=c*y-u*s))?g<h?-1:1:g<i?0:1)<0?h:0==ie?i:g,t/=V=(a<0?-1:1)*(We=pa(t,n,a)),n/=V,a/=V,We=Yn*St/We,ar=tr-(fr=rr),$=Vr,pe=yt[rt];fr<$;fr+=ar,
ar=1)if((nr=sa(ct,ie,it=Zr[fr>>9][511&fr],pe,It,vt,Ve))<0&&0!=(hr=sa(bt,ie,pe,it,vt,It,Ve))&&ra(ct,bt,2147483647&nr,2147483647&hr)>We)for(Nt=!0,ba(t,n,a,(ur=Ve[(hr=wa(fr,vt,Zr,ne,$r,At,ut,Ue,Ce,Se,qe,Xe,Ve))>>7])[hr&=127],ur[hr+128],ur[hr+256],hf,pt,kt,mt,Ft)==Ft&&Ft++,ir+(nr=(hr=za)-Vr+1)>Ct.length&&ha(Ct,0,Ct=new Int32Array(Ct.length+4096),0,ir),Ct[Tt[lr=fr==rr?0:fr-or]]=nr<<20|ir,Ct[Tt[lr]=ir++]=fr,hr-or>Tt.length&&ha(Tt,0,Tt=new Int32Array(Tt.length+2048),0,Vr-or
);Vr<hr;Ct[Tt[Vr-or]=ir++]=Vr++);dt[rr]=he=new Int32Array(ir);r:for(er=tr=0,$=1048575,nr=1;;)if(1048575<(or=Ct[er])&&(Ct[er]=nr<<20|$,$=er,er=1048575&or,or=-(nr=or>>>20)),0<=(he[tr++]=or)){for(;0==--nr;){if(1048575==$)break r;$=1048575&(nr=Ct[er=$]),nr>>>=20}er++}}for(Tt=Ct=null,Ut=Array((qt=new Int32Array(rr=Ee)).length);0<=--rr;)Ut[rr]=new Int32Array(5);for(gr=ct=bt=wt=st=null,oe=Array((Kr=new Int32Array(xr=Da)).length),Ft=ea(Vr,Ft,Zr,Ve,hf,pt,kt,mt,Ut,qt,Lt=Array(Vr),Kr),rr=xr;0<=--rr;
)oe[rr]=new Int32Array(Kr[rr]);for(rr=Vr;0<=--rr;)for(er=~~((kr=Lt[rr]).length/3);0<=--er;)oe[tr=kr[er]][--Kr[tr]]=er<<18|rr;for(rr=Vr,xt=new Float64Array((Rt=new Int32Array(4)).length);0<=--rr;)for(er=tr=~~((kr=Lt[rr]).length/3),ir=kr[0],gt=null;0<=--er;ir=kr[er])if(kr[tr+er]<0){for(null==gt&&(s=(gt=ae[Pr[re[rr>>9][511&rr]]])[0],w=gt[1],c=gt[2]),or=(he=oe[hr=kr[er]]).length,ht=1,Rt[0]=er<<18|rr;0<=--or;)if(($=262143&(lr=he[or]))!=rr&&((pe=Lt[$])[((fr=(lr>>>=18)+(nr=~~(pe.length/3)))-(ar=-1)
)%nr]==ir||pe[lr=(fr-(ar=1))%nr]==ir)){for(V=Math.atan2(pa(l=w*(a=(gt=ae[Pr[re[$>>9][511&$]]])[2]*ar)-c*(n=gt[1]*ar),f=c*(t=gt[0]*ar)-s*a,o=s*n-w*t),s*t+w*n+c*a),(V*=0<=l*((Et=Ve[ir>>7])[fr=127&ir]-(ur=Ve[hr>>7])[nr=127&hr])+f*(Et[fr+128]-ur[nr+128])+o*(Et[fr+256]-ur[nr+256])?-1:1)<=Qn&&(V+=Wn),fr=0;++fr<ht&&((We=xt[fr])-V>=zn||V-We<zn&&(Lt[262143&(nr=Rt[fr])][nr>>>18]==ir?ar<0&&V<=We:ar<0||V<=We)););we=xt,(nr=ht++)==(it=Rt).length&&(ha(Rt,0,Rt=new Int32Array(Rt.length+2),0,fr),ia(xt,0,
xt=new Float64Array(xt.length+2),0,fr)),ha(it,fr,Rt,fr+1,nr-fr),ia(we,fr,xt,fr+1,nr-fr),Rt[fr]=lr<<18|$,xt[fr]=V}for(ar=rr,lr=1,nr=er,or=tr,pe=kr;0<=--ht;lr=1-ie,nr=fr,or=rt,pe=it)ie=(it=Lt[$=262143&(fr=Rt[ht])])[fr>>>=18]==ir?1:0,it[((rt=~~(it.length/3))<<ie)+fr]=lr*Vr+ar,pe[(or<<lr)+nr]=ie*Vr+(ar=$)}for(Xt=new Int32Array((_t=new Int32Array((Pt=new Int32Array((Vt=new Float64Array(Vr)).length)).length)).length),rr=Vr;0<=--rr;)Xt[rr]=-1;for(Bt=new Int32Array((de=new Uint8Array((ve=new Int32Array(
rr=Vr<<1)).length)).length),Ka=Dt=Gt=0;0<=--rr;)if(!de[rr]){for(de[ve[tr=0]=rr]=!0,er=1;tr<er;tr++)for(Bt[Gt+tr]=lr=ve[tr],(Xt[ar=lr%Vr]<0?Xt:_t)[ar]=Dt,or=(nr=~~((kr=Lt[ar]).length/3))<<~~(lr/Vr);0<=--nr;)de[$=kr[or+nr]]||(de[ve[er++]=$]=!0);for($=(Pt[Dt]=Gt)+er,V=0;Gt<$;Gt++)for(er=1,or=~~((kr=Lt[(tr=Bt[Gt])%Vr]).length/3),hr=1-(~~(tr/Vr)<<1),h=(ur=Ve[(ir=kr[0])>>7])[ir&=127],i=ur[ir+128],g=ur[ir+256],y=(ur=Ve[(ir=kr[1])>>7])[ir&=127],A=ur[ir+128],u=ur[ir+256];++er<or;)V+=((A-i)*((o=(ur=Ve[(
ir=kr[er])>>7])[256+(ir&=127)])-g)-(u-g)*((A=ur[ir+128])-i))*(h+y+(y=ur[ir]))*hr,u=o;(Vt[Dt++]=V/6)<0&&Ka++}for(de=oe=Lt=null,zt=new Int32Array((Yt=new Int32Array((Ot=new Int32Array(rr=Dt)).length)).length);0<=--rr;)Ot[Yt[rr]=zt[rr]=rr]=-1;for(rr=Vr;0<=--rr;){if((er=zt[Xt[rr]])!=(tr=zt[_t[rr]]))for(lr=er+tr-(nr=er<tr?er:tr),Yt[nr]=Yt[Ot[Yt[nr]]=lr],Yt[lr]=-1;-1!=lr;lr=Ot[lr])zt[lr]=nr;ne[rr>>9][511&rr]=0}for(rr=Dt,uf=0;0<=--rr;)if(-1!=(or=Yt[rr])){for(er=rr,V=-Number.MAX_VALUE;Vt[er]>V&&(
V=Vt[er],tr=er),er!=or;er=Ot[er]);for(uf+=V,er=Pt[tr++]-1,or=tr==Dt?Vr<<1:Pt[tr];++er<or;)ne[(nr=(tr=Bt[er])%Vr)>>9][511&nr]|=1+~~(tr/Vr)}xt=Vt=null,Qt=new Int32Array((Wt=new Int32Array(Vr)).length),Rt=_t=Xt=Pt=ve=Bt=Ot=Yt=zt=null,uf=Ia(uf+(V=jr*jr*hf*3),uf-V,!1);r:for(rr=-1,$=Vr;++rr<$;)if(0==ne[er=(Qt[rr]=rr)>>9][or=511&rr]){for(Qt[rr]=-1;;Qt[$]=-1){if(--$<=rr)break r;if(0!=(tr=ne[ar=$>>9][lr=511&$]))break}Zr[(Qt[$]=rr)>>9][or]=Zr[ar][lr],re[er][or]=re[ar][lr],ee[er][or]=ee[ar][lr],
te[er][or]=te[ar][lr],ne[er][or]=tr}for(er=J;0<=--er;){for(nr=or=(kr=dt[er]).length,tr=0;0<=--nr;)0<=(rr=kr[nr])&&0<=(kr[nr]=hr=Qt[rr])&&(tr|=ne[hr>>9][511&hr]);3==tr&&ha(kr,0,dt[er+J]=new Int32Array(or),0,or)}for(er=J,Vr=$;0<=--er;)for(nr=(jt=dt[er]).length,Ht=dt[er+J];0<=--nr;)if(0<=(rr=jt[nr]))if(1==(tr=ne[or=rr>>9][$=511&rr]))null!=Ht&&(Ht[nr]=-1);else if(ir=(hr=(kr=Zr[or][$]).length)-1,3==tr){for(null==Zr[ar=Vr>>9]&&(te[ar]=new Int16Array((ee[ar]=new Int16Array((re[ar]=new Int16Array((
ne[ar]=new Int8Array((Zr[ar]=Array(512)).length)).length)).length)).length)),Zr[ar][lr=511&Vr]=he=new Int32Array(kr.length);0<=--hr;)he[ir-hr]=kr[hr];re[ar][lr]=re[or][$],ee[ar][lr]=ee[or][$],te[ar][lr]=te[or][$],ne[ar][lr]=-(ne[or][$]=1),Ht[nr]=Vr++}else{for(hr>>=1,ne[or][$]=-1;0<=--hr;)fr=kr[hr],kr[hr]=kr[ir-hr],kr[ir-hr]=fr;null!=Ht&&(jt[nr]=-1)}for(er=dt.length;0<=--er;)if(null!=(kr=dt[er])){if((hr=kr[ar=0])<-1)r:for(rr=0,or=-1;;)if((kr[ar]=hr=kr[rr++])<-1)0<=or&&(kr[Qt[or]]=ir,Wt[or]=fr),
Qt[++or]=ar++,ir=fr=hr;else for(hr<0?ir++:ar++;0==++fr;){if(0==ir?ar--:-1==(kr[tr=Qt[or]]=ir)&&ha(kr,tr+1,kr,tr,--ar-tr),0==or)break r;tr=Qt[--or],0==ir&&++kr[tr],ir=kr[tr],fr=Wt[or]}ar<2&&(dt[er]=null)}for(er=dt.length,Kt=Vr,Jt=new Uint8Array(120);0<=--er;)if(null!=(kr=dt[er])){for(rr=0;(hr=kr[rr++])<0;);s=(gt=ae[Pr[tr=re[hr>>9][511&hr]]])[0],w=gt[1],h=(1-(g=-s)*g/(V=1+(c=gt[2])*(Be=c<0?-1:1)))*Be,A=1-(u=-w*Be)*u/V,y=(i=s*u/V)*Be;r:for(lr=1,l=Dr[tr*=3],f=Gr[tr],o=Or[tr];;lr=2)e:for(
rr=ar=nr=Zt=0,or=-1;;)if((kr[ar++]=hr=kr[rr++])<0)0<=or&&(Wt[or]=fr),Qt[++or]=ar-1,fr=hr,nr=lr;else for(1==lr&&Zn(Zr[hr>>9][511&hr],Ve,l,f,o,h,i,g,y,A,u);0==++fr;){if(0==--nr){for(Ke=tr=ie=Qt[or]-(ir=-1),Ze=rt=0,Zt=1;tr<ar;Ze++)for((hr=kr[tr++])<0?($=Ze,ir=hr,hr=kr[tr++]):0==++ir&&($=2147483647),kr[Ke++]=hr,($e=rt+Ze)>(Oe=Jt.length)&&function(r,e,t,n,a){var l,f;if(l=n+a,(f=e-n)<0)for(;--l>=n;)t[l]=r[l+f];else for(;n<l;n++)t[n]=r[n+f]}(Jt,0,Jt=new Uint8Array($e),0,Oe),$e=-1;++$e<Ze;
)Jt[rt++]=$<=$e;for(ir=ie,$=0,$e=Ke;++ir<Ke;)t:for(hr=ie-1;++hr<ir;$++)if(!Jt[$]&&0<=(Me=kr[hr])){for(tr=(he=Zr[Me>>9][511&Me]).length,we=Zr[(Ie=kr[ir])>>9][511&Ie],v=(ur=Ve[(ce=he[0])>>7])[384+(ce&=127)],d=ur[ce+512],rn=(ur=Ve[(ce=we[0])>>7])[384+(ce&=127)],en=ur[ce+512],$t=0;0<=--tr;v=k,d=m)for(fr=we.length,x=(k=(ur=Ve[(ce=he[tr])>>7])[384+(ce&=127)])-v,R=(m=ur[ce+512])-d,p=rn,F=en;0<=--fr;p=E,F=T)if(Math.hypot(U=k-(E=(ur=Ve[(ce=we[fr])>>7])[384+(ce&=127)]),L=m-(T=ur[ce+512]))>hf&&Math.hypot(
S=p-v,q=F-d)>hf&&Math.abs(S*R-q*x)<(S*x+q*R)*Gn&&Math.abs(U*R-L*x)<(U*x+L*R)*Gn){if(0<$t++)continue t;t=v,n=d,s=k,w=m,C=p,N=F,b=E,M=T,Ze=tr,rt=fr}if(0<$t){for(tr=he.length;0<=--tr;)for(fr=we.length,ce=he[tr];0<=--fr;)if(we[fr]==ce){if(Math.hypot((v=(ur=Ve[ce>>7])[384+(ce&=127)])-t,(d=ur[ce+512])-n)<=hf?Math.hypot(v-b,d-M)>hf:Math.hypot(v-s,d-w)>hf||Math.hypot(v-C,d-N)>hf)continue t;break}for((nt=he.length+we.length-(tn=ta(t,n,b,M,rt,Ze,we,he,Ve))-(nn=ta(s,w,C,N,Ze,rt,he,we,Ve))
)==he.length||nt==we.length?(ln=Ze+rt-(an=nt==he.length?Ze:rt)+2,3==(it=(pe=nt==he.length?he:we)==he?we:he).length?pe[(an+((nt==he.length?tn:nn)>>1))%pe.length]=it[ln%3]:(pe[an]=it[3&ln],pe[(an+1)%pe.length]=it[ln+1&3])):(ha(he,an=(Ze+(tn+3>>1))%he.length,pe=new Int32Array(nt),0,fn=((ln=Ze+(3-nn>>1))>an?ln:he.length)-an),(on=ln-an)<=0&&(on+=he.length,ha(he,0,pe,fn,ln)),ha(we,an=(rt+(nn+3>>1))%we.length,pe,on,fn=((ln=rt+(3-tn>>1))>an?ln:we.length)-an),ln<=an&&ha(we,0,pe,on+fn,ln)),Zr[(
kr[ir]=nt=Me+Ie-(ln=Ie<Me?Me:Ie))>>9][511&nt]=pe,an=ir-ie-1,Zr[ln>>9][511&ln]=null,ln=Ke-ie+(kr[hr]=-1),fn=$+(on=ir-hr),$e--,Kt--;++an<ln;)Jt[fn+=an]&=Jt[fn-on]}}if(1==ie)break r;if(kr[ie-1]=ie-$e,(ar=$e)<Ke)t:for(;ie<Ke;ie++)if(kr[ie]<0){do{if(--Ke<=ie)break t}while(kr[Ke]<0);kr[ie]=kr[Ke]}}if(0==or){if(0!=Zt)break e;break r}fr=Wt[--or],nr=lr-1}}if(Jt=Wt=Qt=null,Kt<Vr){r:for(rr=-1,P=0;++rr<Kt;){if(null==(kr=Zr[tr=rr>>9][or=511&rr])){do{if(--Vr<=rr)break r}while(null==Zr[ar=Vr>>9][lr=511&Vr])
;Zr[tr][or]=kr=Zr[ar][lr],re[tr][or]=re[ar][lr],ee[tr][or]=ee[ar][lr],te[tr][or]=te[ar][lr],ne[tr][or]=ne[ar][lr]}(er=kr.length)>P&&(P=er)}if(Vr=Kt,B<P){for(At=Array(P+1),rr=P+1,er=je-2+(3*P>>1);0<=--rr;)At[rr]=new Int32Array(er);for(ut=Array(rr=3);0<=--rr;)ut[rr]=new Int32Array(At.length)}}for(rr=za=Vr,tr=-1,hn=Array(512);0<=--rr;hn[er][511&rr]=tr,tr=rr)null==hn[er=rr>>9]&&(hn[er]=new Int32Array(512));r:for(ir=yn=0,An=nr=-1,gn=2,un=null,kr=new Int32Array(je),wn=new Int32Array(je),sn=Array(256
);;An--){for(er=ir,rr=-1;0<=er;er=hn[rt][ie])wn[tr=ho[re[rt=er>>9][ie=511&er]]]!=An&&(wn[tr]=An,rr<0?rr=tr:kr[or]=tr,or=tr);for(tr=0,kr[or]=-1,or=2147483647;0<=rr;rr=kr[rr]){for(er=ir,$=fr=hr=0;0<=er;er=hn[rt][ie])ho[bn=re[rt=er>>9][ie=511&er]]==rr?$++:(3==(lr=ua(he=Zr[rt][ie],cn=ae[Qe[rr]],Ve))&&(fr+=function(r,e,t,n,a){var l,f,o,h,i,g,y,A,u,s,w,c,b,M,I,v,d,k,m,p,F,E,T,C,N,S,q,U,L,x,R,V,X,_;for(f=(_=wf[to[n]])[0]*r,o=_[1]*r,h=_[2]*r,i=t[0],g=t[1],y=t[2],A=t[3],V=0;;V++)if(Math.abs(C=(c=(l=a[(
R=e[V])>>7])[R&=127])*i+(b=l[R+128])*g+(M=l[R+256])*y+A)>hf){q=C/Math.abs(C);break}for(X=V+++e.length,N=x=0;;V++){if(U=Math.abs(C=(I=(l=a[(R=e[V%e.length])>>7])[R&=127])*i+(v=l[R+128])*g+(d=l[R+256])*y+A)>hf?C/Math.abs(C):0,0==N)0==U?N=1:U!=q&&x++;else if(1==N)0!=U&&U!=S?(x++,N=0):(N=((m=b-s)*(T=d-M)-(E=v-b)*(p=M-w))*f+(p*(F=I-c)-T*(k=c-u))*o+(k*E-F*m)*h<0?8:2,0==U?L=S:(x+=N>>2,N=0));else{if(0==U){c=I,b=v,M=d;continue}x+=U!=L?1:N>>2,N=0}if(X<=V)return x>>1;u=c,s=b,w=M,S=q,c=I,b=v,M=d,q=U}}(
ne[rt][ie],he,cn,bn,Ve)),hr|=lr);(0!=$||3==hr)&&fr<=or&&(fr<or||tr<$)&&(ar=rr,or=fr,tr=$)}for(null!=un&&(un[gn]=yn),cn=ae[Qe[((sn[rt=yn>>8]=null==sn[rt]?Array(256):sn[rt])[255&yn++]=un=new Int32Array(tr+3))[0]=ar]],tr=ir,hr=ir=-1,$=3;0<=(er=tr);)if(tr=hn[rt=er>>9][ie=511&er],ho[re[rt][ie]]==ar)un[$++]=er;else{if(3==(lr=ua(he=Zr[rt][ie],cn,Ve))){for(Nt=!0,wa(er,cn,Zr,ne,$r,At,ut,Ue,Ce,Se,qe,Xe,Ve),lr=ua(Zr[rt][ie],cn,Ve),fr=Vr,Vr=za;fr<Vr;hn[$e][511&fr]=tr,tr=fr++)null==hn[$e=fr>>9]&&(
hn[$e]=new Int32Array(512));hn[rt][ie]=tr}1==lr?(hr<0?hr=er:hn[or>>9][511&or]=er,or=er):(ir<0?ir=er:hn[rr>>9][511&rr]=er,rr=er)}for(0<=ir&&(hn[rr>>9][511&rr]=-1),0<=hr&&(hn[or>>9][511&or]=-1),un[1]=ir,un[2]=hr;;){if(1==(gn=3-gn)&&++nr>=yn)break r;if(0<=(ir=(un=sn[nr>>8][255&nr])[gn]))break}}for(er=yn+256-((rr=yn+255>>8)<<8),Bf=Array(yn);0<=--rr;er=256)oa(sn[rr],0,Bf,rr<<8,er);for(io=new Int32Array(je*Rr+15>>4),rr=lo.length;0<=--rr;)lo[rr]=-1;for(Of=Array((rr=je)<<1),ir=Da,yo=Array($=rl=Vr
);0<=--rr;){for(or=rr*(er=Rr),cn=ae[Qe[rr]],vr=dr=new Int32Array(Mn=In=0);0<=--er;)if(io[(nr=or+er)>>4]|=(lr=ua(Lf[er],cn,Ve))<<((15&nr)<<1),3==lr)for(nr=(kr=Gf[er]).length;0<=--nr;)if(3==(lr=ua(he=xf[tr=kr[nr]],cn,Ve)))for(null==Zr[hr=Vr>>9]&&(te[hr]=new Int16Array((ee[hr]=new Int16Array((re[hr]=new Int16Array((ne[hr]=new Int8Array((Zr[hr]=Array(512)).length)).length)).length)).length)),ha(he,0,Zr[hr][ar=511&Vr]=new Int32Array(he.length),0,he.length),ne[hr][ar]=1,te[hr][ar]=te[(
fr=re[hr][ar]=Jf[tr])>>9][511&fr],ee[hr][ar]=lo[tr]=lo[tr]<0?J++:lo[tr],za++,Nt=!0,wa(Vr,cn,Zr,ne,$r,At,ut,Ue,Ce,Se,qe,Xe,Ve),fr=za;1==(lr=ua(Zr[hr][ar],cn,Ve))?vr=ga(vr,Mn++,Vr,8):dr=ga(dr,In++,Vr,8),!(++Vr>=fr);)hr=Vr>>9,ar=511&Vr;else 1==lr?vr=ga(vr,Mn++,1073741824|tr,8):dr=ga(dr,In++,1073741824|tr,8);ha(vr,0,Of[er=rr<<1]=new Int32Array(Mn),0,Mn),ha(dr,0,Of[er+1]=new Int32Array(In),0,In)}for(yt.length=J,rr=H;0<=--rr;)0<=(er=lo[rr])&&ha(kr=xf[rr],0,yt[er]=new Int32Array(kr.length),0,kr.length)
;for(!function(r,e,t,n,a){var l,f;if(l=n+a,(f=e-n)<0)for(;--l>=n;)t[l]=r[l+f];else for(;n<l;n++)t[n]=r[n+f]}(Jf,0,Jf=new Int16Array((rr=Vr-$)+H),rr,H);0<=--rr;)Jf[rr]=re[(er=rr+$)>>9][511&er];for(rr=je<<1;0<=--rr;)for(er=(kr=Of[rr]).length;0<=--er;)1073741824<=(tr=kr[er])&&(kr[er]=(268435455&tr)+Vr);for(or=2,rr=H,$a=Vr;0<=--or;rr=Rr)for(er=Vr+=rr,vn=0<or?xf:Xr;0<=--rr;)null==Zr[tr=--er>>9]&&(ne[tr]=new Int8Array((Zr[tr]=Array(512)).length)),ne[tr][nr=511&er]=1,ha(kr=vn[rr],0,
Zr[tr][nr]=new Int32Array(kr.length),0,kr.length);if(ea(za=Vr,Ft,Zr,Ve,hf,pt,kt,mt,Ut,qt,null,null),Ut=At=ut=dt=Xe=hn=qt=mt=kt=pt=null,(xr=Da)>Lr){for(Kr=new Int32Array(rr=xr);--rr>=Ya;)Kr[rr]=-1;for(rr=Ya;0<=--rr;)Kr[rr]=rr;for(rr=Vr;0<=--rr;)for(er=(kr=Zr[rr>>9][511&rr]).length;0<=--er;)Kr[tr=kr[er]]=tr;r:for(rr=Ya-1,er=ir;++rr<ir;)if(Kr[rr]<0){do{if(--ir<=rr)break r}while(Kr[ir]<0);Kr[ir]=rr}for(Qr=mf=new Float64Array((Wr=kf=new Float64Array((zr=df=new Float64Array((If=new Float64Array((
Mf=new Float64Array(ir=xr-(tr=er-ir))).length)).length)).length)).length),rr=xr;--rr>=er;)Kr[rr]=rr-tr;for(rr=xr;0<=--rr;)0<=(tr=Kr[rr])&&(zr[tr]=(ur=Ve[rr>>7])[ar=127&rr],Wr[tr]=ur[ar+128],Qr[tr]=ur[ar+256]);for(xr=Da=ir,rr=Vr;0<=--rr;)for(er=(kr=Zr[rr>>9][511&rr]).length;0<=--er;)kr[er]=Kr[kr[er]]}for(Kr=qe=Qe=wn=Ve=null,rr=$a,kr=new Int32Array(Rr),dn=Array((pr=new Int32Array(J)).length);0<=--rr;)pr[ee[er=rr>>9][tr=511&rr]]++,rr<$&&kr[re[er][tr]]++;for(rr=Rr;0<=--rr;)Br[rr]=new Int32Array(
kr[rr]),kr[rr]=0;for(rr=J;0<=--rr;)dn[rr]=new Int32Array(pr[rr]),pr[rr]=0;for(rr=$a,P=0;0<=--rr;)dn[tr=ee[or=rr>>9][nr=511&rr]][pr[tr]++]=rr,(tr=Zr[or][nr].length)>P&&(P=tr),rr<$&&(Br[er=re[or][nr]][kr[er]++]=rr,yo[rr]=(tr=Er[er])<0?_b[31&-tr]:Tr[tr]);for(er=Vr+512-((rr=Vr+511>>9)<<9),Zf=new Int8Array((Rf=Array(Vr)).length);0<=--rr;er=512)oa(Zr[rr],0,Rf,tr=rr<<9,er),function(r,e,t,n,a){var l,f;if(l=n+a,(f=e-n)<0)for(;--l>=n;)t[l]=r[l+f];else for(;n<l;n++)t[n]=r[n+f]}(ne[rr],0,Zf,tr,er);for(
ne=Zr=sn=null,qf=Array((Uf=Array($a)).length),dr=new Int32Array((vr=new Int32Array((mr=new Int32Array(P)).length+1)).length),Nt&&(pr=new Int32Array(P)),kn=Pf=Array(Vr),mn=Mf,pn=If,Fn=new Int32Array(0),En=new Int32Array(0),fr=J;0<=--fr;)if(0!=(Tn=dn[fr]).length){for(V=1+(c=(we=ae[Pr[bn=re[(rr=Tn[0])>>9][511&rr]]])[2])*(Be=c<0?-1:1),h=(1-(g=-we[0])*g/V)*Be,A=1-(u=-we[1]*Be)*u/V,y=(i=-g*u/V)*Be,l=Dr[tr=3*bn],f=Gr[tr],o=Or[tr],er=(pe=yt[fr]).length;0<=--er;)mn[ir=pe[er]]=h*(t=zr[ir]-l)+i*(n=Wr[ir]-f
)+g*(a=Qr[ir]-o),pn[ir]=y*t+A*n+u*a;for(rr=Tn.length;0<=--rr;){for(er=(gt=Rf[$=Tn[rr]]).length;0<=--er;)mn[ir=gt[er]]=h*(t=zr[ir]-l)+i*(n=Wr[ir]-f)+g*(a=Qr[ir]-o),pn[ir]=y*t+A*n+u*a;for(kr=vr,Gt=pe.length-1,it=Array(0),v=mn[ir=gt[qn=lr=(1-(hr=Zf[$])>>1)*((ar=gt.length)-1)]],d=pn[ir],Nn=Sn=-1,Cn=er=tr=nr=0;0<=--ar;){for(V=Math.hypot(x=(k=mn[ce=gt[Un=lr+hr*ar]])-v,R=(m=pn[ce])-d),or=Gt,p=mn[be=pe[0]],F=pn[be];E=mn[Xn=pe[or]],T=pn[Xn],De=Ge=Number.MAX_VALUE,(Xn==ce&&be==ir||(De=Math.hypot(S=E-v,
q=T-d))>hf&&(Ge=Math.hypot(U=k-p,L=m-F))>hf&&Math.abs(S*R-q*x)<(S*x+q*R)*Gn&&Math.abs(U*R-L*x)<(U*x+L*R)*Gn)&&((Pn=Ge<V?be:ir)!=ir||0!=nr&&mr[nr-1]==qn||(mr[nr++]=qn),(Bn=De<V?Xn:ce)!=ce||0!=nr&&mr[0]==Un||(mr[nr++]=Un),0!=er&&Pn==Sn||(0==er?(Nn=Pn,Rn=qn):(kr==vr?(tr=er,kr=dr,Vn=xn):(Fn=ga(Fn,it.length,Ln,1),En=ga(En,it.length,xn,1),it=ya(it,he=new Int32Array(er)),ha(kr,0,he,0,er),Cn+=er),Ln=qn),kr[0]=Pn,er=1),kr[er++]=Sn=Bn,xn=qn),0!=or;or--)be=Xn,p=E,F=T;ir=ce,qn=Un,v=k,d=m}if(0<=Nn)if(
Nn!=Sn?(kr==vr?(tr=er,Vn=xn):(Fn=ga(Fn,it.length,Ln,1),En=ga(En,it.length,xn,1),it=ya(it,he=new Int32Array(er)),ha(dr,0,he,0,er),Cn+=er),Fn=ga(Fn,it.length,Rn,1),En=ga(En,it.length,Vn,1),qf[$]=it=ya(it,he=new Int32Array(tr)),ha(vr,0,he,0,tr),Cn+=tr):0==tr?Cn=gt.length:(Fn=ga(Fn,it.length,Ln,1),En=ga(En,it.length,Vn,1),qf[$]=it=ya(it,he=new Int32Array(ar=--er+tr)),ha(dr,0,he,0,er),ha(vr,0,he,er,tr),Cn+=ar),0==it.length)Uf[$]=Array(0);else for(Uf[$]=Dn=Array(it.length),tr=-1,or=it.length-1,
hr=gt.length-hr;++tr<it.length;or=tr){if(qn=En[or],vr[0]=ce=(he=it[or])[he.length-(er=1)],Un=Fn[tr],be=it[tr][0],qn==Un&&Math.hypot((v=mn[Nn=gt[qn]])-mn[ce],(d=pn[Nn])-pn[ce])<Math.hypot(v-mn[be],d-pn[be])&&(vr[er++]=be),1==er){for(ce!=(ir=gt[Ln=(qn+hr)%gt.length])&&Math.hypot(mn[ir]-mn[ce],pn[ir]-pn[ce])>hf&&(vr[er++]=ir);Ln!=Un;)vr[er++]=ir=gt[Ln=(Ln+hr)%gt.length];ir!=be&&Math.hypot(mn[be]-mn[ir],pn[be]-pn[ir])>hf&&(vr[er++]=be)}ha(vr,0,Dn[tr]=new Int32Array(er),0,er)}else qf[$]=it=Array(0)
;if(nr==gt.length&&Cn==gt.length)kn[$]=gt;else{if(ha(gt,0,pr,0,er=gt.length),0<nr){for(;0<nr;)pr[mr[--nr]]=-1;for(ar=er=0;ar<gt.length;)0<=(pr[er]=pr[ar++])&&er++}for(ha(pr,0,kn[$]=jt=new Int32Array(Cn+er),0,er),ar=0;ar<it.length;er+=he.length)ha(he=it[ar++],0,jt,er,he.length)}}}for(rr=Vr;--rr>=$a;)(er=(kn[rr]=Rf[rr]).length)>P&&(P=er);for(dn=$r=Tr=Cr=vr=dr=mr=pr=Fn=En=Er=null,Yf=Array(rr=2),er=(tr=P>(Qa=le)?P:le)>B?tr:B;0<=--rr;)Yf[rr]=new Int32Array(er);for(Wf=Array(rr=2),er=(
eo=new Int32Array(xr)).length;0<=--rr;)Wf[rr]=new Int32Array(er);ao=new Int32Array(($f=new Int8Array(H<Vr?Vr:H)).length>H<<1?$f.length:H<<1),jf=new Uint8Array(Vr),oo=new Int32Array(yn),Hl=Jl=Kl=Zl=$l=rf=!1,Kn.addEventListener("contextmenu",Ea,!1),Kn.addEventListener("mousedown",Ta,!1),Kn.addEventListener("touchstart",Ca,!1),document.addEventListener("mouseup",Na,!1),document.addEventListener("touchend",Sa,!1),document.addEventListener("mousemove",qa,!1),document.addEventListener("touchmove",Ua,
!1),document.addEventListener("mouseleave",La,!1),Ql=jl=0,xa(),Ra()}())}window.addEventListener("load",_r,!1),_q=["penta","hexa","hepta","octa","ennea","deca","hendeca","dodeca","trideca","tetradeca","pentadeca","hexadeca","ditrigon","triambus","ditetragon","tetrambus","dipentagon","pentambus","dihexagon","hexambus","diheptagon","heptambus","dioctagon","octambus"],_e=["","bi-","tri-"];
